### ISSUE TITLE
Display details tag in document more clearly

### ISSUE THREAD

**Issue by eggplants** [pypa/warehouse#10056]
**What's the problem this feature will solve?**

When viewing the markdown containing the details tag as a document on the PyPI project page, it is difficult to see that the details tag can be clicked and expanded because it looks like any other text.

Before expanding:
![image](https://user-images.githubusercontent.com/42153744/133916603-91f789e4-03c8-41f0-bdc8-07ea90fafca7.png)

After expanding:
![image](https://user-images.githubusercontent.com/42153744/133916535-9596f6e3-4048-4ae5-a948-320621a1cbe4.png)

**Describe the solution you'd like**

For example, I think it is better to display a right-facing triangle next to the summary text in the details tag like GitHub:

![image](https://user-images.githubusercontent.com/42153744/133916575-5e757445-385f-4298-9f6f-3103648e0e66.png)

**Additional context**

Screenshots was taken at: <https://pypi.org/project/simpleverse>

**Comment by ewjoachim** [comment]
This is caused by https://github.com/necolas/normalize.css/issues/604 which has been resolved 5 years ago. If we update our very old version of normalize.scss, then this bug will be solved.

**Comment by ewjoachim** [comment]
Just because it's always annoying to not have the opportunity to learn, if anyone is interested, here's how I found it:
- Watched how it appeared in GitHub vs PyPI, found that there was no specific style applied for the "triangle" to appear.
- Realized that it was builtin in browsers (by trying it on an empty page), so it was probably some code on pypi that made the triangle disappear rather than some code needed for the triangle to appear.
- Using the web developper tools on PyPI.org, tried disabling the CSS rules one by one on either `<details>` or `<summary>` until the triangle reappeared. It did when I disabled `display: block` on `summary`.
- Saw that the triangle either appeared when the `<summary>` was not set or set to `display: list-item`; which told me this was the intended display mode
- Searched the codebase for `summary` inside [`warehouse/static/scss`](https://github.com/pypa/warehouse/blob/main/warehouse/static/sass/resets/_normalize.scss#L60), found the line in `_normalize.scss`. File header says it's 3.0.2. So it seems to be a normalize bug then.
- [Searched `summary`](https://github.com/necolas/normalize.css/blame/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L329) in the newest normalize, found a [commit](https://github.com/necolas/normalize.css/commit/55ed05a79c0fd7a9a2c330c6925b982a7d5b307c) linked to a [PR](https://github.com/necolas/normalize.css/pull/606) linked to a [ticket](https://github.com/necolas/normalize.css/issues/604).

**Comment by eggplants** [comment]
Thank you for your answering and debugging! I hope that a quick update of normalize.scss will be done. (without introducing any new bugs...)

**Comment by ewjoachim** [comment]
- The short path: add a rule in warehouse.scss setting `summary { display: list-item; }`
- The less short path: copy paste a new(er) normalize in `_normalize.scss`
- The better path: remove `_normalize.scss`, `npm add normalize.css` and include it from `node_modules`.
- The best path: take this opportunity to remove the dust on our package.json file, update all libs, and setup dependabot.
- The bestest path: The one above plus we add integration tests, with a few screenshot regression tests, so that when we have dependabot PRs, we can be reasonably confident that they don't break anything.

**Comment by di** [comment]
My preference would be for "the better path": I'm not sure why `normalize.scss` is vendored in. Including it as a node module instead sounds like a good solution here.

**Comment by eggplants** [comment]
Thank you for the quick response!

**Comment by ewjoachim** [comment]
Thank you for the simple, intersting, actionnable, useful, kind and respectful issue :)
