### ISSUE TITLE
Fix extra letters bypass problem

### ISSUE THREAD

**Issue by OLZUP** [pypa/warehouse#10192]
**What's the problem this feature will solve?**
The fact that some profanity is not caught because some letters or numbers are added to the end of it. For example ghtprofanityght the profanity is there but not caught by the filter because of extra letters.

**Describe the solution you'd like**
Using REGULAR EXPRESSIONS special characters to find any profane words even with any letters or numbers added to it.

**Comment by ewjoachim** [comment]
As far as I can tell, the code of warehouse itself doesn't define profanity words, we just have a list of prohibited project names in the database, which happens to include offensive words. While we could make our search a bit more exhaustive, it would make a lot of sense in many cases.

For example, we may want to ban the name `request` because it's too close to `requests`, but we don't want to base `requests` itself, or a new package named `requests-async` or `requests-http3` or something (a third party package). If we wanted to do this, we would need to actually add in the DB a column scpecifying which names are forbidden because they're offensive and which ones because they look too much like existing package (and there's also copywrighted stuff etc), and then make special rules for querying this table. Also, we currently have ~26000 entries in the table, which we would need to categorize somehow. We probably wouldn't have to do it 100% by hand, but I believe this would be quite some work.

And even if we would do all that, people would still be registering `prof-anity` and `pr0f4ni7y` and `prof*ckingfanity` and `proofanity` and `profinaty` and `more subtle racist dogwhistle slur with a plausible deniablity` and ...

It's a never ending game.
