### ISSUE TITLE
The user '' isn't allowed to upload to project 'cinnamon'.

### ISSUE THREAD

**Issue by YohannLeFaou** [pypa/warehouse#10217]
I face a problem to upload a project called "cinnamon" on pypi.

I don't find on the PyPi index any project having the name "cinnamon" : https://pypi.org/search/?q=cinnamon

This is really a name problem because the I changed the name to "baloulou" and then the upload worked : https://pypi.org/project/baloulou/

I check the https://pypi.org/help/#project-name but I can't explain why it does not wokr with the name "cinnamon".

Can you help me on this ?

**Comment by ewjoachim** [comment]
I'm seeing multiple things here:
The project named Cinnamon exists: https://pypi.org/project/cinnamon/ . Not sure why the search cannot find it though but I would guess it's because we have a project that has 1 release which has no files.
That being said, it was created in 2013 and didn't receive a release so it's definitely eligible for  a PEP-541 procedure, you can open a ticket at https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+cinnamon.

I believe on the Warehouse repo, there's not much to do except investigating why the project doesn't appear in the search results, but I think we have a convincing explanation already, so I'm inclined to close this ticket, if you're ok.

(Also, don't forget to delete baloulou if you don't plan on using it)
