### ISSUE TITLE
Search relevancy is still not ideal

### ISSUE THREAD

**Issue by di** [pypa/warehouse#1029]
#1020 fixed #1019 for the majority of packages, however a few still produce odd results:

For example:
https://warehouse.python.org/search/?q=flask (`Flask` package is 2nd, `Flask-Admin` is first)
https://warehouse.python.org/search/?q=django (`Django` package is 11th, `dotulu` is first)
https://warehouse.python.org/search/?q=git (First 3 packages do not have "git" anywhere in them)

This is hard to test in dev because the dev DB is a snapshot of TestPyPI, and those packages are missing.

@dstufft, would it be possible to get a more complete DB for local development?

**Comment by dstufft** [comment]
Yea, I'll see if I can't just dump the regular PyPI database and sanitize it.

**Comment by dstufft** [comment]
Sorry for the delay. I have a snaphot of the real PyPI I can send you, but I'd rather not add it to the repository because even compressed it's quite large (~270MB) and although I sanitized it I'd rather not risk having missed something. Is there an email address or something I can send you a link via?

**Comment by dstufft** [comment]
Assuming you're still interested in this anyways!

**Comment by di** [comment]
Sure! You can use the address on my github profile.
