### ISSUE TITLE
Package splitapiclient does not accept new version installation using pip

### ISSUE THREAD

**Issue by chillaq** [pypa/warehouse#10351]
**Describe the bug**
splitapiclient package has 4 versions, latest is 3.0.2 which shows up in pypi.org UI, however, using pip to install latest version does not work, see below:
% pip3 install 'splitapiclient==3.0.2'
ERROR: Could not find a version that satisfies the requirement splitapiclient==3.0.2 (from versions: 1.0.0, 3.0.0)
ERROR: No matching distribution found for splitapiclient==3.0.2

From the UI if I download the latest version files, it is actually 3.0.2 (https://pypi.org/project/splitapiclient/)

**Expected behavior**
pip install should fetch the latest version 

**To Reproduce**
Run command below:
% pip3 install 'splitapiclient==3.0.2'

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by chillaq** [comment]
Hi @di  The issue is the pypi.org is not returning the correct version when pip command used, so the issue with pip command, where do I report it?

**Comment by di** [comment]
Hi @chillaq, the issue is likely because the project only published `.egg` files for Python 3.8: https://pypi.org/project/splitapiclient/3.0.2/#files

**Comment by abitrolly** [comment]
@chillaq if you're using different Python version then fill a report in `pip3` to provide a better error message, because this one is not informative.
```
ERROR: Could not find a version that satisfies the requirement splitapiclient==3.0.2 (from versions: 1.0.0, 3.0.0)
ERROR: No matching distribution found for splitapiclient==3.0.2
```
The requirement is not `splitapiclient==3.0.2` (which exists), but `python==x.y + splitapiclient==3.0.2` (which probably isn't). If `pip` could say that it "Found splitapiclient==3.0.2 for Python m.n, but not for Python x.y` that would save everybody a lot of time.
