### ISSUE TITLE
Circular dependency in Makefile

### ISSUE THREAD

**Issue by di** [pypa/warehouse#10447]
From https://github.com/pypa/warehouse/pull/10278#issuecomment-974902013: 

> I believe this change has introduced a circular dependency, as perceived by these messages:
> 
> ```shellsession
> $ make -v | head -1
> GNU Make 3.81
> $ make build
> make[1]: Circular requirements/docs.txt <- .state/env/pyvenv.cfg dependency dropped.
> ...
> ```
> 
> For funsies, I tried the same with [remake](http://bashdb.sourceforge.net/remake/), which uses a newer version of `make`:
> 
> ```shellsession
> $ remake --version | head -1
> GNU Make 4.3+dbg-1.5
> $ remake build
> remake[1]: Entering directory '/Users/miketheman/workspace/miketheman/warehouse'
> remake[1]: Circular requirements/docs.txt <- .state/env/pyvenv.cfg dependency dropped.
> remake[1]: Circular requirements/lint.txt <- .state/env/pyvenv.cfg dependency dropped.
> remake[1]: '.state/docker-build' is up to date.
> ...
> ```
> 
> I don't know if this is harmful yet, but I'm having other issues getting started with development, and wondered if this is somehow related or not.

_Originally posted by @miketheman in https://github.com/pypa/warehouse/issues/10278#issuecomment-974902013_

**Comment by ewjoachim** [comment]
Reposting my comment:
I think we could mostly solve the problem by making the targets more granular, but at core we need to solve something: in order to install pip-compile, we need to know which version to install it too, which means we need to run pip-compile and so on.
If we install pip-compile without the hashes, it kinda defeats the purpose of using hashes in the first place.

So one solution could be to not declare to make that the pip-compile target needs the pip-compile requirement file, considering that it doesn't often change, and the venv gets recreated once in a while anyway.

So we would have:
- A target for venv creation but not installation of dependencies
- a target for pip-tools that would depend on that one, which would actually use the requirements/pip-tools.txt file but wouldn't say it
- requirements/*.txt would depend on that one
- the full environement target, the one everyone uses, would use the relevant .txt files and declare it.

I believe it would work.

**Comment by di** [comment]
Or, we could take this as an opportunity to move more towards #4948, since it doesn't make a ton of sense right now for us to compile dependencies on one platform (the host OS) to be used on a different platform (inside the container images), which removes the need to build dependencies in the virtual environment.

**Comment by abitrolly** [comment]
Why not to vendorize `pip-compile`?

**Comment by abitrolly** [comment]
For example with `pex`.

```python
pip install pex
pex pip-tools --console-script pip-compile --output-file pip-compile.pex
```
```
-rwxr-xr-x 1 root root 4750609 Dec  7 10:53 pip-compile.pex
```
