### ISSUE TITLE
my private email is shown even though added public one

### ISSUE THREAD

**Issue by CatOw** [pypa/warehouse#10537]
I've added a public email for interacting with me, which is ccuiproject email in image a, whereas in image b when I click the CatOw (Mail) it offers my private email, which I don't want to be public. I want it to be ccuiproject instead just like in image a. How do I fix that? I couldn't find a solution

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.
![b](https://user-images.githubusercontent.com/46374809/147769017-ec251c81-13a4-4bae-9480-f693fbde9738.png)
![a](https://user-images.githubusercontent.com/46374809/147769022-ebcd0410-72c1-47e7-b471-7af2e72e2d43.png)

**Comment by yeraydiazdiaz** [comment]
Hi @CatOw, the "author" email is picked up from your project's `setup.py` via the `author_email`, this cannot be changed AFAIK because releases are immutable.

A workaround is to publish a new release with your public email as the `author_email`, and then delete the previous release which contains the private one. Do note you will have to increase the  version number because PyPI does not allow uploading files with the same name.

**Comment by CatOw** [comment]
This indeed worked. Thank you very much!
