### ISSUE TITLE
504 Gateway Time-out when loading images.

### ISSUE THREAD

**Issue by domdfcoding** [pypa/warehouse#10673]
**Describe the bug**
Images on project pages (e.g. https://pypi.org/project/setuptools/, https://pypi.org/project/isort/) from `warehouse-camo.ingress.cmh1.psfhosted.org` fail to load with a `504 Gateway Time-out` error.

Except from the Firefox dev tools:

![image](https://user-images.githubusercontent.com/8050853/152116084-954df7cf-004f-4613-8b68-a4ccb4a840fb.png)

**Expected behavior**

The images load and display correctly.

**To Reproduce**

Visit https://pypi.org/project/setuptools/, ideally with your browser's dev tools (F12) open to the Network page.

**My Platform**

Tried with Firefox and Chrome on Ubuntu and Chrome on Android, from multiple networks.

**Comment by ewdurbin** [comment]
Thanks for your report. This has been resolved, but needs further attention.

Our instance of camo crashes somewhat regularly due to https://github.com/pypa/warehouse-camo/pull/5#issuecomment-947034444, but is normally rekicked by Kubernetes, seems it gave up trying which caused this outage.

Goal is to move to https://github.com/cactus/go-camo long term, which is maintained.
