### ISSUE TITLE
Allow win-arm64 as a wheel platform

### ISSUE THREAD

**Issue by zooba** [pypa/warehouse#10762]
Upstream, we are planning (hoping... all going well) to release 3.11 with native support for Windows ARM64.

`pip` already handles `win-arm64` as the tag, and there should be no need to change this in the future.

The main risk to the release plan is if the ecosystem is completely unviable for users. The most likely reason for this would be lack of any free CI support, but we're hoping that will become available during the 3.11 beta releases. The second reason would be lack of Warehouse support for wheels, so I'm hoping to get this one out of the way :)

**Comment by di** [comment]
It's already allowed since #10338:

https://github.com/pypa/warehouse/blob/eb241f9061633752672a07851cd553ad4c5cd24a/warehouse/forklift/legacy.py#L107-L112

And there are already releases on PyPI with distributions for this platform:

- https://pypi.org/project/maturin/#files
- https://pypi.org/project/pypdfium2/#files

Is there something else that we need to do here?

**Comment by zooba** [comment]
Haha, one of my colleagues is ahead of me! Perfect, nothing else neededd
