### ISSUE TITLE
Invalidate active sessions on password change

### ISSUE THREAD

**Issue by di** [pypa/warehouse#10849]
In the event of a password change, all other active sessions should be invalidated.

**Comment by ewjoachim** [comment]
Let me try, but if you don't see a PR by the end of the week, consider it free for grabs :)

**Comment by ewjoachim** [comment]
I guess there can be 2 main ways of doing this:
- One would be to actively delete existing entries from the session cache but it would mean being able to scan all sessions and I'm not sure it's ideal, I'd be -1 on that one.
- One would be to add something in the cached session entry so that we know we should discard the entry upon loading:
  - Either we can add something to the redis key itself, so for example instead of storing the session with `session.sid`, we'd store it with `f"{session.sid}-{user.hashed_password}"` (`user.hashed_password` can be either the hash that we keep in the DB, or a hash of that hash if we want to avoid putting those hashes on Redis). Note: this is the solution [django](https://github.com/django/django/blob/7119f40c9881666b6f9b5cf7df09ee1d21cc8344/django/contrib/auth/base_user.py#L127-L136) does, using a hmac of the password hash and a known string.
  - Or we could have something in the data itself causing it to be discarded but that would mean our session would no longer be agnostic of the data it contains. As of today, the session code does `msgpack.packb(request.session)` and couldn't care less what's in there, so I'd tend to keep it that way.

So all in all, I think I'm going to go with number 2 above.

**Comment by ewjoachim** [comment]
Ah, @ewdurbin has done it.

🤷 👍

**Comment by ewdurbin** [comment]
Oof, sorry I worked on this after seeing the email that instigated the issue. Sorry for stepping on your toes @ewjoachim

**Comment by di** [comment]
Sorry @ewjoachim, I wasn't aware @ewdurbin was working on it!
