### ISSUE TITLE
The fakeredis project is unmaintained

### ISSUE THREAD

**Issue by di** [pypa/warehouse#11015]
Per https://github.com/jamesls/fakeredis/commit/798d534bd4d6d396ba5082184e478f160f791940, the `fakeredis` project is unmaintained. This is one of our test dependencies:

https://github.com/pypa/warehouse/blob/6968519ad7de18b9adcad0bf8db02ab85075f7c5/requirements/tests.in#L4

And it's lack of support for `redis==4.2.0` (https://github.com/jamesls/fakeredis/pull/328) is blocking #11014.

We should evaluate our usage of `fakeredis` and determine if we need to find a way to keep the project updated or stop using it.

**Comment by miketheman** [comment]
We use `fakeredis` in two places today:

- the newly-added `tests/unit/oidc/test_services.py` test case for the OIDC JWKS work being done
- the older `tests/unit/legacy/api/xmlrpc/test_cache.py` for legacy API caching behaviors

I've thought about this in a few ways, and some tradeoffs:

1. Instead of using `fakeredis`, run a real redis server sidecar and test against that
2. Find a maintainer for (or adopt) `fakeredis` and implement changes to support the upgrade
3. Replace `fakeredis` with an alternative, like `redislite`
4. Replace `fakeredis` calls with `pretend.stub()`, like we do in `tests/unit/test_sessions.py`

Option 1 seems cumbersome for this project, especially for only a few usages, and adds overhead to test setup, but does provide a real redis server. redis is pretty fast, so the test latency overhead is likely negligible.

Option 2 seems like a good idea in general, but from a timeline perspective, might take a while for a maintainer to be identified, onboarded, add the features needed for redis 4.2.0, and then released, only **after** which we'd become unblocked.

Option 3 seems like a reasonable approach, if we want to test against a real redis server without the complexity of setting up a redis sidecar as mentioned in Option 1. There's also a young [`pytest-redislite`](https://pypi.org/project/pytest-redislite/) plugin that could be interesting to explore in the future if it shapes up nicely.

Option 4 would re-establishes a pattern of using `pretend.stub()` for redis calls, set way back in 2015, and prevents testing against actual redis server implementations, and we delegate that responsibility to the `redis-py` library, in expectation that it does the Right Thing in reality. This also removes a test dependency from the overall stack.

After reading a bunch of use cases, I'm leaning towards Option 4. Thoughts?

**Comment by di** [comment]
I agree, option 4 seems like the best option.
