### ISSUE TITLE
Unable to register name "oracledb"

### ISSUE THREAD

**Issue by anthony-tuininga** [pypa/warehouse#11453]
**Describe the bug**
Attempting to upload the source package for oracledb results in this error:

HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'oracledb' isn't allowed. See https://pypi.org/help/#project-name for more information.

**Expected behavior**
The ability to upload the project! The link provided suggests the name may be used -- but it is not. Please advise! Thanks.

**To Reproduce**
Simply attempt to upload the project!

**My Platform**

My platform is Linux using the command `twine upload`.

**Comment by di** [comment]
Hi, this project name has been prohibited due to a prior dependency confusion attack. If you believe you are the correct owner of the project name, please file a support request [here](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME).

**Comment by anthony-tuininga** [comment]
Ok. Thanks. Logged this issue: https://github.com/pypa/pypi-support/issues/1960
