### ISSUE TITLE
Register page layout messed up on EDGE/IE11, Chrome

### ISSUE THREAD

**Issue by KamodaP** [pypa/warehouse#1183]
![register_layout](https://cloud.githubusercontent.com/assets/5961927/15209417/2ac6865c-1831-11e6-98e1-b0e8c0fbf5c6.png)
No layout for this form. Checked on newest versions of EDGE, IE11, and a bit old Chrome

**Comment by dstufft** [comment]
Thanks for the report!

So this is actually just because we haven't gotten to styling this page yet and not because any specific browser is messed up. I've updated #408 to make sure it also includes the register page (since that's all grouped together under user management). I'm going to go ahead and close this now and let this work be tracked in #408.

Thanks again!
