### ISSUE TITLE
After copying "pip install package" the tooltip says "Copied!" for forever

### ISSUE THREAD

**Issue by alex** [pypa/warehouse#1234]
After a few seconds it should switch back to "Copy to clipboard"

**Comment by dstufft** [comment]
Even better would be if we can detect when the ``tooltipped:hover``, ``.tooltipped:active``, and ``.tooltipped:focus`` events stop happening and change it then, so that it only changes once someone has moused off the thing.

I think this would be on the ``blur`` or ``focousout`` event (for ``:active``) and ``mouseout`` or ``mouseleave`` (for ``:hover``), but someone would need to figure out what the right events are. This would mean that click and keeping your mouse there would keep it at ``Copied!``... until you mouse away, then it would turn back to ``Copy to Clipboard``.

An alternative would be to move away from the pure CSS tooltips and instead switch to JS based tooltips, at least for this, which would give us tooltip show/hide events we can subscribe to.

**Comment by karan** [comment]
Yeah that's a snafu I mentioned in the PR - and haven't been able to find a decent solution to (I'm not a JS person - just know enough to be dangerous).

I like the idea of listening to focusout and mouseout events. I'll keep looking and trying other things though (got my last exam on Monday).

**Comment by karan** [comment]
@alex @dstufft This can be closed now.
