### ISSUE TITLE
Mention the Cheeseshop name on the homepage

### ISSUE THREAD

**Issue by brettcannon** [pypa/warehouse#1248]
I don't really expect this to happen, but I would love to make the Cheeseshop name more prevalent. If I had my way, the homepage would have the title be "The Cheeseshop: The Python Package Index" or "The Python Package Index: aka The Cheeseshop". Basically something so that people aren't shocked when someone calls it "the Cheeseshop" (with my dream being people stop calling it "PyPI" and confusing the pronunciation with PyPy).

Note this isn't asking to change the domain from pypi.io, just the messaging/branding on the site. Obviously feel free to outright reject this, but I just had to say something. :smiling_imp:

**Comment by dstufft** [comment]
I'm not a huge fan of the name of PyPI, but I feel like the protest-naming of PyPI Cheeseshop (or anything else) is the worst possible choice. It doesn't eliminate the confusion between PyPI and PyPy (since it's got very little chance of actually becoming the dominate name without an actual rebranding) it just adds a new kind of confusion between "what is the difference between the Cheeseshop and PyPI?".

I obviously can't control what other people do, and I suspect my opinion isn't going to make folks stop calling it the cheeseshop, but that does mean that PyPI itself, unless someone successfully gets it rebranded, isn't going to call itself the cheeseshop or make reference to it except maybe in a clarifying FAQ or some sort of easter-egg like in-joke thing.

**Comment by dstufft** [comment]
Going to close this until such a time PyPI is actually renamed, but I wanted to mention that it did inspire me to add https://github.com/pypa/warehouse/issues/162#issuecomment-224754085 as an easter egg.
