### ISSUE TITLE
Comment out projects statistics tab

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1310]
For launch it is unrealistic that this will be complete.
We should comment out this tab and implement this feature later.

**Comment by controversial** [comment]
Imho commenting out code is bad practice when you have a VCS like git. What are the community's opinions on this? If you just cut it out, it will still be there in the history... so why leave commented-out code? I don't really feel that it's more convenient than looking back in history with Git, it just adds clutter. What's the rationale for commenting?

**Comment by brainwane** [comment]
@controversial I hear what you're saying, but:

1. when the thing being commented out is a small specific piece of functionality (as opposed to, like, a framework being called in a bunch of different places)
2. that we are going to come back to in a few months
3. and not that many people are working on the software, and everyone involved knows the history

I'm fine with commenting it out. And if we delete it instead of commenting it out, I'm in favor of leaving a comment mentioning the gitlog hash of the last commit with the relevant code in it & mentioning any relevant issue number.

[My git journey has not yet gotten to the place where I'm comfortable searching a git history for deleted code/files with `grep` or `log` or `bisect` -- maybe that's next.]

**Comment by controversial** [comment]
Ok. Makes sense 👍 I hope to start contributing in some minor way at some
point soon, maybe later today.

**Comment by brainwane** [comment]
@controversial Thanks! We often hang out in Freenode IRC, in the #pypa-dev channel, although I can't guarantee anyone will be there at any particular moment. And you've probably already seen the [Great for new contributors](https://github.com/pypa/warehouse/labels/Great%20for%20new%20contributors) label...

**Comment by controversial** [comment]
Right. All of those seem to be on the first page 😛 Any reason why the
community isn't on Slack? I'm on an iOS device a lot and I don't really
have an IRC setup going

**Comment by dstufft** [comment]
> Any reason why the community isn't on Slack?

Mostly because it's a community that predates Slack existing :)

**Comment by controversial** [comment]
Ok 🙃 A slack team probably wouldn't be unwise…

**Comment by nlhkabu** [comment]
Note - please use Jinja2 comments rather than HTML comments for this issue.

**Comment by brianfoley81** [comment]
I agree with @controversial on the comments. In most cases, I like to take a "use it or lose it" approach, otherwise you end up with files that are half commented out because someone's afraid of losing something.

I think this is a special case since we're going to be putting this code back in shortly.  And hooray for Slack!
