### ISSUE TITLE
Add roadmap to documentation - link to it from footer

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1322]
I think it would be a good idea to add a roadmap in the documentation to engage the community in our plans.  At a minimum it should:
- explain our milestones and their motivation
- provide a future vision for the app

Additionally, we should:
- Ask for contributions from the community (and link back to the Github project page)
- Ask for donations (and link to donate.pypi.io)

**Comment by brainwane** [comment]
I agree. I like [the Zulip roadmap](https://zulip.readthedocs.io/en/latest/roadmap.html) as an example. It would be a good place to list, in rough priority, the high-priority features we'd like to add once we're in a place to add new features.

**Comment by nlhkabu** [comment]
The Zulip roadmap is an excellent example.

And... now that we have a 'post launch high priority' tag, we should be able to find those features pretty easily :)

As discussed via email, once this roadmap is published, I think we should ask the PSF to write a blog post about it :)

**Comment by dstufft** [comment]
I think we can probably kick this out of the launch milestone, people can sort of get this using the github issues, and I don't think it's worth blocking on launching on having this. Since legacy didn't have it, it seems to be something that can easily be added after the fact.

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2017-12-19-Warehouse) we decided this belongs in [the first milestone, the MVP for package maintainers](https://github.com/pypa/warehouse/milestone/8).

Since an out-of-date roadmap may be worse than none, and since we predict that our updates and people's interest will wax [during the MOSS-funded project period](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html) and wane afterwards, our decision was:

1. Before Maintainer MVP, write and publish and link to a roadmap on Warehouse
2. Then change this issue to "remove roadmap" and put it in the Launch milestone -- we'll move the roadmap to our GitHub repo where people who look for it can more easily see if it's stale

**Comment by nlhkabu** [comment]
Hi @brainwane - a couple of questions on this:

1. who is responsible for publishing the roadmap
2. where will we host it?  Do we create a page on warehouse, or publish it elsewhere (maybe github wiki?)

Thanks

**Comment by di** [comment]
Perhaps this could live on the [Packaging-WG Wiki](https://wiki.python.org/psf/PackagingWG)?

**Comment by brainwane** [comment]
I should be the one responsible for publishing the roadmap, and I think the [Packaging-WG wiki](https://wiki.python.org/psf/PackagingWG) is an excellent place to host it.

**Comment by brainwane** [comment]
https://wiki.python.org/psf/WarehouseRoadmap is now up -- now the next task for me is to link to it from our other documentation in `docs/`, and @nlhkabu, please go ahead and link to it from the footer. Then we can mark this issue closed, I figure. :)

**Comment by brainwane** [comment]
Now that #2834 is merged, I think merging #2835 will allow us to close this (and create a new issue to "remove roadmap" and put it in the Launch milestone -- for that issue, we'll move the roadmap to our GitHub repo where people who look for it can more easily see if it's stale).
