### ISSUE TITLE
Avatars via Gravatar: inform users

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#1389]
A friend of mine who maintains some Python packages took a look at pypi.io and mentioned:

> It was surprising to me to see my Gravatar image used on my profile—the old site doesn't even have landing pages for user profiles, as far as I can tell?
> It might be good to let users opt into having their Gravatar image show up on their profile page, or at least tell the user that Gravatar is the source of the image when they log in and look at their profile page (I had to do a little digging to figure it out).

So I think this is two related tasks:
- [ ] Find some way to inform maintainers that Gravatar is where this image is being sourced from (mouseover/hover text on the image? image caption? a message on the user profile/login page? I'm not sure how to do it)
- [ ] Provide a way for users to opt in or out of this (my preference is for this to be opt-**in** since showing photos of people without asking them first can feel intrusive and can be a factor that increases harassment by jerks)

I'd predict that, if we don't have these set up at launch, at least a dozen people are going to unhappily say "hey I don't want my picture there" or "where's that coming from," so it's worth it to just implement this ahead of launch to save all of us time and frowns. :)

Potentially related to #815.

**Comment by boxed** [comment]
Seems very strange to opt out of a service you've signed up for whose entire purpose is exactly the behavior they got. 

I absolutely agree that it would be nice if it was obvious that the image comes from gravatar. Maybe just a title attribute?

**Comment by ssbarnea** [comment]
The entire purpose of Gravatar was to put an avatar (not necessarily your real face) near a username. I do not see any reason for adding this feature because if someone doesn't want to use a photo they have at least two options: to not use gravatar or to user an alternative email on pypi. Adding a parameter to your real email is enough to hide gravatar (john.doe+pypi@gmail.com will not render the gravatar unless is registered explicitly on gravatar).

For the sake of reaching M1 and avoiding feature-creeping, I would vote to close this as wontfix or to move it to another milestone.

**Comment by brainwane** [comment]
How about just adding some hover text or something on the image so it is a little more discoverable that it comes from Gravatar, to make it more obvious where it's coming from, so people who find it an unpleasant surprise don't waste time hunting around their PyPI settings fruitlessly?

**Comment by dstufft** [comment]
I'm going to kick this out of launch, I don't think it is really needed as a high priority item and can be added later.

**Comment by nlhkabu** [comment]
Closing this as it was implemented in https://github.com/pypa/warehouse/pull/1444
