### ISSUE TITLE
S3FileStorage docs?

### ISSUE THREAD

**Issue by amitsaha** [pypa/warehouse#1449]
I suspect S3 as a storage backend is supported by warehouse? If so, it would be great to have some docs about it. Happy to learn and contribute to the docs.

**Comment by dstufft** [comment]
What sort of documentation are you looking for? Warehouse isn't really designed to be used by anyone besides PyPI itself so it really *only* supports using S3 as a storage backend in a production setting.

**Comment by amitsaha** [comment]
Looking for deployment docs. How to confgiure warehouse to use s3, bucket naming, etc.

**Comment by flypenguin** [comment]
Basically, ALL docs would be super-helpful I just realized. What I also think is a "bad attitude" is that the thing is super-useful for companies to deploy their own internal "pypi" repo, so I really think if that's true it should change, and soon.

Also an "official container" on the docker hub would be helpful, instead of this incredibly "non-standard" way of creating a container by calling "make" (that's actually kind of a joke if you think what problems containers solve :) )

**Comment by dstufft** [comment]
@flypenguin Unfortunately it's a bit more complicated than just documenting. Making this available for others to deploy means needing to pay attention to a lot more things that we really don't have the manpower for. For instance, it's likely at some point we move authentication out of Warehouse and onto a shared ``id.python.org`` end point that acts as a SSO for all of Python's web properties. Internal deployments aren't going to want to use that so we'll have to either support an authentication mechanism that we don't actually use ourselves *OR* we'll need to break all of the people deploying it internally. There are other things of course from needing to care about maintaining backwards compatibility to worrying about how upgrades work (for example, right now it's not unusual for me to have a one off random script I run between migrations to massage data).

All in all, officially supporting running Warehouse outside of our own infrastructure is going to chew up already limited volunteer time. Folks are more likely going to be better served by running something like DevPI or the like rather than this project.

Given all of that, I'm going to go ahead and close this issue.

**Comment by flypenguin** [comment]
hm. that is understandable. one suggestion though - maybe you should put it like this on the main README or so, just to discourage people from using it ;)
