### ISSUE TITLE
How to join to translate this project.

### ISSUE THREAD

**Issue by yufeiminds** [pypa/warehouse#1452]
Is there any documentation of translation guide? include:

* home page
* button / menu
* documentation

Any one had experience? Thanks，: )

**Comment by di** [comment]
Hi @yufeiminds, thanks for your interest! Unfortunately we recently removed an initial attempt at localization in #1335 due to lack of a champion for translation.

Translation is not part of [our "Launch" milestone](https://github.com/pypa/warehouse/milestone/1), but if you have interest and experience I would recommend adding to the discussion on the issue I just created to address localization (#1453).
