### ISSUE TITLE
https://pypi.python.org/pypi/sphinxcontrib-programoutput is a dead link

### ISSUE THREAD

**Issue by mindw** [pypa/warehouse#1489]
https://pypi.org/search/?q=programout Lists it as a valid.
Worked yesterday 2016/10/30.

**Comment by di** [comment]
@mindw It looks like that package is no longer maintained, and unfortunately the maintainer seems to have removed all of it's releases as well. You might want to comment at https://github.com/lunaryorn/sphinxcontrib-programoutput/issues/10 instead.

(The search results on Warehouse are still showing the package due to an issue which should be fixed by #1473.)
