### ISSUE TITLE
Author and Mantainer

### ISSUE THREAD

**Issue by humitos** [pypa/warehouse#1496]
I created/uploaded the pip package of `pysenteishon` from where I'm NOT the author of the code and I noticed that I appear as the author in the old site:

* https://pypi.python.org/pypi/pysenteishon/

Now, at the new warehouse platform, the problem is still there:

* https://pypi.org/project/pysenteishon/#description

If you look at the `setup.py` file of the project, I'm listed there as the maintainer and Emiliano Dalla Verde Marcozzi is the original author.

https://github.com/edvm/pysenteishon/blob/master/setup.py#L25

Thanks!

**Comment by dstufft** [comment]
This is actually a problem with distutils/setuptools (it originates in distutils and then setuptools gets the same broken behavior from there).

You can see in [Lib/distutils/dist.py#L1121-L1122](https://github.com/python/cpython/blob/master/Lib/distutils/dist.py#L1121-L1122) that we have this bit of code:

```python
        file.write('Author: %s\n' % self.get_contact())
        file.write('Author-email: %s\n' % self.get_contact_email())
```

Then if you go and look at the definition of ``get_contact()`` and ``get_contact_email()`` you see:

```python
    def get_contact(self):
        return self.maintainer or self.author or "UNKNOWN"

    def get_contact_email(self):
        return self.maintainer_email or self.author_email or "UNKNOWN"
```

This fix needs to happen in distutils and/or setuptools to actually properly write out and send the author/maintainer field instead of treating the author field like a singular "contact" field and letting maintainer override author.
