### ISSUE TITLE
Run warehouse with private index

### ISSUE THREAD

**Issue by ocervell** [pypa/warehouse#1502]
Would be great to be able to run warehouse with a Private PyPI index for internal-use in companies.

**Comment by dstufft** [comment]
Hi!

I'm not entirely sure what this issue is asking for, however Warehouse does not support being run anywhere other than on it's official infrastructure and in a development environment. This is done entirely to allow the limited volunteer time we have to be better focused on providing the best PyPI we can, instead of also needing to worry about how changes will affect other deployments.
