### ISSUE TITLE
Standardize linking to the latest version

### ISSUE THREAD

**Issue by brettcannon** [pypa/warehouse#1505]
If you search then the link you are provided with is e.g. https://pypi.org/project/azure/ . But if you're viewing an outdated project version then the "latest version" box points to the URL for the exact release that's currently the newest, e.g. https://pypi.org/project/azure/2.0.0rc6/ . So is the "latest version" URL the overall project one and it defaults to that, or is it the exact release URL? Perhaps there was the thought that if you're viewing a specific version you actually want the specific version that happens to be the latest?

**Comment by dstufft** [comment]
If I recall, the main reason I did this was because the "latest version" widget doesn't just say "hey there is a newer version", it says "Hey there is a newer version, and it is X". My concern was if something is cached then the real latest version might be something different and so it'll take you to a different version.

That being said, we purge these pages whenever a new release is made, so it *shouldn't* be a big deal.

The only other use case I can think of is that someone might copy/paste the URL expecting it to take them to the specific version that was mentioned in the latest version widget and if that changes then their thing might link to the wrong place now.
