### ISSUE TITLE
Package update feeds

### ISSUE THREAD

**Issue by jakirkham** [pypa/warehouse#1683]
Was just having a thought about a neat feature that would be really helpful for me and probably others. Thinking of downstream/secondary package maintainers for instance though others may find it valuable too. My primary personal use case is helping keep [conda-forge]( http://conda-forge.github.io/ ) up to date. Though maybe Linux packagers and others would be interested

It would be really neat to have some kind of feed that would be published to when a particular package is updated. Mainly interested in version bumps, but potentially other events could be valuable if people are interested. It would be good if this feed was designed so that a person or bot could subscribe ideally without an account. Also it might be nice to have some way to filter out dev/prereleases from stable releases.

**Comment by FRidh** [comment]
This is definitely one of those features I would expect from a package index. Right now I keep track of updates by subscribing to the `releases` feeds of the repo's of the projects I'm interested in.

**Comment by jakirkham** [comment]
That's certainly another option. Though not everyone is great about keeping their releases (or tags) in sync with PyPI releases. That said, I expect we will use a variety of different sources.

**Comment by edmorley** [comment]
Another use-case for this: being able to track when new files are uploaded to an existing package version (eg additional wheel variants being uploaded) - so tools like pyup.io can know to update the requirements files with the additional hashes.

**Comment by brainwane** [comment]
I figure this would be based on the same mechanism that could send out notification emails, as requested in #98.

**Comment by brainwane** [comment]
Thanks for your note and sorry for the slow response!

The folks working on Warehouse have gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable. Since this feature isn't something that the legacy site has, I've moved it to a future milestone.

Thanks and sorry again for the wait.

**Comment by brainwane** [comment]
Folks who need this might want to check whether the Libraries.io API for https://libraries.io/pypi might suit their needs in the short term.

**Comment by di** [comment]
Here's a request for RSS feeds specifically: https://github.com/pypa/warehouse/issues/5612

**Comment by brainwane** [comment]
Thanks @scop and @yeraydiazdiaz and @di for resolving this issue!

[Feed details](https://warehouse.pypa.io/api-reference/feeds/#project-releases-feed), [FAQ item](https://pypi.org/help/#project-release-notifications).

**Comment by jakirkham** [comment]
Awesome! Thank you 😄

**Comment by jezdez** [comment]
Yay!
