### ISSUE TITLE
"pypi stat" does not report numbers for releases after Dec'16

### ISSUE THREAD

**Issue by rvprasad** [pypa/warehouse#1783]
pypi stat pytest reports 0 downloads for the last release on 17/01/22. pypi stat pytest-finer-verdicts reports 0 downloads for the last release on 17/02/25. pypi stat thinc reports 0 downloads for last seven releases dating back to 17/01/09.

This data does not seem to be correct as I have installed the latest version of all of the above modules via pip in the last month.

I have reported the same issue against pypi-legacy: pypa/pypi-legacy#610.  I am reporting it here as I am not sure if pypi-legacy issues are being actively tracked.

**Comment by dstufft** [comment]
Hi!

So this is a bit crappy. Basically the tool chain that fixes this has been on and off again broken for over a year now. In the meantime we've gotten a much better system in place that allows far more fine grained access to the download statistics. Because of that, I am inclined to simply deprecate and remove these numbers and direct everyone to use the new system.

You can read more about this [here](https://mail.python.org/pipermail/distutils-sig/2017-March/030218.html).
