### ISSUE TITLE
Is the legacy JSON API lagging?

### ISSUE THREAD

**Issue by jayfk** [pypa/warehouse#1962]
I'd love to switch to the *new* legacy JSON API on `pypi.org/pypi/{name}/json` instead of using the *old* one at `pypi.python.org/pypi/{name}/json`.

However, the new API seems to be lagging:

```
>>> import requests
>>> requests.get('https://pypi.org/pypi/pytest-metadata/json').json()['info']['version']
'1.3.0'
>>> requests.get('https://pypi.python.org/pypi/pytest-metadata/json').json()['info']['version']
'1.4.0'
```

The release API seems to work, though:

```
>>> requests.get('https://pypi.org/pypi/pytest-metadata/1.4.0/json').status_code
200
```

Is this a caching issue?

**Comment by dstufft** [comment]
Yea it's strictly a caching thing, and it's because if someone uploads to Warehouse both Warehouse and Legacy get purged, but if someone uploads to legacy only legacy gets purged :/

**Comment by jayfk** [comment]
Damn. Is there a way for me to fix this on this codebase?

**Comment by dstufft** [comment]
Um, well the way we solved it in the other direction (allowing warehouse to purge legacy) was to make an endpoint on legacy that does the purge routine if given a package name. So if you wanted you could make a temporary API in Warehouse that accepts a package name and then triggers the purges. Then you'd need to incorporate that into legacy PyPI so that on upload and such it hits that warehouse API so warehouse knows to purge stuff.

Otherwise mostly it's just waiting until we shut down the upload on legacy.

I'm going to close this not because it's not a real issue, but because I don't think we're going to get around to doing this. If you decide you want to make PRs I'm happy to review them though.
