### ISSUE TITLE
Show password input (checkbox)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1984]
from https://www.nngroup.com/articles/password-creation/

![screenshot from 2017-05-13 11-07-02](https://cloud.githubusercontent.com/assets/3323703/26024594/5a2cf9f6-37cc-11e7-810d-bf2f0a4868a0.png)

It would be great if we can add a checkbox that shows/hides the passwords on our register and login forms.

**Comment by dstufft** [comment]
This seems like a good idea to me as long as we default to having the password masked.

**Comment by bstutes** [comment]
As noted above I have pushed a branch to my warehouse repo that addresses allowing the user to reveal the password they have entered.  However, since I use a pure Linux laptop I do not have access to a browser to verify the code works for IE 9+.  Therefore, I hesitate creating a pull request.  If someone could pull my code down and verify it works with IE as well as chrome, etc. that would be great.  Any thoughts?

**Comment by nlhkabu** [comment]
hi @bstutes -feel free to create a PR, after that I will pull it down and test it with browserstack :)

**Comment by bstutes** [comment]
Will do.  As an update, I have since been able to test the changes on Google Chrome (Linux/Windows), Firefox-53, IE 11, and MS Edge browsers.  I'm sure your browserstack will allow more thorough testing.

A quick question, MS Edge, at least on the copy I tried, includes an icon in the password element that allows unmasking the password in *that* individual instance.  Since the registration page has two password input elements, each instance has this same icon.  While the convenience of clicking a single checkbox to unmask both password elements may be nice, I wonder if including the checkbox on Edge browsers might not be confusing to the user.  Your thoughts?
