### ISSUE TITLE
merkle tree log for every change.

### ISSUE THREAD

**Issue by graingert** [pypa/warehouse#2061]
host a secure merkle tree log and root, so that uses can pin dependencies with a single merkle root.

Each time a file is uploaded to warehouse insert the filename hash and timestamp into the merkle log. When a client (pip) first selects a set of packages they can store the global merkle root and timestamp as published on warehouse.

When a client (pip) is used to reconstruct a set of packages and their dependencies, the client can present the merkle root and timestamp and can work together with warehouse to securely recreate exactly the bytes that would have been downloaded when the first selection was made.

This would obviate the need for --generate-hashes --require-hashes and pip lock files, because a single value can be used to securely reconstruct a package set from version ranges.

**Comment by dstufft** [comment]
I don't think we're likely going to do this directly, however when we implement TUF I believe that this will be doable with that system. However if it's not, it's doubtful that we would implement this on it's own.

Largely because I don't believe that it's going to be generally useful to too many people and it's another API/invariant that needs to be maintained.

Thanks though!

**Comment by graingert** [comment]
TUF?

**Comment by dstufft** [comment]
https://theupdateframework.github.io/

**Comment by graingert** [comment]
@dstufft Mercury sounds similar
