### ISSUE TITLE
Classifiers in development DB are out of date

### ISSUE THREAD

**Issue by asottile** [pypa/warehouse#2216]
Perhaps I'm doing something incorrectly, while trying to populate some data to test a change I'm hitting this:

```
$ twine upload -r pypi-localhost *.tar.gz --skip-exist
Uploading distributions to http://localhost/legacy/
Enter your password: 
Uploading pre_commit-0.10.0.tar.gz
Uploading pre_commit-0.13.3.tar.gz                                              
HTTPError: 400 Client Error: classifiers: 'Programming Language :: Python :: 3.6' is not a valid choice for this field for url: http://localhost/legacy/
```

I manually applied a hacky patch to work around this:

```diff
diff --git a/warehouse/forklift/legacy.py b/warehouse/forklift/legacy.py
index f149b48..fae8853 100644
--- a/warehouse/forklift/legacy.py
+++ b/warehouse/forklift/legacy.py
@@ -599,7 +599,7 @@ def file_upload(request):
     form = MetadataForm(request.POST)
     form.classifiers.choices = [
         (c.classifier, c.classifier) for c in all_classifiers
-    ]
+    ] + [('Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.6')]
     if not form.validate():
         for field_name in _error_message_order:
             if field_name in form.errors:
```

**Comment by dstufft** [comment]
I don't remember specifically, but it seems likely that our database dump was taken prior to that classifier getting added.

**Comment by cprogrammer1994** [comment]
It means that `'Programming Language :: Python :: 3.7'` is missing as well.

**Comment by pkopac** [comment]
@dstufft: I've just tried uploading a new minor version of [our library package](https://pypi.org/project/chartmogul/) and had to remove all classifiers.
1. I had to [switch to the new URL](https://packaging.python.org/guides/migrating-to-pypi-org/#uploading) because the old one is HTTP 410 now.
2. The new default URL refuses normal classifiers AND there's no list/documentation/tutorial to be found.
At least these are now refused:
* 'Development Status :: 5 - Production/Stable',
* 'Intended Audience :: Developers',
* 'Natural Language :: English',

**Comment by di** [comment]
Hi @pkopac, the issue with [the `classifiers` kwarg in your project's `setup.py`](https://github.com/chartmogul/chartmogul-python/commit/c546ae88bd53358346f9770325a47462203fba89) is that they were in a tuple instead of a list. 

This is a known bug with Warehouse, see https://github.com/pypa/warehouse/issues/2185.

**Comment by di** [comment]
@dstufft I assigned this to you because AFAIK you're the only one that can create and "sanitize" our development DB dump, but I'd be happy gain some knowledge here if you wanted to walk me through how you've done this in the past.

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2017-12-19-Warehouse) we decided that this is a mild annoyance for users and not urgent to fix for a near-term milestone, and that the issue needs revisiting and updating.

**Comment by di** [comment]
It would also be nice if we fixed the "anonymized" email addresses when we do this as well. Right now they are something like ` 5b5a009e806b736ebf9269f6b32b419dexample.com` which is not a valid email address (missing the `@`).

**Comment by di** [comment]
In #2713 Ernest said:

> perhaps a dedicated `admin` user for test rather than having to use an existing PyPI admin's username.
