### ISSUE TITLE
Validate version strings

### ISSUE THREAD

**Issue by bennuttall** [pypa/warehouse#2275]
While working on [piwheels](https://github.com/bennuttall/piwheels), we came across a package release with the following version "number":

```
Sysv_ipc gives Python programs access to System V semaphores, shared memory and message queues. Most (all?) Unixes (including OS X) support System V IPC. Windows+Cygwin 1.7 might also work. Sample code is included. This extension is released under the GPL. You might also be interested in the similar POSIX IPC module at: http://semanchuk.com/philip/posix_ipc/
```

See the [JSON](https://pypi.python.org/pypi/sysv_ipc/) for the [sysv_ipc package on PyPI](https://pypi.python.org/pypi/sysv_ipc/).

It seems this package version spec was permitted by PyPI but isn't valid, i.e. you can't run `pip install sysv_ipc==version` with this as the version.

Would it be possible for warehouse to validate version strings to prevent this?

**Comment by bennuttall** [comment]
That was the longest package version we found. The next longest were commit hashes and odd things like `1.0dev-BZR-r101-panta-elasticworld.org-20091118083244-inh0tj0d73fcdz14`.

**Comment by dstufft** [comment]
So we do validate version numbers and have for like 1 or 2 years now. The problem is basically that for a decade PyPI didn't validate versions and when we enabled validation we had to decide between deleting existing packages that were invalid or just grandfathering them in. It's just assumed that downstream consumers will be able to handle these versions in some way, but leaving the strategy for *how* to handle them up to the individual downstream consumer (E.g. one option could be to completely ignore them).

You can see this code at [warehouse/forklift/legacy.py#L293-L302](https://github.com/pypa/warehouse/blob/c75190ed82f5a8c2e95ec914107d1ae7c47f709f/warehouse/forklift/legacy.py#L293-L302).
