### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by Safihre** [pypa/warehouse#2417]
Forgive me if I missed the appropriate place to report feedback on the new UI, can I do it here?

I enjoy the new style but would have some feedback, specifically on the project-pages.
While it is very nice that they now scale to any device, the main device will still be a desktop computer since this is where you run `pip`. So with that in mind, here's some things I wanted to note:

1. On a regular 1080p screen, the header is currently very large and covers more than half of the screen before getting to the actual description of the project. I understand that this is partly due to the preproduction-warning and the donate bar. So overall I would suggest to have a close (X) option for the preproduction-warning (via `localStorage`?) and reduce the overall height of the header by reducing padding and potentially different placement of the donate bar.
2. I like the `pip install xx` in the header, but because of the background color it doesn't really stand out and is easy to miss. I would suggest a more contrasting color? 
3. The tag-line does not really stand out, where in current pypi it's the first thing you read under a project title. I would suggest to either give the text more contrast, or move it to the central part of the screen? So in the right column, in the same style as 'Navigation' for example.
4. Overall on desktops the padding on buttons and other things in the left bar can be reduced a bit I think, there is a lot of spacing especially in the left project-bar which makes it very long, particularly on smaller projects (like [mine](https://pypi.org/project/sabyenc/)).
5. Small one: on [my project](https://pypi.org/project/sabyenc/) it now randomly says 'About 5 hours ago', I think it needs a 'Last modified' text.
6. I assume it's still coming, but when I am logged in I don't see any extra buttons on my project pages. I would expect for example to see an Edit files option?

I know CSS/HTML/JS so I could submit PR's for this, but I didn't want to be an unwelcome guest! 👻

**Comment by dstufft** [comment]
Assigning this to @nlhkabu since she is in charge of the design :)

**Comment by anowlcalledjosh** [comment]
#1988 ("Create 'condensed' design version") is relevant to this.

**Comment by user-e** [comment]
The current older version has a mainly grey and white colour scheme, a different layout and less whitespace. Some things that can be improved with the layout/design of the newer version:
- The new header is too big and the black and blue colours used [don't fit with the styles used on _python.org_](https://github.com/pypa/warehouse/issues/2562). Also, these colours are too bright/contrasting and there's now too much whitespace.
- The tagline can go above the status tags (version, build, downloads...) in the main column, as bold/more weighted text.
- The sidebar can be structured better like the old navigation links, with fewer sections:
  - Start with all the site links, then have a clear gap (a few lines of blank space), followed by
all metadata of the package in one section without big separating lines (project links including home page, author with a few contact details, license, keywords/tags, maintainers/owners list (icons to profiles), status information/categories (now called classifiers), other things.

**Comment by Safihre** [comment]
Is it me, or has this project stalled? There are so few commits that are not `pyup-bot`.
I would enjoy making the suggested changes and submitting a PR, but it seems it might be weeks before anyone would look at it or for it to get merged. 
What is the timeline for warehouse to take over? 
@dstufft @anowlcalledjosh @nlhkabu

**Comment by user-e** [comment]
I don't know much (only just found out about this pre-production next generation PyPi version) but the Github project has 146 issues and 22 pull requests. Maybe progress is slow and they have many bugs and suggestions to check.

**Comment by dstufft** [comment]
It has not stalled, there has just been more behind the scenes work going on currently.

**Comment by brainwane** [comment]
@Safihre Thanks for your note and sorry for the slow response!

The folks working on Warehouse have just gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and will in December kick off work towards [the first milestone: redirecting pypi.python.org to pypi.org](https://github.com/pypa/warehouse/milestone/1). We (especially @nlhkabu) will have more responses to your and @user-e's feedback after that kickoff.

Thanks again.

**Comment by Safihre** [comment]
@brainwane Awesome!
Still my initial question remains: are PR's from regular folk like us appreciated? Or rather keep bigger changes within the team?

**Comment by brainwane** [comment]
@Safihre Thanks for the suggestion and the discussion!

I'm sorry for the delay in response here. The folks working on Warehouse have gotten [limited funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable. Along the way we've been trying to reply to issues that need replies -- I missed getting to this earlier and I'm sorry about that.

Nicole (@nlhkabu) has written up her design goals, including her assessment of the legacy UI and its problems, at http://whoisnicoleharris.com/2015/12/31/designing-warehouse-an-overview.html . She's doing some user tests to get more data on what users have trouble with, and during those tests, asking about design inconsistency between www.python.org, and usual device/browser/display usage and usual size/resolution.

We absolutely welcome pull requests from everybody, but for larger design changes it would probably be best to talk about them first in issues or on the mailing list, as we've done here, rather than start with PRs. (Design discussion can get tetchy when people talk past each other, so even though everyone's been friendly so far, I figured I'd link to the [CoC](https://www.pypa.io/en/latest/code-of-conduct/) and some [general design feedback tips from Wikimedia](https://www.mediawiki.org/wiki/Wikimedia_Foundation_Design/How_to_give_design_feedback).)

Now that the team is well underway, we'll be faster at responding to new issues and comments -- sorry again for the wait.

**Comment by brainwane** [comment]
@Safihre I'm sorry - you're getting a response from me at the moment but I've been in frequent consultation with Nicole. She's taking your concerns into account, gathering data via [user tests](http://whoisnicoleharris.com/2018/03/13/user-testing-warehouse.html), and then using that data to figure out how to proceed and what to prioritize.

I think part of the issue with this particular thread (#2417) is that we were trying to talk about a lot of things at once. :) Some of your concerns we have already addressed, or we're addressing in other issues:

* The condensed view, including header size, tagline placement, and padding, I believe we are working on in #1988, where I just commented.

* The pre-production warning (which will become a "beta" warning first) will indeed go away (#2518). In any case, we're going to make some notification bars/banners dismissable (#3126).

* There are indeed now options for you to manage files and settings for your projects when you're logged in.

Dividing up your individual remaining suggestions into different issues would be useful, so I'm going to do that:

* #3334
* #3335 

Let's make a fresh start. I'm going to close this issue now, but please open new issues for particular concerns you have about Warehouse design & functionality! We do welcome your feedback and I'm sorry for the bumps along the way here.
