### ISSUE TITLE
Verify ownership of GPG key

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#25]
Currently there's no verification that a person owns the GPG key they claim they do. We should verify this before allowing this key.

**Comment by brainwane** [comment]
This would be a new feature that legacy PyPI does not support and I'm in favor of it in Warehouse. :)

**Comment by ewdurbin** [comment]
@dstufft this is a little bit of an old issue :)

Since it's filing many issues have come and gone regarding GPG, and I am going to close this.

PEP [503](https://github.com/python/peps/blob/cf3bad5ab34381fd5c57787c9716be22f7805414/pep-0503.txt#L89-L97) specifies PyPI's handling of **signatures** _supplied_ when packages are uploaded:

PEP [101](https://github.com/python/peps/blob/3371af975f87ef36e3f17b77cd34863a9da90549/pep-0101.txt) gives overall guidance of signing commits and releases, but does not specify PyPI's behavior:

PEPs [241](https://github.com/python/peps/blob/cf3bad5ab34381fd5c57787c9716be22f7805414/pep-0241.txt#L171-L172) and [314](https://github.com/python/peps/blob/cf3bad5ab34381fd5c57787c9716be22f7805414/pep-0314.txt#L187-L188) both specify the same non-binding requirement that a repository _might_ provide authors the ability to store their GPG Key... which is wholly distinct from a Key ID... but I think I know what they meant.

Given the [context and reasoning](https://github.com/pypa/twine/issues/157#issuecomment-170512719) given in other venues, and the ultimate fact that _just_ asking PyPI for a users GPG Key ID rather than the Keyserver infrastructure that exists solely for this purpose, I'm closing this and removing GPG Key ID handling from pypa/pypi-legacy.
