### ISSUE TITLE
"499 Client Error: Client Disconnected for url: https://upload.pypi.org/legacy/"

### ISSUE THREAD

**Issue by s-m-e** [pypa/warehouse#2533]
Original / initial bug reports & discussions:
* In [twine](https://github.com/pypa/twine/issues/263) (unanswered since 2017-07-25)
* In [pypi-legacy](https://github.com/pypa/pypi-legacy/issues/675) (10+ replies, closed by @ewdurbin on 2017-10-24, requesting further discussion here)

----

**Synopsis**: Uploading new as well as updating existing python packages on PyPI fails with "499 Client Error" from certain networks. Only _production PyPI_ is affected - _pypitest_ on the other hand always accepts uploads. Uploads via both, twine and setuptools, are equally affected. Multiple versions of CPython on multiple operating systems show the same behavior. Altering username or password (to another working account or just complete bogus) has no effect.

**Workaround**: Re-routing the traffic through another network (proxy) helps. The following example illustrates how to do this with ssh:
```
# first shell
ssh -D 8080 some_ssh_server_in_another_network
# second shell
pip install -vU requests[socks]
export http_proxy=socks5://127.0.0.1:8080 https_proxy=socks5://127.0.0.1:8080
twine upload $filename $filename.asc
```
Hosting & cloud providers such as AWS are known to work as proxies (if you have a server there, which you can access via ssh).

**Comment by brainwane** [comment]
@s-m-e thank you for reporting this issue, and sorry for the slow response!

The folks working on Warehouse have gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable -- and along the way, we're working through older bug reports as well.

This is a confusing experience and it's unclear where the problem originates; I'm sorry for the frustration. We discussed your issue in [our meeting today](https://wiki.python.org/psf/PackagingWG/2018-02-20-Warehouse) and speculated about potential causes. This might be an issue with Heroku's HTTP routing, and we are going to move our upload infrastructure soon and so this problem may go away when we do that.

We would appreciate more details, to help us trace this. Since the problem might be that metadata failed validation, if you can share an example distribution that has this problem, that would be really helpful to help us track this down.

Thanks and sorry again for the wait.

**Comment by caseyjlaw** [comment]
Perhaps I'm misunderstanding, but are all uploads to pypi broken? Mine certainly are.
Is there a simpler workaround for this issue than the one given at top?

**Comment by ewdurbin** [comment]
@caseyjlaw sorry you're having trouble. I assume since you're here you are getting the same error message as the original report.

Uploads are certainly working for others, based on activity recent activity on the index.

Can you provide any additional details about your upload? This would include the environment, the size of your upload, and what tool you're using to upload at a minimum.

**Comment by ewdurbin** [comment]
The best guess I can come up with in the blind here is that it may be anti-abuse measures that our _hosting_ itself has in place. @caseyjlaw can you provide (privately if necessary by emailing ernest@python.org) the IP address your upload would be coming from?

**Comment by di** [comment]
@caseyjlaw Would you also be able to provide us with a copy of the distribution you are trying to upload? (Or a recent commit at https://github.com/caseyjlaw/realfast that we could test from would work too)

**Comment by ewdurbin** [comment]
It seems this might be related to this block of code:

https://github.com/pypa/warehouse/blob/889a2b216daf5015fdd1964d61ea0220c677d7f1/warehouse/forklift/legacy.py#L1022-L1026

is returning an empty `Response()` the right move there?

**Comment by ewdurbin** [comment]
Or similarly, twine is swallowing some other validation error?

**Comment by ewdurbin** [comment]
@caseyjlaw what happens if you `twine upload` each file individually?

**Comment by di** [comment]
> Or similarly, twine is swallowing some other validation error?
I'm thinking this may be more likely, but I suppo

**Comment by di** [comment]
Oops, sorry for the close.

**Comment by dstufft** [comment]
> is returning an empty ``Response()`` the right move there?

Yes. It's doing the exact same thing that would happen if the file successfully uploaded, just without any additional processing because we've determined that the file being uploaded (A) Already exists and (B) matches the file being uploaded exactly.

**Comment by dstufft** [comment]
For reference: https://github.com/pypa/warehouse/blob/889a2b216daf5015fdd1964d61ea0220c677d7f1/warehouse/forklift/legacy.py#L1182

**Comment by s-m-e** [comment]
@brainwane @di I can reliably trigger this issue from [my current ISP](https://en.wikipedia.org/wiki/Deutsche_Telekom) with [my Python package](https://github.com/pleiszenburg/zugbruecke/). I have not made any changes since, in case you want to look at potential meta-data issues. I last "confirmed" the upload issue it in mid-December, when I attempted to release another version of my package. I ended up routing the upload through AWS as usual (successfully) after receiving a 499 error on the "direct path". How can I assist any further in bisecting the issue?

**Comment by caseyjlaw** [comment]
Update on my end, I tried this again from a different IP (my home instead of work) and it uploads successfully.
Aside from a different IP, I do not have an `.pypic` file, so I authenticate via a prompt.

I can build and upload with `python setup.py install sdist bdist_wheel upload`. For another package (I had a few to upload), I used twine successfully with the `twine upload dist/*` command.

**Comment by caseyjlaw** [comment]
@di For a recent commit that failed, see https://github.com/realfastvla/sdmpy/commit/a6f783e2bd73443466ba965313eaafa40c51be87.

**Comment by caseyjlaw** [comment]
Just realized that there is other difference between my two environments. My failing OS is redhat enterprise linux while my home os is OSX.

**Comment by ewdurbin** [comment]
Currently our hosting doesn't allow us any way to scute what's going on here from our side.

I'm unable to reproduce from any remote networks I've tried :/

My theory remains that our hosting is dropping the connection before it reaches our app.

At this point we're approaching where we begin to ask for traceroutes, tcpdumps, and all kinds of other horrible stuff that I _think_ we can just avoid altogether since we'll be moving the upload endpoint in the coming weeks to new hosting which we _do_ have introspection on the edge/routing layer.

If you're able to provide any network level debug information from your vantage point @caseyjlaw or @s-m-e it might at least be enlightening at this point.

**Comment by brainwane** [comment]
@s-m-e @caseyjlaw Are you still experiencing this problem?

**Comment by s-m-e** [comment]
@brainwane On my last attempt on 2018-04-10, it worked (without a proxy). Well, it's just one data point - it could be a coincidence.

**Comment by caseyjlaw** [comment]
@brainwane I try to reproduce the error in two locations, but could not. It seems to have been resolved for me.
Congrats on the big upgrade!

**Comment by brainwane** [comment]
Thank you! I think we can say this is resolved. :)
