### ISSUE TITLE
Description not rendering properly

### ISSUE THREAD

**Issue by clenk** [pypa/warehouse#2581]
I have a project with a README.rst that renders properly at https://pypi.python.org/pypi/stix2 but not at https://pypi.org/project/stix2/ - the RST doesn't seem to be parsed. If I import `readme_renderer` and call `render()` on the .rst content, the output contains all the HTML tags I expected it to. Any idea why it's not rendering properly with warehouse?

Link to the readme file: https://github.com/oasis-open/cti-python-stix2/blob/master/README.rst

cc: @gtback

**Comment by di** [comment]
Hi @clenk, thanks for reporting this. The issue seems to be that your README was broken in a previous release, and the cache for this page did not get purged when the release is made.

I ran `curl -XPURGE https://pypi.org/project/stix2/` and https://pypi.org/project/stix2/ now renders correctly.

I also created https://github.com/pypa/warehouse/issues/2582 to capture the underlying issue.
