### ISSUE TITLE
Mobile version of project page cuts off description text (probably right padding/margin)

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#2838]
![screenshot_2018-01-25-08-15-26_com android chrome](https://user-images.githubusercontent.com/578543/35376044-b5629dec-01a9-11e8-98ad-a984e6f6ef40.png)

**Comment by nlhkabu** [comment]
hi @webknjaz thanks for reporting this.  Could you tell me what browser/mobile this was on?

I believe this has been fixed with the optimisation of the mobile UI - It should now look like this:

![fireshot capture 11 - pem warehouse pypi - https___pypi org_project_pem_](https://user-images.githubusercontent.com/3323703/35649334-ace5dfae-06d0-11e8-958a-73e73b252b6b.png)

Can you please confirm that you are no longer seeing this issue?  Thank you :)

**Comment by webknjaz** [comment]
Thanks, I confirm that it's fixed now.
FTR it was Chrome for Android.
