### ISSUE TITLE
there should be an option to completely destroy project on pypi.org

### ISSUE THREAD

**Issue by tbhaxor** [pypa/warehouse#2840]
I am facing a problem while uploading the same file name on pypi warehouse.

ps: i have already destroyed my project on pypi.python.org

```
HTTPError: 400 Client Error: This filename has previously been used, you should use a different version. for url: https://upload.pypi.org/legacy/
```

**Comment by di** [comment]
@tbhaxor The ability to delete a project via Warehouse is an upcoming feature (#2805). As you have noted, this is currently possible via pypi.python.org, and anything deleted there will also be deleted in Warehouse.

The issue you're having is not because the file remains on Warehouse, it's because it's not possible to upload the same filename twice regardless, even if you have deleted the project or it's releases. This is done to ensure that a file that has been uploaded and distributed to users cannot be deleted and re-uploaded under the same name with differing or possibly malicious behavior.

You will need to change the filename (by bumping the version for your project) and make a new release instead.

**Comment by tbhaxor** [comment]
@di 
![image](https://user-images.githubusercontent.com/28386721/35411180-ce8b171a-023d-11e8-8390-e3e801dc3972.png)

Delete option is not visible

I hope i will be fixed / added soon

**Comment by di** [comment]
@tbhaxor Like I said, this feature is not yet implemented in Warehouse, but it is on the way.

In the meantime, if you want to delete that release, you'll need to do it on pypi.python.org at https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=pbars

**Comment by pradyunsg** [comment]
> it's not possible to upload the same filename twice regardless, even if you have deleted the project or it's releases. This is done to ensure that a file that has been uploaded and distributed to users cannot be deleted and re-uploaded under the same name with differing or possibly malicious behavior.

@tbhaxor I request you to read the above.

---

@di Maybe the error message could use some improvement and possibly link to a question in the Warehouse FAQ that elaborates upon it and tells a person what they can do instead when they encounter this error?
