### ISSUE TITLE
[Bug] Can't find package on test.pypi.org

### ISSUE THREAD

**Issue by Kristinita** [pypa/warehouse#2899]
### 1. Summary

I can't find my package `erichek`, if I use search form for **<https://test.pypi.org>** site. If I use search form for **<https://testpypi.python.org>**, I successful find my package.

### 2. Steps to reproduce

Yesterday I print in local folder of my package `erichek`:

    python setup.py bdist_wheel && twine upload --repository-url https://test.pypi.org/legacy/ dist/*

[**Erichek upload**](https://test.pypi.org/project/erichek/) to TestPyPI.

Also, I remove my `canelocanelo` package from TestPyPI, use **<https://test.pypi.org>** interface.

I search erichek for **<https://testpypi.python.org>** and **<https://test.pypi.org>** search forms.

### 3. Expected behavior

[**Result**](https://testpypi.python.org/pypi/erichek/0.2.0) for **<https://testpypi.python.org>**:

![Erichek on testpypi.python.org](https://i.imgur.com/c7Aoafw.png)

Good.

### 4. test.pypi.org behavior

[**Result**](https://test.pypi.org/search/?q=erichek):

![Erichek on test.pypi.org](https://i.imgur.com/22wThkQ.png)

[**Existing package `erichek`**](https://test.pypi.org/project/erichek/) site doesn't show, but show deleted package `canelocanelo`.

### 5. Environment

For me locally:

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.4,
+ Pip 9.0.1,
+ Twine 1.9.1,
+ Wheel 0.30.0.

Thanks.

**Comment by di** [comment]
@Kristinita The search indexes are not immediately updated, it may take ~24 hours for a new package or deleted package to appear in a search. [Your search query now returns the `erichek` package and not the `canelocanelo` package](https://test.pypi.org/search/?q=erichek).

Since we already have #701 to add more incremental indexing, I'm going to close this, but thanks for taking the time to make a really detailed report!
