### ISSUE TITLE
Expose requires_python for each release in JSON API

### ISSUE THREAD

**Issue by astrofrog** [pypa/warehouse#3024]
The following JSON:

https://pypi.python.org/pypi/astropy/json

or:

https://pypi.io/pypi/astropy/json

includes the following for the latest release:

```
        "requires_python": ">=3.5", 
```

but it would be really helpful to have this for all releases listed in the ``releases`` section, to avoid having to hit the server for each release to find out the ``requires_python``.

**Comment by brainwane** [comment]
Thanks for your suggestion, and sorry for the slow response! I like this idea and am grateful to you for bringing it up.

The folks working on Warehouse have gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and are concentrating on work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable. Since (as far as I can gather) this feature isn't something that the legacy site has, I've moved it to a future milestone.

Thanks and sorry again for the wait.

**Comment by ncoghlan** [comment]
Just noting that the current bulk API for accessing the `Requires-Python` metadata is PEP 503's `data-requires-python` link attribute: https://www.python.org/dev/peps/pep-0503/#specification

For AstroPy specifically, that appears at https://pypi.org/simple/astropy/ and https://pypi.python.org/simple/astropy/

Having a project level JSON listing *would* still be a nice improvement, but in the meantime, querying the link attributes in the PEP 503 API is preferred to querying each release individually.
