### ISSUE TITLE
Display help text on browse page and null search page

### ISSUE THREAD

**Issue by hnykda** [pypa/warehouse#3062]
Hi,

I think that it would make much better impression if the packages were sorted by e.g. download count/popularity/update rather alphabetically by default.

When you click on [Browse project](https://pypi.org/search/) and it takes you to the search page, it looks like this:
![image](https://user-images.githubusercontent.com/2741256/36661034-69c3261e-1ada-11e8-8900-6ff9d03e7ab6.png)

That's not really a very flattering choice of packages for Python, and more importantly, it's very probably not what a user wants to see. Clearly, what the user wants to see most likely is something more correlated with usage/download/popularity/visited rather than alphabet.

**Comment by di** [comment]
This is sort of just a side-effect of a sort "by relevance" of an empty query -- since there's no way to determine the relevance to the query without a query, by default we just get an alphabetical list.

Doing anything with download counts here is currently blocked on #699 (we don't actually have the download counts "in" Warehouse right now). It's also not really as good of a metric for "interestingness" as you might expect.

We don't currently have a metric for "popularity" and since PyPI attempts to be a "neutral" catalog, we aren't likely to add one in the near future (see #991).

However, I would agree that this is not a great page to dump the user to when they click the "Browse" link. I think we could do one of two things here in the short-term:

1) If the query is empty (no search string or classifiers selected), we default to some helpful guidance message instead of showing the result list, something like: "To begin your search, enter a search query or select a filter from the list on the left"
2) Remove the "browse projects" link;

I think 1) is probably the right way to go, but will need some wordsmithing from @nlhkabu @brainwane  et al.

**Comment by ewdurbin** [comment]
+1 to Empty Query => "hey put in a search term!"

+1 to Remove "Browse Projects" link.

**Comment by di** [comment]
The downside to removing the "Browse Projects" link is that if we do, there isn't a great path for the user that just wants to start applying classifiers, so I'm not sure I'm +1 on that.

**Comment by pv** [comment]
Changing the "browse projects" ordering to "Date last updated" would also improve the situation.

**Comment by brainwane** [comment]
In our [meeting this week](https://wiki.python.org/psf/PackagingWG/2018-02-26-Warehouse) we decided to provide a temporary fix of some kind here -- for instance, just providing the help text, or something like that -- for launch. And then at some future time we can make a more robust solution.

**Comment by brainwane** [comment]
@nlhkabu please let us know if you're blocked and need any more guidance on what the initial temp fix here ought to be.

**Comment by nlhkabu** [comment]
I agree with @di that it would be a shame to hide this - because it gives people a way to find packages using only filters.

I think the best temporary fix is to do what @pv describes - to change the default order (when no search is applied) to be "date last updated".

Another solution might be to show nothing by default, and add some placeholder text like "Search or apply filters to view relevant packages".

I will rely on @di to tell me which is easier :P

**Comment by nlhkabu** [comment]
Sorry, I just realised that I totally repeated what @ewdurbin said there!  :P

**Comment by brainwane** [comment]
OK, I think we have a TODO here: when the user has not selected/input any search query parameters (via GET to `https://pypi.org/search/?q=` or specifically `https://pypi.org/search/` with no trailing query parameters), display some placeholder text. I can suggest some copy:

> Enter a search query above, or select a filter from the list of classifiers on the left. You can combine searches and classifier filters. Examples:
> * [New Python 3 project releases](https://pypi.org/search/?q=mass&o=-created&c=Programming+Language+%3A%3A+Python+%3A%3A+3)
> * [Sphinx extensions that are stable/production status](https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+Sphinx+%3A%3A+Extension&c=Development+Status+%3A%3A+5+-+Production%2FStable)
> * [Graphics projects under OSI-approved licenses](https://pypi.org/search/?q=graphics&o=&c=License+%3A%3A+OSI+Approved)

**Comment by brainwane** [comment]
@yeraydiazdiaz, @aalmazan, @Volcyy, @HndrkMkt, @cryvate, @asottile, would one of you be interested in working on this?

**Comment by nlhkabu** [comment]
@brainwane - I have a PR on progress for this ticket.  But it would be great if one of the devs you have pinged could review it? I hope to push it today/tomorrow morning :)

**Comment by nlhkabu** [comment]
I've made the PR (see #3327), but I have a question about the best way to set up the example search/filters.

If @yeraydiazdiaz, @aalmazan, @Volcyy, @HndrkMkt, @cryvate, or @asottile could take a look at the PR, that would be great!!

**Comment by brainwane** [comment]
@hnykda Thanks for reporting this issue! Hope we've taken care of the problem you saw.
