### ISSUE TITLE
Images > 5MB in description 404 without indication why

### ISSUE THREAD

**Issue by jwkvam** [pypa/warehouse#3078]
The rst rendered on pypi.org seems to have mangled my gif img.

https://pypi.org/project/bowtie/#description

The old pypi renders it fine.

https://pypi.python.org/pypi/bowtie/

The markup is this
```
.. figure:: https://cloud.githubusercontent.com/assets/86304/20045988/69e5678a-a45a-11e6-853b-7f60a615c9da.gif
   :alt: Demo
```

This is the generated img url on pypi.org:
```
src="https://warehouse-camo.herokuapp.com/ef2d4931bffa7d88bd7df3d2c31bc217354c829c/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f38363330342f32303034353938382f36396535363738612d613435612d313165362d383533622d3766363061363135633964612e676966"
```

Source is here https://github.com/jwkvam/bowtie

```
$ python setup.py check --restructuredtext
/Users/jacques/miniconda/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/Users/jacques/miniconda/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running check
```

**Comment by di** [comment]
After testing this, the reason your image is failing is because the source image is too large. There is a 5MB limit on our `camo` service and your image just barely exceeds it.

The short-term fix is to shrink your image's size. I'll leave this issue open while we work on making the reason for the failure more apparent to Warehouse users.

**Comment by jwkvam** [comment]
Thanks for letting me know, I will update my image. Thanks!

**Comment by di** [comment]
I have a PR up for our camo service to make it possible to redirect to a custom image: https://github.com/pypa/warehouse-camo/pull/1

**Comment by brainwane** [comment]
@jw thanks for reporting this.

Last week Dustin's PR got merged into the camo repo, today we got the camo service deployed to [cabotage](https://github.com/cabotage/cabotage-app), and tomorrow @nlhkabu will be creating a placeholder image that Warehouse can show instead of the broken-because-it-is-too-large image.

**Comment by brainwane** [comment]
Ping @nlhkabu. :)

**Comment by nlhkabu** [comment]
hi @di - with https://github.com/pypa/warehouse/pull/3261 merged, can we now close this?

**Comment by brainwane** [comment]
@nlhkabu maybe I'm wrong, but isn't this issue waiting for an image placeholder from you?

**Comment by di** [comment]
@brainwane I added an update to `pypi-theme` in #3261 which has the image placeholder.

Looks like @ewdurbin has already configured camo to redirect to this image, looking at https://pypi.org/project/bowtie/ I see it there, so yes I think this is finished.

**Comment by brainwane** [comment]
AHA, `pypi-theme` is that repo that I can't access, so I was looking at the wrong PR. I'm sorry for misunderstanding.
