### ISSUE TITLE
Last-Modified header reported incorrect on file downloads

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3108]
From IRC just now:

> [illume] File dates are wrong on file downloads. They are correct on cheeseshop. Last-Modified header is incorrect. I guess this is a pretty major bug, as the date is pretty important in a file host because release date is important meta data.

**Comment by di** [comment]
I think we need more information here? I'm not seeing a `Last-Modified` header at all on file downloads:

```
$ http get https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl --headers
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 80650
Cache-Control: max-age=31557600, public
Connection: keep-alive
Content-Length: 24075
Content-Type: binary/octet-stream
Date: Thu, 01 Mar 2018 16:17:00 GMT
Server: AmazonS3
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Cache: HIT, MISS
X-Cache-Hits: 39, 0
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Permitted-Cross-Domain-Policies: none
X-Robots-Header: noindex
X-Served-By: cache-sea1042-SEA, cache-dfw18640-DFW
X-Timer: S1519921021.729954,VS0,VE52
X-XSS-Protection: 1; mode=block
```

I do see it for legacy:

```
http get https://pypi.python.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl#md5=243fd003a3598dd7006e4e17f59a3a5e --headers
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 80937
Cache-Control: max-age=31557600, public
Connection: keep-alive
Content-Length: 24075
Content-Type: binary/octet-stream
Date: Thu, 01 Mar 2018 16:21:49 GMT
ETag: "243fd003a3598dd7006e4e17f59a3a5e"
Fastly-Debug-Digest: b833426cb8b3bc30a92b4145d9def7577b64172805780b782dca2f6ccf7428b4
Last-Modified: Wed, 28 Feb 2018 17:52:51 GMT
Server: AmazonS3
Via: 1.1 varnish
Via: 1.1 varnish
X-Cache: HIT, HIT
X-Cache-Hits: 3, 1
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Permitted-Cross-Domain-Policies: none
X-Served-By: cache-sea1034-SEA, cache-dfw18630-DFW
X-Timer: S1519921310.689576,VS0,VE1
X-XSS-Protection: 1; mode=block
x-amz-meta-package-type: bdist_wheel
x-amz-meta-project: packaging
x-amz-meta-python-version: py2.py3
x-amz-meta-version: 17.1
x-amz-replication-status: PENDING
```

Is the issue that it doesn't exist?

**Comment by ewdurbin** [comment]
we're explicitly stripping those headers when serving from files.pythonhosted.org:

https://github.com/pypa/warehouse/blob/b66a37d0f5dd5d77730a1bfa427548aa554c40b5/vcl/main.vcl#L322-L337

we might want to adjust the ordering as it sounds like this should only be getting stripped for non 200 responses.

**Comment by di** [comment]
Right, which is why I'm confused about the OP saying "File dates are wrong on file downloads" rather than "File dates are missing on file downloads"

**Comment by ewdurbin** [comment]
wget for instance sets the resulting file's modified time to the value from Last-Modified. this is likely what the reporter is referencing.

**Comment by brainwane** [comment]
We discussed this in [today's Warehouse core developers meeting](https://wiki.python.org/psf/PackagingWG/2018-03-12-Warehouse). Since this is a regression, we should fix it before shutting down the legacy site.

And the header-stripping is probably an accident rather than intentional. @dstufft, Dustin and Ernest would like you to weigh in on this.

**Comment by dstufft** [comment]
Recording this here since I said it in Slack:

This was not done accidentally, but was instead done to disable support for conditional ``GET``s for hosted files. The metrics pipeline inside of Fastly uses response headers to store information about the file (such as project, version number, etc) which it then logs to Linehaul and ultimately ends up in BigQuery. There was an issue where a number of errors were being reported to Sentry due to missing headers, and after diving into the issue, the ultimate conclusion was that these extra response headers were being omitted in the case of a 304 response to a conditional ``GET``. After discussing this with Fastly, it was determined that the RFC doesn't allow any additional headers besides a white list, and Fastly was dutifully stripping them from our response.

It was decided that because we have a very long cache time on these files, that we could afford to lose the efficiency of a conditional ``GET`` in order to keep the download count numbers more closely aligned with the actual number of downloads. Thus we stripped ``Last-Modified`` and ``ETag`` from files when serving them, to prevent clients from ever even attempting to do a conditional ``GET``.

I believe it is also possible to change this code so that instead of omitting ``Last-Modified`` and ``ETag`` from the response, we strip ``If-None-Match`` and ``If-Modified-Since`` from the request headers for files, which should also have the effect of disabling conditional ``GET`` support (assuming of course, that Fastly's support for conditional ``GET`` happens after the point we strip those headers) while retaining these headers on the responses.

**Comment by dstufft** [comment]
Oh, and of course there is always the option of deciding that the original decision (that losing conditional ``GET`` is an OK price to pay for more accurate download counts) was wrong, and to simply remove this code and let us not record downloads if they occurred as part of a conditional ``GET``.

**Comment by brainwane** [comment]
@illume are you the illume who mentioned this issue in IRC? I'd like to better understand 

1. what bit of software, somewhere between PyPI and you, is setting an incorrect `Last-Modified` header
2. your use cases

so we can decide whether to change Warehouse's behavior. Thanks.

**Comment by dstufft** [comment]
This is working now:

```
$ curl -I https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
HTTP/2 200
last-modified: Tue, 15 Aug 2017 13:23:46 GMT
etag: "eb9be71cc41fd73a51a7c9cd1adde5de"
content-type: binary/octet-stream
server: AmazonS3
cache-control: max-age=31557600, public
accept-ranges: bytes
date: Thu, 12 Apr 2018 21:57:23 GMT
age: 6259621
x-served-by: cache-sea1034-SEA, cache-ewr18144-EWR
x-cache: HIT, HIT
x-cache-hits: 25463, 1
x-timer: S1523570244.606736,VS0,VE0
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: deny
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-permitted-cross-domain-policies: none
x-robots-header: noindex
content-length: 88704
```
