### ISSUE TITLE
Better metadata for Twitter

### ISSUE THREAD

**Issue by di** [pypa/warehouse#3112]
Currently links to `pypi.org` shared on Twitter look pretty plain:

<img width="585" alt="screen shot 2018-03-01 at 9 59 50 am" src="https://user-images.githubusercontent.com/294415/36854739-4fa716fa-1d37-11e8-867b-842bbeebf3d9.png">

The grey icon is Twitter's default. We're setting an `og:image` meta tag, but [there seems to be some additional metadata tags we can add](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started).

https://github.com/pypa/warehouse/issues/2211 proposes being able to set this per-project, but for now, it'd be nice if this was the PyPI logo instead.

Also, Twitter provides a validator to test with: https://cards-dev.twitter.com/validator

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by jMuzsik** [comment]
Hi all, I'd like to give this a go

**Comment by brainwane** [comment]
@jMuzsik Sure, go ahead! (In case you didn't see the thumbs-up from Dustin.)

**Comment by jMuzsik** [comment]
Ok, forking right now, saw the triaging reference so I thought you guys were still talking about it. I think I'd like to pick up another good first issue as well as this one looks very easy.

**Comment by brainwane** [comment]
Thanks, @jMuzsik! I am doing a big issue sweep right now and will be updating metadata for a bunch of issues -- whether they need triaging, which milestone (if any) they belong in, and so on. Sorry for the miscommunication.

Once you're done with this one, maybe you could do #3139, if no one has done it by then?

**Comment by jMuzsik** [comment]
The confusing part about this issue is that (correct me if I am wrong) I cannot see if it works unless the code gets pulled in because I have no way to validate a card unless the site exists.

The problem is here:

https://github.com/pypa/warehouse/blob/55000586ac999ae7eacc2635633777ccb0d0e428/warehouse/templates/base.html#L64

I have two guesses, one is very likely the problem.

1. SVG is not supported: [Twitter Docs](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary) state: 

`twitter:image`

A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 1:1 with minimum dimensions of 144x144 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. The image will be cropped to a square on all platforms. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. **SVG is not supported.**

2. Or because the image is stored statically it is not being rendered.

I need something like this: 

```html
<meta property="og:image" content="http://graphics8.nytimes.com/images/2011/12/08/technology/bits-newtwitter/bits-newtwitter-tmagArticle.jpg" />
```

So ought I to add a jpg of the svg in the static images and then rewrite the metadata as so:

 ``` html
<meta property="og:image" content="{{ request.static_url('warehouse:static/dist/images/logo-large.jpg') }}"> 
```

**Comment by di** [comment]
@jMuzsik 

> The confusing part about this issue is that (correct me if I am wrong) I cannot see if it works unless the code gets pulled in because I have no way to validate a card unless the site exists.

Yes, this is true unless you use a service like https://ngrok.com/ to give you a public URL to your local dev environment to test.

> SVG is not supported

Good catch! Seems like this is why. We'll have to generate a PNG from the SVG and add it to the `pypi-theme` repo (which is private). I'll create an issue there and put the blocked label on this issue until it's done and the image is available.

**Comment by di** [comment]
We now have the following image which can be used for Twitter:

![](https://pypi.org/static/images/twitter.jpg)

Which can be used with `request.static_url('warehouse:static/dist/images/twitter.jpg'`

**Comment by di** [comment]
<img width="577" alt="screen shot 2018-03-20 at 4 51 35 pm" src="https://user-images.githubusercontent.com/294415/37684733-fa9a082a-2c5e-11e8-9e77-5be346023146.png">

Looks great!

**Comment by brainwane** [comment]
I'm not sure why https://twitter.com/yera_ee/status/976472212889796609 by @yeraydiazdiaz doesn't look like that. Yeray tweeted it after we deployed the change on pypi.org. Screenshot:

![yeray-tweet](https://user-images.githubusercontent.com/842790/37723616-34773be8-2d05-11e8-990f-06fcb9aca436.png)

**Comment by di** [comment]
Looks correct to me now:

<img width="607" alt="screen shot 2018-03-21 at 11 46 49 am" src="https://user-images.githubusercontent.com/294415/37723913-91a8fe44-2cfd-11e8-91c9-d33f6d40ccb4.png">

Likely the project page hadn't fallen out of the cache yet, and this isn't really worth issuing a `purge-all` for.
