### ISSUE TITLE
Add a "shortlink" for projects

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3143]
**From user testing:**

When viewing projects on PyPI, some users type the URL directly if they know the project name.

We should create a shortlink like`pypi.org/p/myproject` which would redirect to `pypi.org/projects/myproject`

cc @di for feedback / guidance.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
Going to remove the "good first issue" label from this. IMO while this would be nice, it's not likely to happen.

We have a number of other routes that sit at the top level path here, and this would make packages conflict with them, e.g. would https://pypi.org/help/ go to our "Help" page (as it does now) or to the `help` project (currently at https://pypi.org/project/help/)?

We would need to 'audit' the existing routes for conflicting projects and either rename our routes or "reserve" the project name for our own routes.

This would also make adding new routes harder in the future, because we'd need to go through the same process, rather than just adding it as we do now.

**Comment by paternal** [comment]
What about a short route? E.g. https://pypi.org/p/foobar which would replace, or be an alias to https://pypi.org/project/foobar . It would be a shorter URL to type directly, while not messing up "non project" routes (like https://pypi.org/help).

**Comment by dstufft** [comment]
I'd be fine with a shorter router as an alias. I don't think we gain much by making it the canonical location, but a blanket redirect of ``/p/`` to ``/project/`` seems like it'd be fine, and let people type out something shorter.

**Comment by di** [comment]
Sounds good to me, this is probably a "good first issue" then. I've updated the title/description/labels accordingly.
