### ISSUE TITLE
Modal disappears when mouse leaves window

### ISSUE THREAD

**Issue by di** [pypa/warehouse#3152]
When a modal is up, like the "Delete Release" modal, the modal disappears when the user moves the mouse outside the browser window. It only reappears when the user hovers over the button:

![mar-06-2018 19-04-26](https://user-images.githubusercontent.com/294415/37067844-6a6ee3e4-2171-11e8-8cb4-058b04ab5ae4.gif)

**Comment by nlhkabu** [comment]
This is so weird.  Thanks for finding it @di.  I'll look into it :)

**Comment by brainwane** [comment]
This is something that perhaps someone else would like to pick up? @Volcyy, @jw, @aalmazan, @yeraydiazdiaz, perhaps one of you would be interested?

**Comment by brainwane** [comment]
This is reasonably high in urgency, as we need it fixed before launch - so, ideally, within the next 5-7 days.

**Comment by yeraydiazdiaz** [comment]
I had a quick look, seems it's caused by the modal being a child of the "Options" dropdown, when moving the mouse away the dropdown hides along with the modal, it reappears when hovering back.

![modal_disappears](https://user-images.githubusercontent.com/6739793/37391177-512d5ca2-2762-11e8-8e3c-8484b9760a18.gif)

My first instinct is to decouple the modal from the dropdown, either by creating all modals in the template and showing and hiding via Javascript or have it create the modals dynamically.

Does that sound reasonable?

**Comment by di** [comment]
@yeraydiazdiaz I reverted #3251 because we discovered this bug that I missed on review:

![2018-03-15 15 43 33](https://user-images.githubusercontent.com/294415/37489237-fc101738-2864-11e8-8216-52e28d779b44.gif)

**Comment by yeraydiazdiaz** [comment]
sorry about that, I'll see if I can fix it
