### ISSUE TITLE
Add JS validation when passwords do not match

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3197]
It would be nice to use JavaScript to indicate whether or not the passwords match:

1. show a message
2. conditionally enable the button

----

![screenshot from 2018-03-09 06-36-40](https://user-images.githubusercontent.com/3323703/37194259-48d7d8da-2365-11e8-83b1-82bac0c1e220.png)

----

![screenshot from 2018-03-09 06-36-40-match](https://user-images.githubusercontent.com/3323703/37194328-94f916c0-2365-11e8-8cb5-bee346c806da.png)

@yeraydiazdiaz would this be something you might enjoy working on?

**Comment by yeraydiazdiaz** [comment]
Sure, I'll take the opportunity to rewrite the feature in Stimulus.

Disabling the submit button was something [we explored before](https://github.com/pypa/warehouse/pull/2542#issuecomment-341894703) and decided against it. We are now using a pattern where feedback is given when clicking on the submit button in the form of tooltips.

Do we want to mix both feedback flows?

**Comment by di** [comment]
@yeraydiazdiaz Great question. The submit button disabling was a problem on the registration form because there wasn't a way to provide feedback if the user was missing one of the required fields.

I think here it's OK, since it should be pretty clear to the user that they need to fill out the password field in order to be able to change their password, and we'll be able to conditionally show the "passwords match"/"don't match" message when the first field is filled out.

**Comment by yeraydiazdiaz** [comment]
@nlhkabu which CSS classes are you using for the messages? The closest thing I'm finding are badges and don't quite look the same

**Comment by nlhkabu** [comment]
@yeraydiazdiaz you could use `warehouse/static/sass/blocks/_form-errors.scss` to display the error.
For the green, you could create a `.form-error--valid` modifier on this component. Let me know if you need a hand with that - if you prefer you could push the PR unstyled and I can add a commit for this :)
