### ISSUE TITLE
config.yml defaults do not match documentation

### ISSUE THREAD

**Issue by vladimir-v-diaz** [pypa/warehouse#325]
According to the Warehouse configuration documentation, "The default configuration for Warehouse is inside of the warehouse/config.yml file."

[configuration.rst](https://github.com/pypa/warehouse/blob/master/docs/configuration.rst) specifies defaults that do not match [config.yml](https://github.com/pypa/warehouse/blob/master/warehouse/config.yml)

For example:
Debug is `False` [by default](https://github.com/pypa/warehouse/blob/master/warehouse/config.yml#L1), but the documentation states debug should be `True`.

paths.documentation is `None`, but the default value in `config.yaml` is `data/packagedocs`.

There are also inconsistencies with the descriptions.  `database.url` requires postgresSQL 9.3+, but the contributing document specifies 9.2+.  There are others.

Should this document be updated to match `config.yml`?

**Comment by dstufft** [comment]
I'm going to close this, I've started porting Warehouse over to Pyramid to ease the concerns of the custom framework-ish thing I've got going on here. That work is on the pyramid branch inside this repository. Since that includes all new configuration and configuration files, this issue does not really apply anymore.
