### ISSUE TITLE
Maintainers needs more right

### ISSUE THREAD

**Issue by noirbizarre** [pypa/warehouse#3250]
Hi !

I just tried the new warehouse, but in many case I can't do anything: I have a lot of project where the owner is one account created for an organization but on which I work as a maintainer with my own account.
This workflow doesn't seems to work on warehouse because maintainers can't do anything else that publish new releases.
I can't delete release anymore on warehouse as a maintainer, the role changed.

Is this possible to:
- have multiple owner on a project ?
- have an intermediate role between maintainer and owner with more rights ?
- have the same permissions for maintainers in warehouse than the legacy PyPI ?
(I think any of these solutions do the job)

**Comment by brainwane** [comment]
Hi, @noirbizarre, and thanks for trying Warehouse and letting us know of your problem!

Right now, in Warehouse, 

* an Owner owns a project, may add other collaborators for that project, and upload releases for a project. May delete files or releases. Can delete the entire project.

* a Maintainer may upload releases for a project. Cannot add collaborators, delete files, delete releases or delete the project.

Can you talk a little about how often you need to delete releases? My personal assumption is that projects very rarely need to delete releases, because instead of deleting a release, a project usually wants to make a new release that supersedes the old one.

Yes, indeed, it is possible to have multiple owners on a project. It sounds like the Owner for many of your projects should promote your account to Owner for those projects.

Thanks!

**Comment by noirbizarre** [comment]
Hi, I just tested a little bit more and this does not seems to be an issue anymore.
My primary use case was: I need to remove the latest development build so people only see stable version (and this was a daily job). But this is fixed in warehouse by #1519 so there is no need anymore to do so :tada: 
Plus, It's already possible to have multiple owners, so everything is perfect :ok_hand:

**Comment by brainwane** [comment]
@noirbizarre Thanks for the update. Glad to hear Warehouse works for you. :tada: 

Please consider signing up for our low-traffic [announcement email list](https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/) to get a heads-up when we make any big changes in the future.
