### ISSUE TITLE
Document how to add code to dismiss notification bar

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3379]
We should add some help text at the top of `static/sass/blocks/_notification-bar.scss` to explain how to make a notification bar dismissible.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by pgadige** [comment]
I'd like to work on this, @nlhkabu. I'll appreciate some insight on what qualifies as help text.

What should we provide to the reader of `static/sass/blocks/_notification-bar.scss` file as help text?

Should we explain adding `.notification-bar--dismissable` and `.notification-bar--visible` to the div tag that's used to make notification bar together with a button with `.notification-bar__dismiss` to click on to dismiss/close the notification bar?

**Comment by nlhkabu** [comment]
@aalmazan would you be able to give @pgadige some help direction on how best to document this?  Thanks :)

**Comment by nlhkabu** [comment]
@aalmazan would you be able to give @pgadige some guidance on how to document this?  Thanks :)

**Comment by aalmazan** [comment]
Hi @pgadige,

I'm not sure how much detail you need, but since it's not particularly a big feature, I'll describe most of the workflow.

To make a notification dismissable one would need to add the following to the main notification-bar div:
* `.notification-bar-dismissable` to its classes
* `data-controller="notification"` and,
* `data-target="notification.notification"` as attributes

The `data-controller` and `data-target` attributes are used by `warehouse/static/js/warehouse/controllers/notification_controller.js` to handle visibility -- this includes adding `.notification-bar--visible` to the notification if it has not been dismissed (and persisted) yet. 

Also, note that if Javascript is disabled the styles in `warehouse/static/sass/noscript.scss` will be used instead. This mainly defaults notifications to always be visible. 

Let me know if you need anything else!
