### ISSUE TITLE
Status of the project (aka is it dead)?

### ISSUE THREAD

**Issue by karan** [pypa/warehouse#348]
So I'm checking back on this project after a rather long time, and it seems like there hasn't been much activity (no commits since I was here last time), no docs updates.

Is this project dead? Does it still need help? How can we help?

Where is the project headed?

**Comment by msabramo** [comment]
Last time I talked to @dstufft about it on IRC, he was very much still interested, but had a shortage of time.

**Comment by karan** [comment]
I'm willing to help. But I don't know what's pending (can see issues but not what do to first), where to begin or how to start. Some docs on development and the code itself would be super helpful (especially for navigating the code).

**Comment by msabramo** [comment]
@dstufft committed just 2 hours ago. So hopefully he'll have a bit of time to update.

**Comment by chhantyal** [comment]
I was also checking if there was any way I could help cause I really liked when it was crate.io 

A roadmap would be really nice, and hopefully would help it to make pypi.python.org

**Comment by dstufft** [comment]
It's not dead, but I'm working on a fairly major refactoring to move it away from the custom-ish framework which should alleviate the concerns people have with the current code base.

**Comment by msabramo** [comment]
Pyramid! :)

**Comment by iElectric** [comment]
:beers:

**Comment by piotr-dobrogost** [comment]
@dstufft 

I'm curious as to why did you choose Pyramid over Django or some other Python web framework? (Not that I have something against Pyramid; quite the opposite :))

**Comment by dstufft** [comment]
Warehouse has gone through about four iterations now:

1. Django - This "worked", but the Django ORM wasn't powerful to handle all of the things that the PyPI schema uses (though off the top of my head, I can't recall what exactly) and if we replaced the ORM with SQLAlchemy you're more or less throwing away the most compelling feature of Django, the massive ecosystem around it. There were also concerns I had where I wanted to do things a little strangely in order to enable things like maximizing cacheablity of Warehouse (Things like accessing the session requires decorator a view). I also think that the Pyramid render system is really great and I like it better than how Django typically works (especially since at the time Django didn't have multiple template engine support so it was really jsut the DTL that worked well). Finally I don't like global state (although Django only really uses it for settings, which isn't the worst thing).
2. Werkzeug - This "worked" too, and it didn't have any global state which I liked. However Werkzeug is very pretty low level and it doesn't do a whole lot for us. This had the effect that I was essentially creating my own custom one off framework that nobody but me really knew how it worked (and there was no documentation or anything for other people to learn it). It also had the effect that nobody else could really work on things easily because adding new features to the "framework" was bottlenecked on me to figure out how I liked that feature to work.
3. Flask - This didn't get very far. Flask works great for small things, but I really dislike it for anything other than small toys. I think that using import as a way to pass variables into a function is wrong and makes for worse and more confusing code. It also has the effect that if you're attempting to write things *for* flask you're essentially all in on the import as a way to pass variables and you end up with a whole bunch of them.
4. Pyramid - This is what we're on now and I think it's unlikely it'll move away from this. It solves most of the problems I have with the above and it generally doesn't annoy me. In particular it's flexibility is great for a project like PyPI where we have a decade or so of legacy to contend with.

**Comment by brainwane** [comment]
@karan I know this is a very old issue, but I figured you ought to know: [we now have a Warehouse roadmap](https://wiki.python.org/psf/WarehouseRoadmap) and [we're happy to help you get started contributing to Warehouse](https://twitter.com/EWDurbin/status/955415184339849217)!
