### ISSUE TITLE
Add PYZ Upload

### ISSUE THREAD

**Issue by juancarlospaco** [pypa/warehouse#3587]
- Add the possibility to Upload `*.PYZ`, made using std lib `zipapp.create_archive()`.

**Comment by brainwane** [comment]
Thanks for your suggestion, @juancarlospaco! I don't know what work would be necessary in order for the Python Package Index to support [`zipapp` archives](https://docs.python.org/3.5/library/zipapp.html) alongside source distributions and wheels -- the [distutils-sig mailing list](https://mail.python.org/mailman/listinfo/distutils-sig) might be a good place to discuss what other parts of the toolchain might need to also add functionality in order to upload or manage these archives.

**Comment by brainwane** [comment]
@juancarlospaco I need to correct you -- right now, a person can upload a wheel or a source distribution (sdist) to PyPI. Please see https://packaging.python.org/tutorials/distributing-packages/#packaging-your-project for more details.

I don't know whether PyPI's maintainers will choose to implement `.pyz` support at all, or anytime soon (we need to discuss it, so I've labelled this issue with "needs discussion"). I'd like to get more information.

Are you a packager of a project whose users want to download and install `.pyz` files? And how does the size of a `.pyz` file compare to an sdist or a wheel for the same project?

**Comment by brainwane** [comment]
I'm grateful that you brought this idea to our attention -- I look forward to getting more info. :)

**Comment by juancarlospaco** [comment]
About Size is kinda `*.pyz` == `*.zip` of the sdist, its a Zip anyways.

**Comment by brainwane** [comment]
Hi @juancarlospaco -- could I ask why you closed this? Thanks!
