### ISSUE TITLE
Automagic GitHub repo stats display doesn't find www.github.com/user/repo URLs

### ISSUE THREAD

**Issue by bskinn** [pypa/warehouse#3643]
As noted [here](https://github.com/pypa/warehouse/pull/2163#pullrequestreview-111691465), the automagic sidebar stats feature when a GitHub repo is the project homepage doesn't activate if the URL is written using `www.github.com`; it only finds `github.com` URLs.

**Comment by di** [comment]
We probably should make sure that this works for URLs like `github.com` and `www.github.com`, but not something like `thisisnotgithub.com`.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by bskinn** [comment]
Mm, <nod>... `.endswith('.github.com')` might suffice?

**Comment by di** [comment]
> Mm, ... `.endswith('.github.com')` might suffice?

I don't think this would work for a URL like `https://github.com/pypa/warehouse`

**Comment by bskinn** [comment]
Are there any other common `*.github.com` URLs that would ***not*** be composed as `*.github.com/user/repo/...`, and that someone might want to use as a homepage URL?

If so, a pattern matching condition might get pretty messy.  A narrower compound condition might be better.

    if (parsed.netloc == 'github.com' or parsed.netloc == 'www.github.com') and ...

**Comment by brainwane** [comment]
@bskinn Hope you don't mind -- since this is an improvement to a new feature, I'm marking it as something we can do after we shut down the legacy PyPI site.

**Comment by bskinn** [comment]
@brainwane Nope! I figured it would get slotted for further down the pipeline, since it's a minor glitch.

**Comment by di** [comment]
To be clear: if you made a PR to fix this I would merge it, it's just not going to get fixed by one of the maintainers soon.

**Comment by bskinn** [comment]
@di I can put together a PR to fix it, no problem; but I'm not set up with docker &c. to run the test suite locally.  Can I just rely on Travis to test it for me?

Also, if I'd need to add a test for the new behavior, I'd need guidance as to where in the test suite to add it.

**Comment by di** [comment]
@bskinn Travis will definitely test it for you. You probably don't need to be able to run the tests locally to fix this issue, but it's not too complicated and we have a pretty good guide: https://warehouse.readthedocs.io/development/getting-started/
