### ISSUE TITLE
[Feature Request] More predictable download links

### ISSUE THREAD

**Issue by inducer** [pypa/warehouse#3738]
When I copy a download link from https://pypi.org/project/virtualenv/, I get:

https://files.pythonhosted.org/packages/b1/72/2d70c5a1de409ceb3a27ff2ec007ecdd5cc52239e7c74990e32af57affe9/virtualenv-15.2.0.tar.gz

This makes me feel bad when I copy-paste that URL into scripts:

* I wonder about the long-term stability of the link, because it contains what looks like unpredictable extra hash gunk.
* Changing the version number looks like it might require an (inefficient) trip to the package indiex to look up the new version of the hash gunk.

Could there be an option for a copy-pastable perma-URL that's suitable for scripting that does not contain non-user-maintainable information?

**Comment by ewdurbin** [comment]
This URL structure is not new. It was enforced when we moved file hosting to AWS S3.

These URLs are static and do not change, the hash gunk is calculated from the checksum of the file.

## Official guidance

Query PyPI's index to determine where to download files from.

## If you so choose

You _can_ use our conveyor service to fetch this file, but this realistically exists primarily to support old build systems and others that refuse to query the index.

```shell
$ curl -I https://files.pythonhosted.org/packages/source/v/virtualenv/virtualenv-15.2.0.tar.gz
HTTP/2 302 
location: https://files.pythonhosted.org/packages/b1/72/2d70c5a1de409ceb3a27ff2ec007ecdd5cc52239e7c74990e32af57affe9/virtualenv-15.2.0.tar.gz
```

But as you'll note, it is just a redirect to the canonical file.

You should generally query the index for package URLs rather than guessing, but the url structure for the redirect service is:

```
/packages/{python_version}/{project_l}/{project_name}/{filename}
```

where `project_l` is the first letter of the project name.

`python_version` can be one of many things, akin to the old file structure PyPI used to hold on disk.

In general this is only a good idea for `source` as a `python_version` to fetch tar and zip files.

**Comment by inducer** [comment]
Thanks for the explanation!
