### ISSUE TITLE
New classifier request tox

### ISSUE THREAD

**Issue by gaborbernat** [pypa/warehouse#3766]
tox supports plugins, similar to how pytest does it. Can we have a framework classifier to make it easier for users to locate plugins?

Thanks 

https://github.com/tox-dev/cookiecutter-tox-plugin/issues/4

**Comment by di** [comment]
@gaborbernat To be clear, you're asking for a classifier like `Framework :: Tox`, correct?

**Comment by gaborbernat** [comment]
with lower case, but yes; so ``Framework :: tox``

**Comment by di** [comment]
@hpk42 @obestwalter Care to add your support for this classifier?

Historically classifiers have been title-cased (e.g., `Framework :: Pytest`) so unless the `tox` maintainers have strong feelings about the casing of the name, I'm inclined to prefer `Framework :: Tox` for consistency's sake.

**Comment by obestwalter** [comment]
Hi @di - thanks for picking that up. I would also think it can't hurt to have a classifier for tox, as there is a growing number of projects and plugins around it. Regarding the casing: I would definitely prefer `tox`. I just scrolled through all existing classifiers and all but two are Title Cased. So seeing some lower case things there already I would think we can keep tox lower case also? 

The real problem is though: people are not very consistent. So I would be intersted, if it matters to PyPi at all. Does the user get an error, if they write e.g. pytest instead of Pytest in their classifier? I can't try it out myself right now and googling if the classifiers are case sensitive did not turn up something right away either. 

If it gets normalized anyway it doesn't really matter that much to me, then I can at least write the classifier in my projects "correct". But if the user gets an error if they write tox and **have** to write Tox, then I would say it definitely has to be lower case.

**Comment by gaborbernat** [comment]
@di any updates on this?

**Comment by di** [comment]
I've added the classifier `Framework :: tox`, thanks for your patience.

**Comment by obestwalter** [comment]
Hi @di thanks a lot!
