### ISSUE TITLE
Only Python 2 version showing for universal wheel

### ISSUE THREAD

**Issue by jadolg** [pypa/warehouse#3803]
Hi, I have uploaded a new version of my library which is a universal wheel. It's platform independent and works with both python 2 and 3 but Python Version of the download files section only shows 2.7.
![image](https://user-images.githubusercontent.com/5427672/39211612-2e26275a-47da-11e8-9ef6-4e49c66937df.png)

**Comment by di** [comment]
@jadolg Can you link us to the project in question?

**Comment by dstufft** [comment]
This happens when you upload with ``python setup.py upload`` instead of twine.

I wonder if we shouldn't just remove the column completely. It's kind of silly since it's either going to be nothing (sdists) or already represented in the wheel filename. It might still be relevant for eggs, but I don't think so there either.

**Comment by jadolg** [comment]
https://pypi.org/project/rocketchat-API/

**Comment by brainwane** [comment]
@jadolg would you mind telling us whether this problem still happens if you do the following?

* use Twine to upload, specifically `twine>=1.11.0` -- see https://packaging.python.org/tutorials/distributing-packages/ for usage instructions
* make sure you're using `setuptools>=38.6.0`, `wheel>=0.31.0`, and `pkginfo>=1.4.2` (to cover PEP 566 issues per https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi )

To test this, you can add `dev[n]` to the end of your version number (as in, `0.6.8dev1`) and upload to Test PyPI (instructions: https://packaging.python.org/guides/using-testpypi/ ).

Thanks!

**Comment by jadolg** [comment]
thanks, @brainwane. I uploaded a new version using Twine and all problems are gone. The version string is correct, markdown is rendering perfectly and this [odd issue](https://github.com/jadolg/rocketchat_API/issues/20) I had in my library just disappeared.
Is there a way to avoid users to upload their packages using other ways? I've never used Twine before. I always used good old `python setup.py bdist_wheel upload` with no problems.

**Comment by brainwane** [comment]
@jadolg Thanks for the update.

In a sense you're asking: how do we get users to only use one way to upload stuff to PyPI, or make sure the ways most people do their uploads is supported, or warn them when something they're doing is apt to cause hard-to-diagnose problems? That's a big infrastructural (social infrastructure and digital infrastructure) problem and we're talking about it in https://github.com/pypa/packaging-problems/issues/107 and https://github.com/pypa/packaging-problems/issues/129 and https://github.com/pypa/twine/issues/154 plus other places. I'm sorry for the trouble.
