### ISSUE TITLE
"Latest" version for project detail should take into account PEP 440 pre-releases

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#382]
Right now the latest version that is shown when looking at an project detail without a version is the absolute latest version. Ideally this would do something similar to what PEP 440 suggests for installers, get the latest non pre-release version and if that fails, then include pre-releases.

This might involve trying to write a `PEP440Version` database type that understands the PEP 440 version constraints. I'm unsure what the best way of handling this would be.

**Comment by Carreau** [comment]
+1 for that. Just got affected while searching.

alpha, beta and rc should likely have lower score

**Comment by brainwane** [comment]
For context, for @Carreau:

The folks working on Warehouse have recently gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable. Since this is a request for polish in the browser UI, I've moved it to a future milestone.

Thanks and sorry again for the wait.

**Comment by brainwane** [comment]
@HndrkMkt would you be interested in working on this?

**Comment by dstufft** [comment]
This is done already, just never got flagged as completed.
