### ISSUE TITLE
Name-Squatting on Pypi.org: Removed projects if no code is added after 6+ months

### ISSUE THREAD

**Issue by jeff00seattle** [pypa/warehouse#4004]
**What's the problem this feature will solve?**
On Pypi.org, there are several Python projects that are completely empty, no content except a one-line README, and have not been touched in years for the single purpose of name-squatting, for example, `requests_extension` was created in 2014 and nothing since.
Name-Squatting Example with Inactive Contributors (not okay): https://pypi.org/project/requests_extension/#description

I can understand for those active Pypi.org contributors such as `requests2` wanting to name-squat `requests3` because `requests2` is now up to version 2.6+, such permitted name-squatting is allowed. However, what if someone else not associated with contributing to `requests2` had squatted on `requests3` and does nothing with it? Recourse or kicking out name-squatters within Pypi.org is not found.
Active Example: https://pypi.org/project/requests2/#description
Name-Squatting Example owned by Active Example (totally okay): https://pypi.org/project/requests3/#description

**Describe the solution you'd like**
Projects that have not code and for the expressed interest of name-squatting and has not been touched for over 6 months should be removed, so that Project name could be made available to more active contributors to Pypi.org. The original owner of the name-squatting project can reclaim the same Project name but only after a waiting period of 30 days.

**Additional context**
Similar request for issue [4003](https://github.com/pypa/warehouse/issues/4003)

**Comment by dwighthubbard** [comment]
Organizations may register packages for their organization namespace so public users don't accidentally create packages that conflict with the packages in their internal private repos.

The packages on the public repos would then be empty, but it doesn't mean that they are unused.

It would be useful to have a way to determine this is the case, vs someone grabbed the name and never used it however.

**Comment by timkpaine** [comment]
name squatter: https://pypi.org/user/suroegin/

**Comment by sloev** [comment]
https://pypi.org/project/cccp/ has been squatted since 2011 with no code and nothing installable:

```
 pip install cccp
Collecting cccp
  Could not find a version that satisfies the requirement cccp (from versions: )
No matching distribution found for cccp
```

i am let down by this since i am currently creating a package for opensource that is called SemiServerSideRendering : SSSR or in Cyrilic CCCP which is a nice name to gain traction.

i have written the maintainer but it does not seem like he has done anything with the namespace in more than 8 years.

**Comment by di** [comment]
Since this issue was first created, [PEP 541](https://www.python.org/dev/peps/pep-0541/) has been accepted and implemented.

Aside from that process, PyPI has no plans to archive, hide or otherwise remove any existing packages.

* If you'd like to acquire a broken/unmaintained/squatted package: [file a PEP 541 request here](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME)
* If you'd like to report a user squatting on a large quantity of package names: [email admin@pypi.org](mailto:admin@pypi.org)
