### ISSUE TITLE
minor: sort keys in `releases` field of json api

### ISSUE THREAD

**Issue by asottile** [pypa/warehouse#4046]
**What's the problem this feature will solve?**

`releases` keys are currently not version / release sorted.

Here's a specific example using `pre-commit`'s versions (note 0.10.x is sorting before 0.2.x):

```console
$ curl -s https://pypi.org/pypi/pre_commit/json | jq '.releases | to_entries | .[].key'
"0.10.0"
"0.10.1"
"0.11.0"
"0.12.0"
...
"0.18.1"
"0.18.2"
"0.18.3"
"0.2.0"
"0.2.1"
"0.2.10"
"0.2.11"
"0.2.2"
...
"0.9.2"
"0.9.3"
"0.9.4"
"1.0.0"
"1.0.1"
"1.1.0"
"1.1.1"
...
"1.8.1"
"1.8.2"
```

**Describe the solution you'd like**

Ideally these would be version-sorted (similar to what is done on the `/simple` page)

**Additional context**

yes, I realize maps _technically_ shouldn't have an ordering -- though it would be much more convenient for my usecase if these were sorted :)

**Comment by di** [comment]
As you said, I'm not sure it really makes sense to attempt to order the mapping (either in Python or in JSON).

A better approach might be to add a new field (perhaps something like `release_ordering`) which provides the the versions for each release in an ordered list.

It might be worth mentioning that if you need to order versions, the `packaging` module provides a canonical way to do it as well: https://packaging.pypa.io/en/latest/version/

**Comment by asottile** [comment]
Yep! See #4049

**Comment by asottile** [comment]
That patch does use `packaging` like suggested.  I think changing the api is a bit out of scope for a cosmetic issue.  It seems according to the code that the ordering _is_ intentional here (I had to modify an existing `orderby` to correct the issue) and that the current output is a bug.  Fortunately, warehouse only targets python3.6+ so orderings of mappings are maintained.  Or do you disagree, notably that an improvement to ordering here is not actually an improvement at all?

I see this issue as almost an identical issue to #2574 (which was considered a bug), just with a different view.

**Comment by di** [comment]
@asottile Ah, sorry for being unclear. I was suggesting that you use the `packaging` module in whatever is consuming this API instead.

The `/simple` page is a bit different because HTML is inherently ordered.

That said I'm not opposed to adding a new field to the API here, but perhaps it would be more reasonable to just expect consumers to do the sorting themselves.

**Comment by asottile** [comment]
Are you opposed to my current patch?  It's clearly sorted _today_ just sorted _wrong_.

**Comment by di** [comment]
@asottile Yes. While most times keys in JSON seem deterministic, there's nothing actually guaranteeing that a given serializer/deserializer maintains that ordering, so attempting to enforce it here and suggesting that consumers trust that ordering doesn't really make sense.

**Comment by asottile** [comment]
There is a guarantee though, warehouse is running python3.6 which has ordered mapping types.

**Comment by dstufft** [comment]
> There is a guarantee though, warehouse is running python3.6 which has ordered mapping types.

While Python has ordered data types, there is no guarantee that the json module is going to retain the ordering of the mapping, or that in the general case whatever is parsing the JSON is going to retain the ordering of the keys in the JSON.

This is an important maintainability question, because while dicts are guaranteed ordered now, since the JSON module doesn't guarantee it will follow that order that means potentially any upgrade to Python, even a point release, may break this functionality (and thus anyone depending on it).

I also believe the patch in question isn't going to work, because our JSON serializer calls the json module with ``sort_keys=True``, In order to get deterministic output from the JSON.

**Comment by asottile** [comment]
Ah yes, `sort_keys=True` would throw this off.

That said, `json` is specced to respect the order of mappings passed so I don't think there's a maintainability issue there: [bpo-6015](https://bugs.python.org/issue6105) / [PEP0372](https://www.python.org/dev/peps/pep-0372/) (^F "json module")

**Comment by asottile** [comment]
while possible, and I think an improvement -- I no longer need this
