### ISSUE TITLE
Request trove classifier: Beer Garden

### ISSUE THREAD

**Issue by loganasherjones** [pypa/warehouse#4110]
Request to add a new Trove classifier. I actually have two classifiers that I would like to add.

## The name of the classifier you would like to add

* `Framework :: Beer Garden`
* `Framework :: Beer Garden :: Plugins`

## Why do you want to add this classifier?

**Justification:** I have new framework called Beer Garden. You can [view the documentation here](https://beer-garden.io/) for a full list of features. One of the main components of Beer Garden are community-driven plugins. As such, we need to build a marketplace to help visualize all of the known plugins. Since we are trying to stay close to python, we would like our plugin developers to be able to publish their plugins to PyPi like normal. However, in order for us to build a marketplace, we will have to be able search PyPi for specific attributes, hence this request.

**Why do the current classifiers not meed your need:** Beer Garden does not fit into any of the current frameworks, and short of forcing users to follow a specific naming convention, or creating my own packaging format, I don't see any way of including searchable metadata in PyPi.

**How many projects do you expect to use this new classifier:** 10 currently, but as the community grows and more plugins exist the number will increase.

**Why do you need more than one?** I'm requesting more than one because it will be helpful to separate Beer Garden the framework from the plugins. So the `Framework :: Beer Garden :: Plugins` tag allows us to separate plugins from the framework itself.

**Comment by jamadden** [comment]
Hi! Thanks for the request. It's been almost a year (apologies for the lack of communication); are you still interested in having classifiers added? 

If so, the PyPI moderators are in the process of developing a few guidelines for the creation of new Framework classifiers. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, I think we're expecting the bar to add new ones to be relatively high. Currently, we're looking at these guidelines:

* New framework classifiers should be created if they are "notable;" and 
* They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that.

As to the other guideline ('immediate use to existing projects'), it's been suggested that 

- Requestors can demonstrate this by providing links to 10 or more existing PyPI projects that will use the classifier; or
- Another way to demonstrate notability would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier.


We're looking for some feedback on this. Does it seem reasonable to you? And if so, are gathering those links and/or comments something you would be able to help with?

**Comment by loganasherjones** [comment]
Hiya! Thanks for the reply. I kinda went out and started making my own marketplace that helps to solve the problem I was having. Perhaps in the long run, I will still need to come back to something like this, but for now, I assume you can go ahead and close this request!
