### ISSUE TITLE
"Framework :: tox" trove classifier not included in filters

### ISSUE THREAD

**Issue by rpkilby** [pypa/warehouse#4111]
**Describe the bug**
`Framework :: tox` is listed as a trove classifier [here](https://pypi.org/pypi?%3Aaction=list_classifiers), but is not included in the "By Framework" search filter. Directly modifying the query string does not return results either.

**Expected behavior**
- `tox` should be listed in the framework search filter.
- Filtering with `Framework :: tox` should return tox-related results.

**To Reproduce**
Go to: https://pypi.org/search/?c=Framework+%3A%3A+tox

> There were no results for 'Framework :: tox' filter

**Comment by di** [comment]
This is because there are no projects using this classifier yet (it is relatively new). We don't show unused classifiers in the search tree.

By the way, you might be interested in using the classifier list at https://pypi.org/classifiers/ instead, it will link directly to the search results for a given classifier.

**Comment by rpkilby** [comment]
Thanks. I saw the classifier in tox's own `setup.py` and assumed it was already in use.

**Comment by di** [comment]
That classifier was [added on April 28th](https://github.com/tox-dev/tox/commit/053dcf5d72f2beea20fcecbc658aef5fe5e5b5b8),  but the [most recent tox release was on April 2nd](https://pypi.org/project/tox/3.0.0/).
