### ISSUE TITLE
Don't block reuploads of a file based solely on the hash

### ISSUE THREAD

**Issue by zooba** [pypa/warehouse#4114]
**What's the problem this feature will solve?**
Because pip resolves wheel platforms by filename, occasionally you want to upload the same wheel under different platforms. For example, a wheel that will only work on Windows (regardless of 32/64-bitness) has to be provided in both `...-win32.whl` and `...-win_amd64.whl` variants.

Warehouse currently uses the contents of the file (apparently?) to check whether a file has already been uploaded. This means you can't upload the same wheel twice under different names.

**Describe the solution you'd like**
(I'd _really_ like better platform resolution in pip, but that doesn't solve the problem of people who haven't/can't upgrade, so...)

I'd like it if you were allowed to upload the same file multiple times under different filenames. Totally happy for it to resolve to the same bytes on the server, provided pip thinks they are distinct.

**Additional context**
See https://pypi.org/project/ptvsd/4.1.1a1/#files for an example package where we have done this.

**Comment by dstufft** [comment]
I think if you’re changing the wheel file name, you should also be changing the metadata inside of the wheel which would change the hash. Is that not what you’re doing? If not is there a reason?

**Comment by zooba** [comment]
That's our workaround, but since we're only building a single wheel (with multiple ABI-tagged extension modules in it) it has to be done manually.

**Comment by dstufft** [comment]
But the platform tags that you’re changing are also part of the wheel metadata. So if you’re changing the file name you should also be updating those files anyways. It the WHEEL file iirc

**Comment by zooba** [comment]
Except the platform really is "multiple platforms" (specifically, it's "either win32 or win_amd64"). No installation tools are able to resolve a dual-purpose tag like this, so we use two files to help them out, but the installed wheel is identical and has no platform.

**Comment by njsmith** [comment]
@zooba In case it's not clear -- what Donald's pointing out is that the platform tag is listed twice: once in the wheel filename, and once in a special metadata file inside the wheel, and the two copies of this metadata are supposed to match. Some tools only look at the filename, so you can get away with having a mismatch -- in particular I think pip currently looks only at the filename. But in the future this might change.

Also, I think you should be able to use a single file with the tag `win32.win_amd64`, where `.` is a special operator in wheel tags that means `or`? See https://www.python.org/dev/peps/pep-0425/#compressed-tag-sets

**Comment by zooba** [comment]
It was clear, but you're right that a compressed tag will work for my current case. Funny how I knew about that for the Python version, but it hadn't clicked that it works for all the parts.

So that deals with my current problem, but I still think Warehouse shouldn't be blocking reuploads of a file based solely on the hash. If there's a good reason then I'm happy to hear it and leave alone, but it seems like an arbitrary and potentially confusing restriction.

**Comment by dstufft** [comment]
The reason is basically to allow content addressable files-- I don't think we're currently using that today, but it leaves it open to do so in the future. Allowing file uploads for the same hash blocks that off completely-- so we could do it, but we'd have to decide we're never going to want that if we do.

**Comment by dstufft** [comment]
FTR it appears your wheels are slightly invalid right now, you have a wheel named ``ptvsd-4.1.1a1-py3-none-win32.whl``, but the internal metadata says ``Tag: py3-none-any``, so that's a mismatch between the two values which should be the same. Potentially pip should start at least warning in this case, if not erroring because the metadata is effectively broken here.

**Comment by zooba** [comment]
How does it block it off? Wouldn't you just be allowing using the hash as the filename? Or are you thinking more of a reverse search where you can map back to the original filename (in which case, why not map back to multiple?)

**Comment by zooba** [comment]
> it appears your wheels are slightly invalid ...

Watch for the next update ;)

**Comment by dstufft** [comment]
Sorry, I missed this last message on this, and yes, content address files would mean you'd be able to locate a file knowing nothing but it's hash. Like I said, I don't know we'd ever actually do that or not, but the current restriction enables that to happen in the future if we ever desired it.

The other reason is that because the internals of the wheel file have to change if you change the tags, that it's likely an error if you're trying to upload a file with the same hash as an existing file-- it likely means you forgot to adjust your tags inside the wheel file too.

Generally I don't feel strongly one way or another about this, but the fact I can't think of a case where you'd actually want to upload the same file under two different filenames that isn't actually a case of one (or both) of the uploaded wheels having incorrect metadata associated with it I'm leaning towards leaving the current restriction in place. Is there a use case you can think of when you'd want to upload two files like this where the wheel files don't have erroneous metadata inside them?

**Comment by brainwane** [comment]
@zooba hey, ping in case you missed Donald's question in the last comment and have time to respond.

**Comment by di** [comment]
Closing this issue as I don't think we have any plans to support this at this time.
