### ISSUE TITLE
Transfer abdonned project PyQRCode - PEP-541

### ISSUE THREAD

**Issue by heuer** [pypa/warehouse#4121]
PyQRCode seems to be unmaintained.

I contributed code two years ago and I like to take over the project since all requests (email and issue reports) to the current owner end up in nothing.

See <https://github.com/mnooner256/pyqrcode/issues/52>
My fork: <https://github.com/heuer/pyqrcode/tree/develop>

My PyPi-Account: heuer

Thanks a lot.

**Comment by ericmjl** [comment]
If appropriate, I would like to record my vote here for @heuer to take over the project. @heuer has been more responsive than the original developer, has been active on the issues tracker, and has developed a new version of the package that is only awaiting a new PyPI release.

**Comment by di** [comment]
@ericmjl The process has been agreed upon in PEP 541, but hasn't been implemented yet.

Right now we are working on adding the necessary admin features to be able to take action on PEP 541 requests, to do so in a fair way to all users, and to be able to organize them in a way that is not incredibly time-consuming for the volunteers who will be responding to them (e.g.: #3231, #4011, #4022).

Since this is an entirely volunteer-driven project, it's not really possible to provide a timeline. I can say that these issues are my current highest priority, when I am able to find the time to work on them.

What you've done so far is exactly the right thing to do, and I'll be happy to address your request once said features are in place.

**Comment by ericmjl** [comment]
@di, thanks for pinging in, and for the clarification! :smile: Also, thanks a ton for the work that you've been doing!

**Comment by mfrasca** [comment]
one more user, supporting the request.  or considering moving away from PyQRCode.

**Comment by yeraydiazdiaz** [comment]
Hello @heuer, I have sent @mnooner256 an email asking to clarify his position regarding this package. Hopefully we will hear from him soon and move this request forwards.

Thank you for your patience while we deal with these issues.

**Comment by yeraydiazdiaz** [comment]
Hello @heuer, @mnooner256 has replied to my email and stated his intention to continue working on PyQRCode, thus no ownership transferral is possible.

At this point I can only suggest creating a fork and publishing a project under a different name.

I will now close this issue. Thank you for your patience.

**Comment by heuer** [comment]
Thanks for your work, @yeraydiazdiaz! 
I am glad that Michael responded and is willing to maintain the project.

**Comment by mfrasca** [comment]
my "confused" statement: because the last commit by the current official maintainer is still 3 years old.

**Comment by ericmjl** [comment]
Yes, this is great news! Thanks for clarifying, and for handling this request!

**Comment by om26er** [comment]
ping @mnooner256, is there an update on your plans, do you still plan to continue development of PyQRCode or maybe are willing to transfer maintainership to people interested ?

**Comment by di** [comment]
Hi folks, please have this discussion on the projects tracker instead. Thanks.
