### ISSUE TITLE
Trove Classifier Request: django cms

### ISSUE THREAD

**Issue by kinkerl** [pypa/warehouse#4158]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: Django CMS`
* `Framework :: Django CMS :: 3.4` which is an LTS
* `Framework :: Django CMS :: 3.5` latest
* `Framework :: Django CMS :: 3.6` upcoming 

## Why do you want to add this classifier?
django cms has a plugin ecosystem and it would make it easier for plugin creators to lable the compatibilities and for users to see compatible plugins.

Thanks!

**Comment by jamadden** [comment]
Hi! Thanks for the request. It's been almost a year (apologies for the lack of communication); are you still interested in having classifiers added? 

If so, the PyPI moderators are in the process of developing a few guidelines for the creation of new Framework classifiers. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, I think we're expecting the bar to add new ones to be relatively high. Currently, we're looking at these guidelines:

* New framework classifiers should be created if they are "notable;" and 
* They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that.

As to the other guideline ('immediate use to existing projects'), it's been suggested that 

- Requestors can demonstrate this by providing links to 10 or more existing PyPI projects that will use the classifier; or
- Another way to demonstrate notability would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier.


We're looking for some feedback on this. Does it seem reasonable to you? And if so, are gathering those links and/or comments something you would be able to help with?

**Comment by FinalAngel** [comment]
Hello @jaystino, thank you very much for your feedback!

We are still very interested in having these classifiers added as django CMS is still one of the largest packages used that is based on Django. We also see other similar CMS present and would like to improve the experience for our users there by adding the necessary classifiers to our addons-ecosystem.

We have several addons available where we can add the classifiers immediately (and would also add this in our best practices guidelines). We're not anticipating these additions as "future uses".

The process you outline is understandable and makes sense to us and we fully support the approach 👍

Let us know how to proceed 🎉

**Comment by jamadden** [comment]
> Let us know how to proceed

Thanks for your interest. We're working a similar process on a few other classifier requests and the responses to https://github.com/pypa/warehouse/issues/5156 and https://github.com/pypa/warehouse/issues/5553 have been very helpful, so something along those lines would be great.

**Comment by jamadden** [comment]
Thanks for your response. I spot-checked some of those packages and they are published on PyPI and appear to be maintained. Many of them currently use `Framework :: Django` classifiers. Are you anticipating keeping that classifier and adding this one as well, or replacing that classifier? Would a sub-classifier (`Framework :: Django :: CMS`) be appropriate instead?

**Comment by FinalAngel** [comment]
@jamadden we would keep the Django classifiers and add django CMS separately as for example here:
https://github.com/divio/aldryn-addons/blob/master/setup.py#L31-L35

As Django version support can vary depending on the django CMS version. It's just a bit confusing as the CMS is called "django CMS".

**Comment by jamadden** [comment]
Thanks for your responses, that makes sense! With the evidence given here and at https://www.django-cms.org/en/, to my mind, it looks like the proposed guidelines have been met, and I would suggest adding the classifier.

I'd like to allow a few days to give the other @pypa/pypi-moderators a chance to review this before taking action. (If there's no other motion on this by next week, feel free to ping me.)

**Comment by FinalAngel** [comment]
Thank you very much @jamadden 👍

**Comment by jamadden** [comment]
The four requested classifiers have been added to pypi.org

**Comment by FinalAngel** [comment]
thank you @jamadden !

**Comment by FinalAngel** [comment]
@jamadden would it also be possible to add:

``'Framework :: Django CMS :: 3.7',``

we plan to release it in the next couple of months :)

**Comment by ewdurbin** [comment]
@FinalAngel: Done

**Comment by FinalAngel** [comment]
thank you @ewdurbin !

**Comment by FinalAngel** [comment]
@ewdurbin would you be able to add:

```
'Framework :: Django CMS :: 3.7',
```

we're preparing the release in the next coming weeks :)

**Comment by ewdurbin** [comment]
@FinalAngel there's a new process for trove classifier requests, see https://pypi.org/help/#new-classifier and https://github.com/pypa/trove-classifiers/ (you could potentially open your own PR there to add it).

Also I think you meant to request `'Framework :: Django CMS :: 3.8'` :)

**Comment by FinalAngel** [comment]
Ah perfect @ewdurbin, thank you very much. Will follow the process as mentioned!
