### ISSUE TITLE
Claim Ownership of pySMART Package

### ISSUE THREAD

**Issue by draik** [pypa/warehouse#4214]
**Describe the bug**
This has not been maintained since June 11, 2015 (3Y 10D as of today)

**Expected behavior**
Cannot push updates to 0.4 (my changes) to the main package. Previous maintainer has not been active, nor responded to my email.

**To Reproduce**
https://pypi.org/project/pySMART/

**Additional context**
Following PEP-541 and trying to get maintainer control over the package.

**Comment by mth309** [comment]
Hi draik,
I'm the original author of the pySMART tool and you're right, I've been horribly lax at keeping it up to date on PyPI.  A few years ago I made an agreement with the team that builds FreeNAS allowing them to use the code under LGPL license (instead of the original GPL I'd published on PyPI), and they've been hosting it on their github and making great improvements ever since.  

I've been contacted by many people over those years offering to work on pySMART, and I've been pointing them all to the FreeNAS github since they have the latest and greatest code.  Here's the link:  https://github.com/freenas/py-SMART.  Unfortunately, I'd just never gotten around to updating the version in PyPI.  It sounds like I must have overlooked an email from you so I'd like to apologize for that,  I certainly did not mean to ignore any offer of help that it sounds like you sent.

In any case, after being contacted by the PyPI folks as a result of your claim, I decided it was time to grab the latest code from the FreeNAS github and package it up for PyPI.  This afternoon I did just that, so you should now see a new and improved (and likely "final"?) version 1.0 of pySMART at PyPI.  The readme of the new version speaks about and links to the FreeNAS github as well, so in the future if PyPI gets out of data again people will know where to look for the latest code.  If you'd like to build upon this version I'd invite you to participate at the FreeNAS github, or if you had something else in mind reach out to me directly and maybe we can work something out.  Thank you for your interest in this project!

**Comment by yeraydiazdiaz** [comment]
@mth309 thank you clarifying the situation.
