### ISSUE TITLE
PyPI sends emails with unicode in header

### ISSUE THREAD

**Issue by nhoening** [pypa/warehouse#4273]
**Describe the bug**

I created a new account on pypi.org, but I am not receiving any email verification link by email - not after accouunt creation and also not after resending the verification link (even if pypi.org claims "Verification email for nicolas@seita.nl resent").

test.pypi.org works for me, using the same account name and email address. I deleted and recreated the account on both pypi.org and test.pypi.org - same behaviour (well, the initial email did sometimes not arrive on test.pypi.org, but the the verification resend always arrived right away).

**Expected behavior**

I should get an email token after registering, and also when I resend the verification mail from the account page. I know it might take a while, but I am experiencing this since Friday.

**To Reproduce**

Register on pypi.org, wait for email. Resend the verification email from the account settings page, wait again.

**My Platform**

Firefox 52

**Comment by ewdurbin** [comment]
Hello @nhoening! PyPI received bounces for the address you specified which led to it being placed on the suppression list.

I've removed it from the suppression list, can you try again?

**Comment by nhoening** [comment]
Yes, that did it. Thanks for the quick help!

**Comment by ewdurbin** [comment]
@nhoening in taking a closer look, @di noticed that your domain's mail transfer agent was rejecting the `To` field due to the ö in your last name:

```
emailAddress: Nicolas Höning <nicolas@seita.nl>
diagnosticCode: smtp; 550 To contains invalid characters.
```

Warehouse constructs `To` headers using:

https://github.com/pypa/warehouse/blob/40fbc32fef7c7ffe41cd18f3f8951578555db1aa/warehouse/email/__init__.py#L25-L33

So it appears that either:
  1) Your mail transfer agent no supports unicode
  2) You temporarily changed your profile display name, as it now contains the ö character

Can you confirm if either of these occurred? I may be imagining things, but I briefly recall seeing the non-unicode "variant" of your name in your profile when taking a look initially.

My concern is that future email may not be deliverable.

**Comment by nhoening** [comment]
I can confirm that I tried to rule out the umlaut as a problem. I had used it initially and after a day or two, I went on testing without the umlaut. test.pypi.org also did not work initially, until I removed it, but I thought it must be a glitch. It makes more sense now.

So, either I should talk to my email provider, or you guys decide that [RFC-5322 Article 2.2](https://tools.ietf.org/html/rfc5322#section-2.22) (see below) applies to this problem (I wouldn't be expert enough to tell) and maybe encode header text.

> Header fields are lines beginning with a field name, followed by a
>    colon (":"), followed by a field body, and terminated by CRLF.  A
>    field name MUST be composed of printable US-ASCII characters (i.e.,
>    characters that have values between 33 and 126, inclusive), except
>    colon.  A field body may be composed of printable US-ASCII characters
>    as well as the space (SP, ASCII value 32) and horizontal tab (HTAB,
>    ASCII value 9) characters (together known as the white space
>    characters, WSP).

**Comment by di** [comment]
Reopening this because I think it's something that can be fixed on our end.
