### ISSUE TITLE
direct link to .egg package

### ISSUE THREAD

**Issue by blshkv** [pypa/warehouse#4304]
I'm packaging a python egg file for a linux distribution and it requires me to specify a directly link to a file. Currently, it is possible to request for it via API, however this feature not available for me.

The closest what I found is the following URL:
https://pypi.org/simple/

So if I need to get a link for ```frida-12.0.3-py3.6-linux-x86_64.egg``` file for example, I need to visit
the URL ```https://pypi.org/simple/frida/```, search for this filename and copy the link.

However, I cannot automate it. It would be more useful if you could redirect the following URL (in my example): https://pypi.org/simple/frida/frida-12.0.3-py3.6-linux-x86_64.egg to the direct link.

Thank you in advance.

**Comment by ewdurbin** [comment]
@blshkv see https://warehouse.readthedocs.io/api-reference/integration-guide/#querying-pypi-for-package-urls for more information on how you might obtain the direct link.

The URL you want a redirect for would be:

`https://files.pythonhosted.org/packages/3.6/f/frida/frida-12.0.3-py3.6-linux-x86_64.egg`

This will return an HTTP redirect to `https://files.pythonhosted.org/packages/73/d8/ffeed9316a2e73ec1920c02bb1bfb37db62c6b56e83b5d3d0e6c17ae63b2/frida-12.0.3-py3.6-linux-x86_64.egg`

**Comment by blshkv** [comment]
Perfect, thank you for pointing that out!

**Comment by blshkv** [comment]
Hi, can you help me find a similar link for .whl  https://pypi.org/simple/orjson/ please?
I tried few schemes and unable to figure it out :\

**Comment by ewjoachim** [comment]
As explained in https://warehouse.readthedocs.io/api-reference/json.html, you can load https://pypi.org/pypi/orjson/json. You'll find the link in the payload, depending on if you want a stable or cutting edge version, a wheel or a tar.gz etc.

**Comment by blshkv** [comment]
that doesn't work well for me, unfortunately. I'm trying to package a package for Gentoo, and need a universal URL, similar to the one which you provided before: ```https://files.pythonhosted.org/packages/3.6/f/frida/frida-12.0.3-py3.6-linux-x86_64.egg``` which would redirect to a next location. If not, I would need to write a separate eclass to extract it, but parsing JSON in bash might not be that easy.

**Comment by ewjoachim** [comment]
> parsing JSON in bash might not be that easy

If you can use [jq](https://stedolan.github.io/jq/manual/), it's usually not that bad.

Otherwise, I note that it's quite rare for a project in 2021 to still expose egg files, the standard is wheel.

The URL you're looking for is something around:
`https://files.pythonhosted.org/packages/cp36/o/orjson/orjson-3.5.4-cp36-cp36m-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl`

The part you had wrong was probably the "python version". One way to find the information that it needs to be `cp36` and not `3.6` or something: starting from @ewdurbin 's advice that it was using the conveyor service, search for its code source: https://github.com/pypa/conveyor/blob/master/conveyor/views.py and see that it looks for the matching `python_version` field in the JSON API, so looking at the JSON API, orjson's `python_version` fields looks like `cp36` and the rest is following the doc :)

**Comment by blshkv** [comment]
That works. Thanks a lot!

**Comment by blshkv** [comment]
hm.. what would be the url for https://pypi.org/pypi/semgrep/json please?

**Comment by ewjoachim** [comment]
I've outlined the exact method for figuring it out above.

`https://files.pythonhosted.org/packages/cp36.cp37.cp38.cp39.py36.py37.py38.py39/s/semgrep/semgrep-0.57.0-cp36.cp37.cp38.cp39.py36.py37.py38.py39-none-any.whl`

You're welcome to request help again if you find a package for which the method above doesn't work, but if it does, please follow it. Otherwise, I might not be a very reliable human API (my SLA are probably aweful).

**Comment by blshkv** [comment]
Didn't expect it that long, but I figured it out at the end. Thanks a lot!
