### ISSUE TITLE
Feature request: How many correctly answered Stack Overflow questions are there for this module?

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#4408]
Feature request from user research.  Not sure if this is possible, but it sounds interesting!

**Comment by evemorgen** [comment]
Any thoughts about that? Linked PR provides POC implementation of this, which works decent for well known modules

**Comment by di** [comment]
I'm concerned about false positives here: with Github, the maintainer is explicitly including a Github link, essentially confirming that the repo corresponds to the project.

However here, the maintainer has no control over the behavior, and the linked tag might actually be wrong (e.g. the project https://pypi.org/project/go/ would link to questions and answers about https://stackoverflow.com/questions/tagged/go)

Instead, maybe it would make sense to do what we do for Github: if the maintainer has included a link to a StackOverflow tag in `project_urls`, then we show these statistics, otherwise we don't.

**Comment by evemorgen** [comment]
I had similar feelings about false-positives, however, I'm also concerned that if it won't happen automagically, this feature would receive very little or no usage at all. 

Since providing Github link seems natural, about  StackOverflow tags, I'm not so sure. 

All in all, I agree that providing a link in `project_urls` is a better idea, will try do

**Comment by di** [comment]
After giving this some thought, I'm going to close this because I think it should be opt-in and I think the usage would be quite low.
