### ISSUE TITLE
API list_packages() really needed?

### ISSUE THREAD

**Issue by guettli** [pypa/warehouse#462]
I was interested in the API of warehose.

I am unsure if list_packages() is really a good idea.

If it exist, it will be used. If I compare this to android google play store ... there are many packages.

What does the client do with a list of several thousand packages? I guess the client does filter the list. I think it is better to use the search api in the first place.

Can you understand my fear?

Maybe it is better to not provide this method at all?

**Comment by dstufft** [comment]
It's currently needed for the mirroring infrastructure.

I'm not sure I understand what the fear is though, if a client doesn't want a list of all of the projects they just don't need to call the API. If they want a list of all of them they can call this API method. The names of the projects are not secret so there's no data exposure risks.

Can you explain what your worry is with this API method?

**Comment by guettli** [comment]
I don't know the internals of pip and the pypi server. But I somehow don't like that I can install `django` and a package called `Django` gets installed.

Both words are not equal. One has a capital "D"

Some magic guessing happens somewhere. I guess that naive clients will download all package names and then try do some guessing to find the matching packages.
It is just a fear. It is not very important.

list_packages() gets used for mirroring? Interesting. How does mirroring work?

**Comment by dstufft** [comment]
First thing is there is a difference between the name of the thing you ``import`` and the name of the thing on PyPI (aka what you ``pip install``). They do not have to match.

The name on PyPI is case insensitive (among a few other normalizations), this is what makes it so you can do ``pip install django`` and get "Django" installed. Nobody can register both "django" and "Django" because PyPI treats them as the exact same thing (and so does pip). pip doesn't actually need to do much special, all that handling is really done on PyPI itself.

When starting a mirror from scratch, mirroring works by getting a list of all the packages from ``list_packages()`` and then fetches the data for each individual package.

I'm going to close this, I think that this API method is fine.
