### ISSUE TITLE
"400 Client Error: File already exists." on similarly-named files

### ISSUE THREAD

**Issue by pabloem** [pypa/warehouse#4695]
**Describe the bug**
I uploaded artifacts with a wrong version (`projectname-2.6.0.rc2-tags.whl`). The `rc2` was left from release candidate creation.
When I uploaded these artifacts, they got correctly put in the 2.6.0 version, but won't be chosen by pip on installation, instead doing a source install.
I corrected the issue with the filename, so now artifacts are `projectname-2.6.0-tags.whl`, but when I try to upload with twine, I receive a `HTTPError: 400 Client Error: File already exists.`.

This feels like a bug in PyPi? Or any suggestions for a workaround?

**Expected behavior**
I'd expect to be able to upload the artifact with different file name, even if the version already exists.

**To Reproduce**

**My Platform**
Operating system: `Linux Debian 4.8 x86_64`
Version of python:` 2.7.13`
Version of twine:
```
twine version 1.11.0 (pkginfo: 1.4.2, requests: 2.19.1, setuptools: 40.2.0,
requests-toolbelt: 0.8.0, tqdm: 4.25.0)
```

**Additional context**
[Release with issues](https://pypi.org/project/apache-beam/2.6.0/#files)

**Comment by pabloem** [comment]
What seems to be going on is that PyPi gets version and environment information from the metadata that is packaged in the wheel (where version is 2.6.0). - pip seems to get the version information from the file name (here, the version is 2.6.0.rc2).

Is there something that can be done to work around this?

**Comment by di** [comment]
This is intentional: PyPI is comparing the hash of your file with previously uploaded files. Usually this happens when a user is trying to upload an existing built distribution that has been renamed. Since installers like `pip` assume the filename accurately represents what's inside the distribution, this often can produce issues where a built distribution _looks_ like it's compatible, but isn't once it's installed.

In this case, I would expect that changing the version from `2.6.0.rc2` to `2.6.0` and regenerating the wheels would produce a file with a different hash, as the version number is stored within the metadata of the wheel. Can you confirm that you've indeed rebuilt the wheel after updating the version?

**Comment by pabloem** [comment]
I have not rebuilt the wheel. I had just renamed it. I'll try rebuilding it. Thanks a lot!

**Comment by di** [comment]
Sorry, replied before I saw your second comment, I see what's happening now.

I think if you made a trivial change to the project's source, causing the built distributions to have new hashes, you should be able to upload them to the same 2.6.0 release with the correct filenames, and then delete the `.rc2` files.

**Comment by pabloem** [comment]
Thank you.
