### ISSUE TITLE
Not receiving Test PyPi verification emails

### ISSUE THREAD

**Issue by vanbenschoten** [pypa/warehouse#4704]
I'm attempting to register on Test PyPi as the first step for publishing a package, but I'm not receiving the verification e-mails (and hence can't upload via twine). I've tried different e-mail addresses, but still no luck.

**Comment by ewdurbin** [comment]
hello @vanbenschoten what is your username on test.pypi.org?

**Comment by vanbenschoten** [comment]
vanbenschoten

**Comment by ewdurbin** [comment]
@vanbenschoten looks like the worker locked up for testpypi (we only run 1 rather than the 3+ we run for production).

This was causing emails not to send since ~12:34 UTC today. You should receive all attempted verification emails soon.

It's resolved now and I'm going to ensure we would have at least detected this in production, and ensure that we detect it for test.pypi.org moving forward.

**Comment by vanbenschoten** [comment]
Thanks!
