### ISSUE TITLE
Missing keys from the legacy JSON api

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#481]
We are missing some keys from the legacy JSON API, in particular I believe we're missing `requires_dist`.

**Comment by di** [comment]
Here's the keys that are present in the legacy API that aren't given by Warehouse:

* `info._pypi_hidden`
* `info._pypi_ordering`
* `info.cheesecake_code_kwallitee_id`
* `info.cheesecake_documentation_id`
* `info.cheesecake_installability_id`

Here are fields that have been added in Warehouse:
* `releases.<version>.digests.md5`
* `releases.<version>.digests.sha256`

Here are fields that seem to have been changed:
* `info.package_url` is `info.project_url` in Warehouse

Specifically, `info.requires_dist` is not missing -- it's being included here: https://github.com/pypa/warehouse/tree/0bb7fed7879e5930e9a3fc299933fb969298136d/warehouse/legacy/api/json.py#L171

These changes all seem OK and/or expected to me (although I'm a little curious about `package_url` vs `project_url`, but I'm guessing this was intentional) so I think this might be a non-issue?

**Comment by dstufft** [comment]
Looks like I probably fixed this in https://github.com/pypa/warehouse/pull/2140 and then just forgot to close this issue (or I wasn't sure if it was the only field left... not sure).
