### ISSUE TITLE
Access to the sanic package on PyPI 

### ISSUE THREAD

**Issue by ahopkins** [pypa/warehouse#4832]
I am trying to get access to the [sanic package](https://pypi.org/project/Sanic/) on PyPI.

Up until a few weeks ago @channelcat had maintained the package alone. He decided to move the [GitHub repo](https://github.com/huge-success/sanic) to an organization and added some [more maintainers](https://github.com/orgs/huge-success/people). The PyPI repo has not been moved so no one has access and we have not heard from him any more.

We would like to get a release out.

Here is my account on PyPI: https://pypi.org/user/brewmaster/

In addition to the sanic repo, the community organization also maintains the sanic-openapi: https://pypi.org/project/sanic-openapi/

Can someone assist me in how we can get access to these two packages?

**Comment by ewdurbin** [comment]
Hi @ahopkins! The easiest way for this to move forward would be for @channelcat to transfer ownership to your PyPI user so that you can then add additional maintainers and owners from the new organization.

If @channelcat is unavailable or unresponsive, I see the following facts:
  - The current homepage URL for the sanic package 
http://github.com/channelcat/sanic, _does_ forward to the repository at 
https://github.com/huge-success/sanic which indicates an intentional migration by @channelcat.
  - Maintenance of the codebase appears to be occurring in the new repository, including activity from @ahopkins.

I think given the following we should be OK to transfer the project ownership:
  - A confirmation from another active maintainer of the new org (@ashleysommer, @yunstanford, @vltr, or @seemethere) that transferring to the brewmaster user on PyPI is 👍.

**Comment by ewdurbin** [comment]
@dstufft @di do you have any other stipulations?

**Comment by di** [comment]
I've reached out to @channelcat for confirmation. If they don't respond in a timely fashion, I'm OK with transferring this project to you, as it seems that by transferring the Github repo, they intended for others to be able to maintain the project. Preferably we'd add some other owners of the project in addition to yourself.

**Comment by di** [comment]
@ewdurbin Sounds like we're on the same page 😂

**Comment by seemethere** [comment]
You don't actually need access to the pypi account to do releases. Just tag a release on GitHub and it should automatically post it up to the pypi account.

**Comment by seemethere** [comment]
Is there a concept of organizations on pypi? Would like to move ownership of this repository to an organization similar to what we have here on GitHub.

**Comment by ewdurbin** [comment]
@seemethere not currently, that is being tracked in #201

**Comment by vltr** [comment]
@ewdurbin @di we are working very hard to maintain Sanic up and running, not only with code but creating a community centric project with more immersion from developers around the world.

**Comment by ashleysommer** [comment]
+1 from me for transfer of the pypi access for the Sanic project to brewmaster.

**Comment by ahopkins** [comment]
@seemethere There is not, but there can be multiple "contributors" on pypi.

@di Thanks. I hope @channelcat does get back. This is the last communication I have had from him:

https://groups.google.com/d/msg/sanic-dev/WXbBxNo7Zek/UWisOI28BgAJ

**Comment by ahopkins** [comment]
@di Just curious ... how long is a "timely fashion"?

**Comment by di** [comment]
@ahopkins I've added you as Owner of `sanic` and `sanic-openai`. Please make sure to add at least one other maintainer as an owner so this is less likely to happen again.

**Comment by ahopkins** [comment]
Thank you. I plan on it.
