### ISSUE TITLE
How does warehouse store depedencies?

### ISSUE THREAD

**Issue by guettli** [pypa/warehouse#491]
If a package has `install_requires=['foo>=1.2']` in its `setup.py` how does warehouse store this information?

Does it store this in the database?

I tried to find the database schema, but I am not familiar with sqlalchemy (only django ORM up to now).

My use case: dependency resolving without full download.

**Comment by dstufft** [comment]
It doesn't *generally* store ``install_requires`` but that's mostly because setuptools doesn't send that information. That data hasn't been mapped into the SQLAlchemy ORM yet, though the file upload branch I'm working on does that. The table is https://github.com/pypa/warehouse/blob/54c67bab2b150acad1267d4d0a4b32426adaa62d/warehouse/legacy/tables.py#L471-L485

**Comment by guettli** [comment]
What is "kind"? Look like a black magic number to me :-)

**Comment by domenkozar** [comment]
This is why we last for PEP426.

**Comment by guettli** [comment]
According to the PEP there are several kinds of dependencies: https://www.python.org/dev/peps/pep-0426/#support-for-different-kinds-of-dependencies

**Comment by dstufft** [comment]
I've mapped these into the ORM with an enum for the different types. I'm going to go ahead and close this issue since there's notthing really actionable here.
