### ISSUE TITLE
Request trove classifier Framework :: BEAT

### ISSUE THREAD

**Issue by anjos** [pypa/warehouse#5156]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: BEAT`

## Why do you want to add this classifier?

BEAT is a framework for describing experiments in AI (machine learning).  It is written in Python and is composed of several packages, including a web-based component (live here: https://www.beat-eu.org/platform/) besides around ~20-30 other packages (https://gitlab.idiap.ch/beat) that ensure various bits of functionality.  We're currently working on extensions to this framework for various tasks in AI and we'd like to label them correctly in PyPI to keep track of development.

**Comment by jamadden** [comment]
Hi! Thanks for the request. It's been several months (apologies for the lack of communication); are you still interested in having classifiers added? 

If so, the PyPI moderators are in the process of developing a few guidelines for the creation of new Framework classifiers. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, I think we're expecting the bar to add new ones to be relatively high. Currently, we're looking at these guidelines:

* New framework classifiers should be created if they are "notable;" and 
* They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that.

As to the other guideline ('immediate use to existing projects'), it's been suggested that 

- Requestors can demonstrate this by providing links to 10 or more *existing PyPI projects* that will use the classifier; or
- Another way to demonstrate notability would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier.

We're looking for some feedback on this. Does it seem reasonable to you? And if so, are gathering those links and/or comments something you would be able to help with?

**Comment by anjos** [comment]
Thx for your feedback.  Hopefully, we can do a mix of both?

PyPI projects that are there, currently:

* https://pypi.org/project/beat.backend.python/ (BSD)
* https://pypi.org/project/beat.core/ (BSD)
* https://pypi.org/project/beat.cmdline/ (BSD)
* https://pypi.org/project/beat.editor/ (BSD)
* https://gitlab.idiap.ch/beat/beat.web/ (AGPLv3) - currently not on PyPI, but will be distributed there as well

We have other projects in the pipe.  Will ask colleagues to drop a message here.

**Comment by tiagofrepereira2012** [comment]
Hi guys,

I'm a developer of one of the BEAT components and I do confirm I'll be using the new trove classifier.

**Comment by 183amir** [comment]
I'm a developer of the BEAT framework as well and can confirm I'll be using the new trove classifier. Thank you.

**Comment by smarcel** [comment]
I'm a developer of a BEAT framework component and confirm I'll be using the new trove classifier as soon as it is available in there?

**Comment by sgaist** [comment]
Hi, I am the current maintainer of the BEAT project and I can confirm the use of the trove classifier. 

On an additional note, the beat.backend.python package is also used in various Docker images (to be published) for execution and remote communication.

**Comment by zmostaani** [comment]
Hi,

I'm a developer of BEAT framework as well and I'll be using the trove classifier as soon as it is available.

Thank you.

**Comment by jdiefen** [comment]
Same here - 
I'm a developer of a BEAT framework component and confirm I'll be using the new trove classifier as soon as it is available

**Comment by neodark** [comment]
I'm also a developer of a BEAT framework component and confirm as the other have done above that I'll be using the new trove classifier when available. Thanks!

**Comment by anjos** [comment]
@jamadden: please let us know if the above information is enough so that this request can proceed.

**Comment by jamadden** [comment]
Thanks for your responses, everyone! With the evidence provided, to my mind, it looks like the proposed guidelines have been met, and I would suggest adding the classifier.

I'd like to allow a few days to give the other @pypa/pypi-moderators a chance to review this before taking action. (If there's no other motion on this by next week, feel free to ping me.)

**Comment by ewdurbin** [comment]
@jamadden I'm +1 on adding this classfier

**Comment by jamadden** [comment]
`Framework :: BEAT` has been added to pypi.org

**Comment by sgaist** [comment]
Thank you very much

**Comment by anjos** [comment]
Awesome! Thx.
