### ISSUE TITLE
Repo should validate non-compliant module structure (e.g., patch-1.16)

### ISSUE THREAD

**Issue by boxsmiley** [pypa/warehouse#5183]
**Describe the bug**
pypi.org allows upload and index of packages that are not compliant with the python spec.  The spec requires that a folder be at the top level of the module that contains PKG-INFO and the implementation.   

**Expected behavior**
If a module doesn't have a top-level folder inside it that contains the PKG-INFO and implementation, it should not pass validation.  

**To Reproduce**
Examine patch-1.16.   It has PKG-INFO at the top level and doesn't contain a folder.  

**My Platform**
Affects all.  

**Additional context**
Here is how patch is:
![should_be](https://user-images.githubusercontent.com/14824671/49820042-b791b200-fd2b-11e8-8362-568aea676932.png)

Here is how it should be:
![is](https://user-images.githubusercontent.com/14824671/49820038-b52f5800-fd2b-11e8-9230-6f40d6c015fe.png)

**Comment by di** [comment]
Can you give us a link to the specification you're referring to?

**Comment by boxsmiley** [comment]
Here is the spec I was thinking of:  https://www.python.org/dev/peps/pep-0314/

Upon re-reading, it is possible that this is just convention and is not explicitly required by the spec.  

This originally came up because JFrog's python repo would not correctly index this particular module.  I told them that they had a bug because pypa has no problem with it.  They told me that they believed that this module was not in compliance with the spec.

**Comment by di** [comment]
That specification is just for the metadata, i.e. what is contained in the `PKG-INFO` file, it doesn't consider what else can be included (or not included) in a distribution.

In fact, it's totally valid (but not very useful) to have a package that is _only_ this file. I think the issue here lies with JFrog's implementation instead, I'd suggest you open an issue in their tracker instead.

Given that, I'm going to close this issue, but feel free to add more details if necessary.

**Comment by boxsmiley** [comment]
Ok. Thanks.
