### ISSUE TITLE
Markdown Images are not rendered in pypi

### ISSUE THREAD

**Issue by kirankotari** [pypa/warehouse#5246]
**Describe the bug**
Images are not rendered in pypi from README.md file
Package link: [https://pypi.org/project/shconfparser](https://pypi.org/project/shconfparser)

*Image Size:
sh_cdp_neighbour.png - 184 KB
sh_run.png - 855 KB*

**Expected behavior**
Images need to be rendered, as shown in the following link
Github link: [https://github.com/kirankotari/shconfparser](https://github.com/kirankotari/shconfparser)

**To Reproduce**
Image from a link:
*`![show run to tree structure](https://github.com/kirankotari/shconfparser/blob/master/asserts/img/sh_run.png)`*

Testing using image from package path:
*`![show run to tree structure](/asserts/img/sh_run.png)`*

**My Platform**
Checked in Chrome 71 and IE 11

**Additional context**
The warehouse [image link](https://warehouse-camo.cmh1.psfhosted.org/c2db686691289f829fa3a3af93807591a924795f/68747470733a2f2f6769746875622e636f6d2f6b6972616e6b6f746172692f7368636f6e667061727365722f626c6f622f6d61737465722f617373657274732f696d672f73685f72756e2e706e67) says `Not Found`

**Comment by kirankotari** [comment]
Thanks @ewdurbin

**Comment by Borda** [comment]
Hello, we have some problem with rendering GitHub status badges - https://pypi.org/project/pytorch-lightning/1.0.8/
so we tried to download all badges locally and add then to the package distribution on the fly (when the package is created) but this approach does not work as readme cannot take local images from the package - https://stackoverflow.com/a/46875147/4521646
so is there a way or suggestion on how to upload the images/badges to a public domain and later refer in the readme? Moreover, are these referred imaged downloaded by PyPI or what happens if the image changes over time or it is removed?

**Comment by di** [comment]
Hi @Borda - many users upload images to GitHub or another image hosting service (like imgur) or host the images on their own domain. PyPI will link directly to the image, so if the hosted image is changed or removed, it will change on PyPI as well.
