### ISSUE TITLE
Trove Classifier Request (Framework :: AiiDA)

### ISSUE THREAD

**Issue by giovannipizzi** [pypa/warehouse#5553]
Request to add a new Trove classifier.

## The name of the classifier you would like to add
* `Framework :: AiiDA`

## Why do you want to add this classifier?
The [AiiDA framework](http://www.aiida.net) has been developed since 2013 ([GitHub page](https://github.com/aiidateam/aiida_core); scientific publication: [[journal]](http://dx.doi.org/10.1016/j.commatsci.2015.09.013), [[arXiv, open access]](https://arxiv.org/abs/1504.01163)). AiiDA helps researchers to manage complex workflows in computational materials science and beyond and make them fully reproducible. It automates the procedure of submitting, retrieving and parsing calculation on high-performance supercomputers (HPC) and stores automatically the provenance (i.e., the "history") of the simulations in the form of a directed acyclic graph. 

In the past two years, together with collaborators we've been extending the support of AiiDA (via plugins) to over 30 different simulation packages, covering over 60 different code executables and this number keeps increasing steadily over time.

At the moment, we are collecting all these plugins in our [custom AiiDA plugin registry](https://aiidateam.github.io/aiida-registry/) but we believe that a Trove classifier for the AiiDA framework would be extremely beneficial to simplify searching for the AiiDA plugins.

**Comment by jamadden** [comment]
Hi! Thanks for the well written request. The PyPI moderators are in the process of developing a few guidelines for the creation of new Framework classifiers. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, I think we're expecting the bar to add new ones to be relatively high. Currently, we're looking at these guidelines:

* New framework classifiers should be created if they are "notable;" and 
* They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that; the information you've already provided goes a long way towards satisfying that.

As to the other guideline ('immediate use to existing projects'), it's been suggested that 

- Requestors can demonstrate this by providing links to 10 or more **existing PyPI projects** that will use the classifier; or
- Another way to demonstrate notability would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier.

We're looking for some feedback on this. Does it seem reasonable to you? And if so, are gathering those links and/or comments something you would be able to help with?

**Comment by giovannipizzi** [comment]
Dear Jason,
thanks a lot for the detailed reply.

On "notability", as you mentioned, we've already provided (hopefully) enough information. Let me also add that the scientific paper has been already cited over 80 times.

For the second request, here is a non-exhaustive list of some of the plugins using AiiDA that could benefit of the new Trove classifier. I put name with link to the PyPI project, as well as the GitHub mention of (one of) the PyPI project maintainers of the package. In this way, they can confirm with a comment that they support this request. Don't hesitate to let us know if you need more PyPI projects (we suggest the convention that all AiiDA plugins start their package name with `aiida-`, so if you [look for `aiida` on PyPI](https://pypi.org/search/?q=aiida) you find more of them).

1. [aiida-vasp](https://pypi.org/project/aiida-vasp/) @espenfl
2. [aiida-cp2k](https://pypi.org/project/aiida-cp2k/) @yakutovicha
3. [aiida-quantuemespresso](https://pypi.org/project/aiida-quantumespresso/) @sphuber
4. [aiida-zeopp](https://pypi.org/project/aiida-zeopp/) @ltalirz
5. [aiida-castep](https://pypi.org/project/aiida-castep/) @zhubonan
6. [aiida-crystal17](https://pypi.org/project/aiida-crystal17/) @chrisjsewell
7. [aiida-siesta](https://pypi.org/project/aiida-siesta/) @vdikan
8. [aiida-yambo](https://pypi.org/project/aiida-yambo/) @AntimoMarrazzo
9. [aiida-fleur](https://pypi.org/project/aiida-fleur/) @broeder-j
10. [aiida-kkr](https://pypi.org/project/aiida-kkr/) @PhilippRue
11. [aiida-tbmodels](https://pypi.org/project/aiida-tbmodels/) @greschd

I hope that this information, together with the supporting comments by the maintainers mentioned above, will help you make your decision. Thanks a lot in advance!

**Comment by ltalirz** [comment]
maintainer of [aiida-zeopp](https://pypi.org/project/aiida-zeopp/) here - looking forward to using the classifier!

**Comment by sphuber** [comment]
Thumbs up from me for the [aiida-quantumespresso](https://github.com/aiidateam/aiida-quantumespresso) and [aiida-codtools](https://github.com/aiidateam/aiida-codtools) plugins

**Comment by espenfl** [comment]
Maintainer of [aiida-vasp](https://github.com/aiida-vasp/aiida-vasp) here. Thumbs up from me as well.

**Comment by zhubonan** [comment]
maintainer of [aiida-castep](https://gitlab.com/bz1/aiida-castep) here - I support the request and is looking forward to using the classifier!

**Comment by chrisjsewell** [comment]
thumbs up from [aiida-crystal17](https://github.com/chrisjsewell/aiida-crystal17/)

**Comment by yakutovicha** [comment]
Maintainer of [aiida-cp2k](https://github.com/aiidateam/aiida-cp2k) here. Thumbs up from me as well.

**Comment by PhilippRue** [comment]
Thumps up in the name of [aiida-kkr](https://github.com/JuDFTteam/aiida-kkr) as well.

**Comment by broeder-j** [comment]
Also thumps up from me in the name of [aiida-fleur](https://github.com/JuDFTteam/aiida-fleur).

**Comment by vdikan** [comment]
From [aiida-siesta](https://pypi.org/project/aiida-siesta/), thumbs up.

**Comment by jamadden** [comment]
Thanks for your responses, everyone! With the evidence provided, to my mind, it looks like the proposed guidelines have been met, and I would suggest adding the classifier.

I'd like to allow a few days to give the other @pypa/pypi-moderators a chance to review this before taking action. (If there's no other motion on this by next week, feel free to ping me.)

**Comment by giovannipizzi** [comment]
Thanks, that's great!

**Comment by ewdurbin** [comment]
@jamadden I'm +1 to adding this classifier.

**Comment by jamadden** [comment]
`Framework :: AiiDA` has been added to pypi.org

**Comment by sphuber** [comment]
Thanks a lot @jamadden and @ewdurbin
