### ISSUE TITLE
HTTPError: 400 Client Error: File too large

### ISSUE THREAD

**Issue by erubiano** [pypa/warehouse#5598]
We tried to distribute the .whl files along with the .tar.gz file at TestPypi, but encountered "HTTPError: 400 Client Error: File too large. Limit for project 'marvin-pkg-erubiano' is 60 MB.". Could you please help us?  Thanks!

We want to start with TestPypi and later also Pypi.

The name of the project: Thttps://test.pypi.org/project/marvin-pkg-erubiano/
The size of our release, in megabytes: 90M
The Indexes we need the increase:  Test PyPI

**Comment by di** [comment]
I've set the upload limit for `marvin-pkg-erubiano` to 100 MB on TestPyPI.

**Comment by erubiano** [comment]
We did some necessary changes and our final distribution it is about 260 MB.

Could you please help us againg by increasing the limit?

**Comment by jamadden** [comment]
@erubiano The project on https://test.pypi.org/project/marvin-pkg-erubiano/ doesn't provide a description or a link to a homepage. Can you please help us understand what it is and why it needs to be so large? Perhaps there is a way to break slow-moving pieces into their own distribution so that no individual distribution needs to be so large.

**Comment by erubiano** [comment]
We have solved the problem in a different manner. We do not need more capacity.
Thank you anyway. Please close this issue.
