### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by 1constant** [pypa/warehouse#5606]
The site " magic 0.1 " cannot be found.  The site appears completely empty. 
There are a number of such sites.  Is there any place or mechanism where a user could report this kind of glitch?  Is there somebody (a kind of janitor) who is in charge of cleaning regularly different parts of the house?

**Comment by jamadden** [comment]
Hello,

Are you talking about the "Download" link on the page https://pypi.org/project/magic/ (or https://pypi.org/project/magic/0.1/)?  That was user-supplied metadata for an older version of the package index; [since PEP 470](https://www.python.org/dev/peps/pep-0470/) such external download links are no longer supported. However, there can be [historical value](https://www.python.org/dev/peps/pep-0541/#removal-of-an-abandoned-project) to preserving old release metadata, so it's not generally the policy to remove a project just because it is old.

**Comment by 1constant** [comment]
Yes, I was talking of this download link.

Ok, I understand the reason to maintain the site for historical value.

In view of PEP 470, shouldn't a mechanism be developed to remove all the 
disactivated external links ?

1Constant


Le 2019-03-22 à 10:36, Jason Madden a écrit :

**Comment by jamadden** [comment]
I don't know if that's been considered or addressed before. You might look into the [distutils-sig](https://mail.python.org/archives/list/distutils-sig@python.org/) archives and see what's there if there's nothing here in the issue archives; if you don't find a  discussion, of course please feel free to bring it up there. 

If there are any action items that come from that I would imagine they would need to be new, more general, tickets (or linked to the original tickets). Would you mind closing this one?

**Comment by 1constant** [comment]
Please close this ticket.

Thanks for the explanations.

(Or should I intervene in other way to close it ?)

1Constant


Le 2019-03-22 à 11:03, Jason Madden a écrit :
