### ISSUE TITLE
deleting release does not delete files on testing infrastructure

### ISSUE THREAD

**Issue by tomato42** [pypa/warehouse#5707]
**Describe the bug**

even after the release is deleted in the test.pypi.org instance, it's impossible to re-upload files.  twine reports following error:
```
HTTPError: 400 Client Error: This filename has already been used, use a different version. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/
```

**Expected behavior**

when a release is deleted in test instance, it should either delete all associated files with it or allow re-upload of files with the same names

**To Reproduce**

1. upload a new package to test pypi
2. delete that newly created package from test pypi
3. try uploading the same version of package

**My Platform**

setuptools (41.0.0)
twine (1.13.0)
wheel (0.33.1)

**Additional context**

What's the purpose of _test_ infrastructure[1] if it can't be used to test, fix and verify problem with release without burning through package versions!?

 1 - the only way to verify that project long description is correct before publishing a package, as there is no way to edit the long description after uploading the file

**Comment by jamadden** [comment]
> 1 - the only way to verify that project long description is correct before publishing a package, as there is no way to edit the long description after uploading the file

Perhaps you could try [readme-renderer](https://pypi.org/project/readme_renderer/), which provides the `twine check` command to verify the long description in the same way that warehouse does?

**Comment by tomato42** [comment]
I want to see how it looks like on the webpage, with tags, versions, etc.

**Comment by chaoflow** [comment]
@tomato42 I see and share your point and would also prefer if there'd be a way to re-upload releases to the *testing* infrastructure.

A workaround I'm using is to use .dev releases after a release to test.pypi.org that needs corrections.

test.pypi.org:
- 1.2.3 needs fix
- 1.2.3.dev0 and another
- 1.2.3.dev1 looks great

pypi.org
- 1.2.3 corresponds to 1.2.3.dev1 on test.pypi.org apart from the different version.

**Comment by di** [comment]
Thanks for the feature request! Using dev or prereleases is the recommended method here, for now.

The only distinction between PyPI and TestPyPI is that they are entirely separate (and can be visually distinguished). Otherwise, they behave exactly the same, which allows maintainers to have the same expectations about both. E.g., PyPI doesn't allow for reuploading of deleted distributions, so TestPyPI doesn't either.

Long term, we plan to turn down TestPyPI (#918) and instead support two-phase uploads (#726) which will allow maintainers to preview/review a new distribution before publishing, which will obviate this problem, so I'm going to close this issue in favor of that plan.
