### ISSUE TITLE
Add ability to require 2FA for a given project

### ISSUE THREAD

**Issue by di** [pypa/warehouse#5792]
**What's the problem this feature will solve?**
Currently there is no way to require a certain level of security for a given project.

**Describe the solution you'd like**
Allow a project to require that 2FA is enabled before a new owners/maintainers can be added. This should also prevent users that are not in compliance from doing the activities permitted by their role.

**Additional context**
~Blocked on #5790, otherwise this would allow any attacker to determine the 2FA status for a given user.~

**Comment by brainwane** [comment]
Some UX questions to be resolved include:

* If a user wants to send an invitation and the recipient doesn't have 2FA on, what happens?
* if you get an invite and don't have 2FA on, what happens?
* In projects with multiple owners: can any owner turn that on? Maybe it's not allowed until all the existing owners/maintainers have turned on 2FA? Once turned on, can any owner turn it off by themselves?
* Will we expose anywhere, in public, the info that this is a requirement for this project? (Leaning towards no, since that allows malfeasors to discover which projects DON'T have this requirement.)
* What happens to an existing owner/maintainer of a project if they try to disable 2FA on their account? Maybe they retain maintainer/owner status but are blocked from actually performing any of their privileged actions? Would they be unable to create project-scoped API tokens, for instance?

So we'd want to research this with user tests and check prior art on other similar platforms. That, plus developing flows and templates, makes this a feature that might take something like 2 weeks of UX work.

Until we get into it we won't know how much backend work is involved in accommodating flows and edge cases here, and how much PM work it'll take to document, publicize, triage related issues, etc., but it feels to me like it might take ~6 days of backend and ~4 days of PM work.

It would also be great to have an admin panel to make it easy for a PyPI site administrator to check whether a specific project has this turned on (to help with troubleshooting and potentially with quiet outreach to improve the security of specific high-profile packages). (Doing that, including underpinnings and methodical unit & integration tests, might take about 5 days of work.)

(Roughly scoping this out as we look for additional funding.)

**Comment by miketheman** [comment]
Has there been any further movement on the UX decisions here? Or would this need further work scoping to make those decisions?
