### ISSUE TITLE
GitHub statistics: link to project page instead of /stargazers

### ISSUE THREAD

**Issue by zmwangx** [pypa/warehouse#5876]
**What's the problem this feature will solve?**

Currently, "Stars" in the GitHub statistics section links to the /stargazers page on GitHub, e.g. https://github.com/pypa/warehouse/stargazers, which technically is the correct page to link to. However, not sure if it's just me, I find a list of random GitHub users who have starred a project almost completely useless 99.99% of the time. (Meanwhile, the /network page for forks is at least occasionally useful, though usually filled with pointless forks adding nothing.)

What about linking to the project page (where the number of stars is still clearly visible) instead of /stargazers? This seems in line with most ![https://github.com/pypa/warehouse/](https://img.shields.io/github/stars/pypa/warehouse.svg?style=social)-type badges you would encounter around the web, too; they usually link to the project page instead of /stargazers.

**Describe the solution you'd like**

Instead of linking to /stargazers (e.g., https://github.com/pypa/warehouse/stargazers), link to the project page (e.g., https://github.com/pypa/warehouse/).

**Additional context**

I should admit that I'm really just trying to use "Stars" as a link to source code.

**Comment by di** [comment]
If the statistics widget is present, there will be a corresponding link to GitHub in the "Project links" section, e.g. for https://pypi.org/p/pip:

![image](https://user-images.githubusercontent.com/294415/97454513-d8098c00-1904-11eb-928f-fe075a5b623d.png)

Since the link to the GitHub page is already present, and not really part of "statistics", I'm going to close this, but thanks for the feature request!
