### ISSUE TITLE
Project Theft

### ISSUE THREAD

**Issue by pro-src** [pypa/warehouse#5901]
My project cloudscraper was stolen by another user. I gave the user owner access rights in faith of a partnership. They subsequently removed my owner access rights, blocked me from the Github repo, violated the MIT license, and plagiarized my work. I have sent a DMCA takedown notice and forwarded emails to legal@python.org. I haven't heard back from python.org as of yet and my DMCA notice is still being processed. The user has fixed some of the plagiarism since my DMCA notice but everything else is still very wrong.

The repo in question is https://github.com/VeNoMouS/cloudscraper
The package in question is https://pypi.org/project/cloudscraper

The project was my idea. I created the project on pypi.org. I authored 90% of the code. I trusted the wrong person.

Only 3 days ago did they bother to fix one problem with the copyright notice. I've been trying to fix this for weeks. I can prove my copyright and forward emails of the DMCA notice.

Please help me get things back under control.

**Comment by Piedrosys** [comment]
I'm closing this due to lack of response and since it seems clear that I've lost my rights to this project. 

Clarification on the removing and adding of roles. ***I as the project owner could not make my self a maintainer (despite what the logs say).*** Feel free to reproduce this as proof for yourself. You can't make yourself a maintainer when you're the owner and the log entry will be created regardless. It just doesn't work because you're the owner.

I reiterate that I wanted a partnership and letting the other guy take the lead as a way to establish trust was what made sense to me at the time.

In order to make myself a maintainer rather than the owner. I did delete the project with the intention of letting it be recreated. It did not work exactly. An experiment was conducted to see if ownership had been given to the other guy. ***I was never meant to be removed from the project.***

I did not make myself a maintainer. Yes, that was the original intention(a mistake). I was removed from the project entirely by the other guy.

After reviewing the chat log referenced in the issue linked above, I see more clearly the full extent of my mistake and is why I'm closing this issue now. But let's be honest, the project is small and not of any real value. A personal project that was stolen. It's a shame that people like that exist.

**Comment by pro-src** [comment]
I'm closing this due to lack of response and since it seems clear that I've lost my rights to this project.

Clarification on the removing and adding of roles. I as the project owner could not make my self a maintainer (despite what the logs say). Feel free to reproduce this as proof for yourself. You can't make yourself a maintainer when you're the owner and the log entry will be created regardless. It just doesn't work because you're the owner.

I reiterate that I wanted a partnership and letting the other guy take the lead as a way to establish trust was what made sense to me at the time.

In order to make myself a maintainer rather than the owner. I did delete the project with the intention of letting it be recreated. It did not work exactly. An experiment was conducted to see if ownership had been given to the other guy. I was never meant to be removed from the project.

I did not make myself a maintainer. Yes, that was the original intention(a mistake). I was removed from the project entirely by the other guy.

After reviewing the chat log referenced in the issue linked above, I see more clearly the full extent of my mistake and is why I'm closing this issue now. But let's be honest, the project is small and not of any real value. A personal project that was stolen. It's a shame that people like that exist.
