### ISSUE TITLE
Validate Complexity of Passwords

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#6]
Ensure that user passwords always match some level of password complexity/strength.

**Comment by nlhkabu** [comment]
I'd like to indicate password strength client side too... we'll need to look into a plugin for this.

**Comment by dstufft** [comment]
I think Dropbox has a js library for it.

**Comment by alex** [comment]
https://github.com/dropbox/zxcvbn

**Comment by nlhkabu** [comment]
Nice!

**Comment by demianbrecht** [comment]
@dstufft @nlhkabu: What's the status of registration flows? I'm interested in taking a run at this, but noticed that there's been similar work done in https://github.com/pypa/warehouse/pull/334 (which was closed).

**Comment by nlhkabu** [comment]
Sounds great from my end @demianbrecht !

I have not yet started on the design, so the best way to build the templates is to make them _functional only_ (i.e. don't worry at all about how it looks at all).  Once your PR is merged, I will come through and apply the appropriate styling.

**Comment by dstufft** [comment]
The status is they still need to be written. That PR is old and it's against a version of Warehouse before I rewrote it in Pyramid so it's not directly usable.

**Comment by demianbrecht** [comment]
Thanks @nlhkabu and @dstufft. I was a little swamped last week but I'm hoping to get some time to devote to this during this week.

**Comment by demianbrecht** [comment]
While working on the registration flow, I took a quick look at zxcvbn. I was hoping that the Python port would be consistent with the initial JS implementation. Sadly, that doesn't seem to be the case (https://github.com/dropbox/python-zxcvbn/issues/14) and would lead to inconsistencies between server and client side, which wouldn't be so hot.

A couple potential paths I can think of:

1. Fork the project (it seems to have been abandoned) and update it to match. I'm not terribly keen on doing this due to time constraints, but if someone else is willing, then great
2. Only have server-side complexity validation
2a. Adding a server-side endpoint for FE validation calls
3. Roll our own consistent implementation between server and front end

I think I'd favor either 2 or 3 depending on which way the wind blew.

**Comment by demianbrecht** [comment]
@nlhkabu until there's a matching fe/be implementation, [here's what's recently been added] for password strength. Should be trivial to implement something matching in JS as a stop gap until a better replacement is found.

**Comment by controversial** [comment]
@demianbrecht Why are we concerned about server-side password strength evaluation? We could use *only* the JavaScript library, and validate password strength before allowing the user to submit the form, and we could do nothing server-side.

Of course, the viability of this option depends on whether we're concerned about the potential vulnerability (which I don't think we are): the determined user could theoretically use the JavaScript console or even just `curl` to submit false results about password strength, such as giving `password` a maximum strength rating, but that's probably not a _huge_ concern. Because it would only affect the user in question, nobody else, the user is only hurting himself / herself.

What's the opinion on this? Why do we need to have password strengths stored if they could be easily computed and re-computed with JavaScript?

**Comment by sigmavirus24** [comment]
> Why are we concerned about server-side password strength evaluation? We could use only the JavaScript library, and validate password strength before allowing the user to submit the form, and we could do nothing server-side.

Because people don't only interact with Warehouse via a browser. Even so, JavaScript should never be the only form of verification. Even someone using a browser can modify the request before it is actually sent, which will bypass any JavaScript validation. Providing JS validation is merely a UX enhancement. Providing server-side validation is providing the actual service.

**Comment by controversial** [comment]
It’s not merely a UX enhancement, it enforces security for the vast
majority of users. The question comes down to how strongly we want to
enforce password security. I don’t think it’s completely black and white. I
see your point, though.

**Comment by demianbrecht** [comment]
> The question comes down to how strongly we want to
enforce password security.

*Very* strongly :)

Without sufficient password strength on the server, as Ian mentioned, we leave users open to passwords that aren't sufficiently strong, which reduces user security. Because of the reduction of user security, it increases the risk to packages managed by a given user. Package integrity and security are of paramount importance, so everything that can be done to increase user-level security is a Good Thing.

**Comment by controversial** [comment]
Right. Makes sense. I keep forgetting that this is a service under which
thousands of people can rely on the security of a single account (Imagine
if `requests` was updated to install spyware on users’ machines). So this
option is out.

**Comment by dstufft** [comment]
I'm going to drop this out of the shut down milestone since this is implemented for the server side validation (which is the actual important one) and the only thing left is to implement it client side (which is just a UX enhancement).

**Comment by yeraydiazdiaz** [comment]
@demianbrecht seems there's [a better maintained version of zxcvbn-python](https://github.com/dwolfhub/zxcvbn-python) whose output is identical of that of the JS version, at least on the quick test I ran on my box.

**Comment by brainwane** [comment]
Given that the UX enhancement is what the end user *sees* and understands, I'm adding this back into the "shut down legacy PyPI" milestone. :)
