### ISSUE TITLE
Wrong package version

### ISSUE THREAD

**Issue by uda** [pypa/warehouse#6074]
**Describe the bug**
PrettyTable shows latest version to be "7", which doesn't exist, the archives behind are actually "0.7".
This causes the latest version "0.7.2" not to be used by default.

**Expected behavior**
Version "0.7" to show "0.7" and the latest version to be "0.7.2"

**To Reproduce**
https://pypi.org/project/PrettyTable/

**Additional context**
I know there is another drop-in fork for this package, but this is a dependency of a different package I am using and it is causing issues in installation if not specifying "prettytable" as a direct dependency with the correct version.
I am not sure how 0.7 became 7 (I checked the archives, all files specify 0.7), so it is worth looking into even if the package is unmaintained.

**Comment by jamadden** [comment]
According to the project's journal, a version '7' was uploaded in Feb of 2013 (note that the upload action itself [includes the version](https://warehouse.pypa.io/api-reference/legacy/#upload-api), so probably the uploading tool failed to properly interpret the version). This version was then "hidden", but the files and release were left in place. Since that time, the ability to hide releases was removed from PyPI, so version 7 is now reported as the newest version on the project's home page (and pip [never honored the hidden bit anyway](https://github.com/pypa/pip/issues/788)).

A solution would be to remove version 7 altogether. That's something the project maintainer's could do. I believe @flaper87 is such a maintainer.

**Comment by brainwane** [comment]
@uda have you tried reaching out to @flaper87 via email? I see an email address listed at https://github.com/flaper87 .

**Comment by flaper87** [comment]
Hi folks,

I'm so so sorry but I just saw this. Sadly, my time to maintain this project has been reduced to almost none and I haven't been able to push new versions of it.

I'm normally completely and absolutely against deleting versions from pypi but I've gone ahead and deleted it since that version still exists in Pypi under a different (and correct) version number. Hope this helps to fix the issue.

On a side note, if any of you would like to help to maintain prettytable, I'd be more than happy to add you.
