### ISSUE TITLE
Implement OpenID Logins

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#61]
PyPI allows logging in via OpenID, we need to either implement this or deprecate it and provide a migration path.

**Comment by domenkozar** [comment]
Should be fairly trivial with http://velruse.readthedocs.org/en/latest/

**Comment by ergo** [comment]
I suggest http://peterhudec.github.io/authomatic/ instead - it supports both py 2 and 3, and I've implemented both velruse and authomatic in my applications.

Authomatic supports bigger range of providers over velruse though.

I can provide example implementation if you guys are interested.

**Comment by apollo13** [comment]
The last release from velruse was in 2013 -- does not seem to be really reassuring. If there are no objections from @dstufft I'd give authomatic a try, unless there is a "defacto" solution for pyramid I do not know off…

**Comment by ergo** [comment]
I've used both velruse and authomatic - both work fine with pyramid - however authomatic supports py3 and way more providers as of today.

**Comment by ewdurbin** [comment]
Numbers from the past month:

<img width="1039" alt="screen shot 2017-09-20 at 10 17 53 am" src="https://user-images.githubusercontent.com/1200832/30648855-0224a3c6-9ded-11e7-83be-16cd5ddd7dc8.png">

While I think maintaining federated authentication is not a bad idea, it is clearly not used enough to warrant doing any backflips.

pypa/pypi-legacy currently uses Authomatic for both Google and OpenID and I'm a huge fan, it was straightforward to integrate and hasn't caused any fuss since being deployed.

**Comment by brainwane** [comment]
@dstufft Per [your distutils-sig email](https://mail.python.org/pipermail/distutils-sig/2018-January/031855.html) shall we close this issue?

**Comment by rsyring** [comment]
FWIW, it seems like a few comments on the distutils-sig thread indicate the usage disparity is due to the perception that google integration doesn't work on pypi currently.  That's also true for me.  If better social auth (GitHub and Google being my two preferences) were available in the future, I'd likely use it more.

**Comment by ewdurbin** [comment]
We disabled new Google Login associations many moons ago.

Only users who had previously associated a Google Account are able to use the feature.

**Comment by ewdurbin** [comment]
> No PyPI user found associated with that Google Account, Associating new accounts has been deprecated.

Is the "error" message that currently displays when attempting to login.

**Comment by dstufft** [comment]
Closing this, we're not going to support Federated auth at this time.
