### ISSUE TITLE
PEP 541: transfer ownership of LinkChecker

### ISSUE THREAD

**Issue by mgedmin** [pypa/warehouse#6136]
I would like to request transfer of ownership of the `LinkChecker` project to myself (`mgedmin`) and @anarcat (`anarcat` on PyPI).

The original maintainer (@wummel) hasn't responded to [numerous contact requests on GitHub](https://github.com/wummel/linkchecker/issues/686) or via email.  The last package version on PyPI is from 2014 and is broken due to a bug in version comparison logic (https://github.com/wummel/linkchecker/issues/649) that's been fixed in git master in 2016 but never released.  There have been no git commits since then.

We've forked the project to https://github.com/linkchecker/linkchecker/ and have made several releases, but we're unable to distribute them on PyPI.

(There was a previous request to transfer ownership filed at https://github.com/pypa/pypi-legacy/issues/725.)

**Comment by jamadden** [comment]
https://pypi.org/project/linkchecker links to http://wummel.github.io/linkchecker/ which does link back to @wummel. The contact email present on https://pypi.org/project/linkchecker matches the contact email on file with PyPI, which has been verified (though it appears to have been some time since the account was accessed). Said github account has shown activity recently though. 

I've reached out to the contact email on file to start the [reachability](https://www.python.org/dev/peps/pep-0541/#reachability) countdown.

**Comment by anarcat** [comment]
i confirm this is a legitimate request and that we have not heard from @wummel since we started this process over 2 years ago.

**Comment by mgedmin** [comment]
I think the reachability countdown has expired: two months have passed since July 2 (PEP 541 says "six weeks").

**Comment by anarcat** [comment]
hello... is this thing on? we have timed out here for months, if not years. we filed three different issues as the ownership processed changed (twice!) since 2017. it seems we kind of deserve an answer here. :)

if it's a no, we'll just go our own way and make a release under a different name, but i'm getting a little frustrated by the lack of progress...

can someone just make the call here already? i think we have checked all the boxes here and are ready to move ahead...

thanks!

**Comment by jamadden** [comment]
I'll ask the appropriate admins to make the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by anarcat** [comment]
oh my! thank you so much!!! whoohoo! :)
