### ISSUE TITLE
Request trove classifier for Plotly Dash

### ISSUE THREAD

**Issue by fkromer** [pypa/warehouse#6273]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: Dash`

## Why do you want to add this classifier?

[Plotly Dash](https://plot.ly/dash/) is the current de facto standard data science dashboard application framework with components, dev tools, etc. provided as Python packages via PyPi. A trove classifier for the framework would users help to to find relevant packages.

**Comment by jamadden** [comment]
Hi! Thanks for the request. The PyPI moderators are in the process of developing a few guidelines for the creation of new `Framework` classifiers. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, I think we're expecting the bar to add new ones to be relatively high. Currently, we're looking at these guidelines:

* New `Framework` classifiers should be created if they are "notable;" and 
* They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that.

As to the other guideline ('immediate use to existing projects'), it's been suggested that 

- Requestors can demonstrate this by providing links to 10 or more **existing PyPI projects** that will use the classifier; or
- Another way to demonstrate notability would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier.

Are gathering those links and/or comments something you would be able to help with?

**Comment by fkromer** [comment]
@jamadden This makes total sense.

> We understand that "notability" is subjective and we'd appreciate help judging that.

Plotly Dash is the current de facto standard data science dashboard application framework. The [project](https://github.com/plotly/dash) has around 9500 stars on GitHub right now. I don't know any other comparable framework providing the same degree of features and extensibility.

> - Requestors can demonstrate this by providing links to 10 or more existing PyPI projects that will use the classifier; or

Obviously it's not easy to find relevant packages on PyPi. [The plotly organization is maintaining 86 GitHub repositories containing Python code.](https://github.com/plotly?utf8=%E2%9C%93&q=&type=&language=python) Almost every repo could use the classifier. The framework is extensible easily, already adopted heavily but still relatively new. I could imagine a lot more future packages will use the classifier as well.

> - Another way to demonstrate notability would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier.

Contributor comments have been requested.

**Comment by chriddyp** [comment]
As the original author of Dash, I support this classifier.

One thing unique about Dash as a framework is that it emphasizes a "component plugin system". So, all Dash "components" (think "widgets") are themselves plugins, many of which are community maintained.

With this in mind, many folks in the community (see Dash forums here: https://github.com/plotly/dash-core-components/blob/5ceae700d915e2df54829098ed8574dd634dd783/src/components/Graph.react.js#L108-L113) have requested an easier way to find published component packages. For example, see these threads:
- https://community.plot.ly/t/pypi-classifier-for-dash-framework/26346/3
- https://community.plot.ly/t/show-and-tell-does-dash-have-a-marketplace-if-not-why-not/23447

The forum itself has a "show and tell" thread & tags that provide one way to share components, see:
- https://community.plot.ly/tags/show-and-tell
- https://community.plot.ly/t/show-and-tell-community-thread/7554/49

And our component plugin system (https://community.plot.ly/t/show-and-tell-community-thread/7554/49) recommends tagging the components with the GitHub tag `plotly-dash` (of which there are 122 projects, see https://github.com/topics/plotly-dash)

However, these methods are "opt-in" - a developer has to explicitly share their work on the community forum and remember to tag their project on GitHub. With the PyPI classifier, it'd be more automatic and discoverable as our plugin system could use this trove classifier in the component "boilerplate" / "cookie-cutter" code, e.g. here: https://github.com/plotly/dash-component-boilerplate/blob/64406a8ecec85da56b40e930d48fa66d1a3b309c/%7B%7Bcookiecutter.project_shortname%7D%7D/setup.py, which would greatly benefit the community.

Thank you for your consideration!

**Comment by mbkupfer** [comment]
I'm using Dash very frequently and publish dash components from time to time. I think this would prevent unecessary duplication and help elevate the ecosystem by adding more formality to how these component plugins are shared.

**Comment by tcbegley** [comment]
I maintain [dash-bootstrap-components](https://github.com/facultyai/dash-bootstrap-components). Like other third-party extensions to Dash, since we're not affiliated with Plotly, our library doesn't appear on the Plotly GitHub organisation page, or in any of the official Dash documentation. A Dash classifier would certainly help us become more discoverable to users of Dash.

**Comment by GibbsConsulting** [comment]
We publish [django-plotly-dash](https://github.com/GibbsConsulting/django-plotly-dash) and [jupyter-plotly-dash](https://github.com/GibbsConsulting/jupyter-plotly-dash) and are also not affiliated with Plotly, 
 which means we are in the same situation as @tcbegley . We would also welcome a Dash classifier.

**Comment by mkcor** [comment]
I'm a Dash contributor and, as a disclaimer, I'm affiliated with Plotly.

First, I would welcome a `Framework :: Dash` trove classifier by principle, because I'm into library and information science (so, data management, data searchability, data discoverability).

I also support this addition for practical reasons: the Dash ecosystem is getting quite abundant, so a Dash classifier would be helpful to keep up with its growth.

Let me mention [dash-bio-utils](https://pypi.org/project/dash-bio-utils/) in addition to the list provided by @fkromer : it is an embryonic package gathering dataset parsers used in the demo apps featured in [dash-bio](https://pypi.org/project/dash-bio/).

**Comment by shammamah** [comment]
As another Dash contributor and core developer, I would also like to support the addition of a trove classifier for Dash. As Chris mentioned above, the `dash-component-boilerplate` is a way for our users to create their own custom components that they can subsequently share with the community. Adding a classifier would allow them to do so in a more structured way.

**Comment by delsim** [comment]
The [dpd-components](https://github.com/GibbsConsulting/dpd-components) package is one example of the custom components described by @shammamah

**Comment by fkromer** [comment]
@jamadden Do you need further assistance to get the classifier added?

**Comment by freshwuzhere** [comment]
I’m a lowly dev and contributor to Dash and the addition of a trove classifier would greatly assist discovery of the great works conducted and posted by the many dedicated data scientists around the world.  
Thank you.

**Comment by jamadden** [comment]
The classifier `Framework :: Dash` has been added. Thanks for your patience!
