### ISSUE TITLE
500 error on project deletion

### ISSUE THREAD

**Issue by di** [pypa/warehouse#6448]
Currently project deletion results in a 500 error due to #6339.

This is because the `UserEvent` and `ProjectEvent` models have a 'not-null' constraint on the project ID, and are not cascaded (deleted) when the project is deleted.

**Comment by woodruffw** [comment]
#6450 patches over this by deleting the orphaned events, but a more permanent solution needs to retain those events.

From chat:

We should ultimately key on `users.username` and `projects.normalized_name`. In order to key on the latter, it'll need to be changed from a `column_property` into a real (and unique) column, which will require a migration.
