### ISSUE TITLE
newrelic javascript is not executed because of the content security policy

### ISSUE THREAD

**Issue by alex** [pypa/warehouse#658]
![screen shot 2015-09-06 at 1 50 43 pm](https://cloud.githubusercontent.com/assets/772/9705783/4cfcb77a-549e-11e5-9e7e-54722db1f2ed.png)

**Comment by dstufft** [comment]
This is interesting, a quick google brings up https://discuss.newrelic.com/t/content-security-policy-and-browser-injection/2629/43 which suggests that New Relic Javascript is fundamentally incompatible with CSP at this time without adding the ``unsafe-inline`` directive. Github apparently worked around this by developing their own JS based performance collection tool (http://githubengineering.com/browser-monitoring-for-github-com/).

At this point, I think it's probably not reasonable for us to use the New Relic browser javascript since they provide no way to do so securely with a restrictive CSP policy.

**Comment by alex** [comment]
(That forum is super hard to read)

Does the contents of the JS change every time, or is the hash an option?

**Comment by dstufft** [comment]
It changes each time with data to connect the browser data to the backend data.

**Comment by alex** [comment]
Is `nonce` an option, I don't know how that CSP directive works.

On Sun, Sep 6, 2015 at 2:05 PM, Donald Stufft <notifications@github.com>
wrote:

> It changes each time with data to connect the browser data to the backend
> data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pypa/warehouse/issues/658#issuecomment-138104572>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
It would be an option if we had any control over the injected JS, but that's injected by the New Relic code and they don't provide an option to specify a nonce.

**Comment by alex** [comment]
That seems like a relatively straightforward thing for them to implement
though. Can we file a bug?

(Also, where there's a regex there's a way)

On Sun, Sep 6, 2015 at 2:10 PM, Donald Stufft <notifications@github.com>
wrote:

> It would be an option if we had any control over the injected JS, but
> that's injected by the New Relic code and they don't provide an option to
> specify a nonce.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pypa/warehouse/issues/658#issuecomment-138104787>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
They said there is an internal feature request for it already, so they are working on it they just don't have it yet.

**Comment by dstufft** [comment]
I'm closing this. With #743 New Relic is no longer being used.
