### ISSUE TITLE
Stale cache?

### ISSUE THREAD

**Issue by ashleysommer** [pypa/warehouse#6652]
I uploaded a new version of Sanic-Restplus approx 35 minutes ago, its not showing at https://pypi.org/project/sanic-restplus/ however the test-pypi shows it fine: https://test.pypi.org/project/sanic-restplus

**Comment by Mng12345** [comment]
I just found the version of my package is updated! May be the system is delayed for handling all uploaded packages #6651

**Comment by eamonnfaherty** [comment]
I am seeing this for a project I maintain.

**Comment by ewdurbin** [comment]
PyPI's asynchronous job queue saw a backup beginning around 09-17-2019 21:28:00 UTC due to a large influx of messages. The worker pool has been temporarily expanded to process the remaining messages and we'll be investigating what caused the influx. Messages should be up to date within an hour, and all backlogged emails and cache purges should be complete.

**Comment by ewdurbin** [comment]
The queue has cleared. If you're still experiencing this please reopen this issue.
