### ISSUE TITLE
Still find the same project name after delete the last project

### ISSUE THREAD

**Issue by gideonmanurung** [pypa/warehouse#6654]
**Describe the bug**

Before i delete the project , i have upload the lastest version and successfull to upload. I have found the lastest version in dashboard , but when i try to install by pip i get the previous version of the project. So i delete the project and reupload to make e new project , but got an error because the previous name project that i delete still can found in pypi but i didn't get access to control the project again.

**Expected behavior**

After i remove the project , the project name still can use for future.

**To Reproduce**

**My Platform**

**Additional context**

**Comment by ewdurbin** [comment]
PyPI does not allow reuse of existing file names, you must reupload with a new version to recreate your project. https://pypi.org/help/#file-name-reuse

pip was not able to see your file due to PyPI's asynchronous job queue seeing a backup beginning around 09-17-2019 21:28:00 UTC due to a large influx of messages. The worker pool has been temporarily expanded to process the remaining messages and we'll be investigating what caused the influx. Messages should be up to date within an hour, and all backlogged emails and cache purges should be complete.

**Comment by gideonmanurung** [comment]
So i can reupload to make a new version of my project even i have delete my project right ? @ewdurbin

**Comment by ewdurbin** [comment]
@gideonmanurung yes, you can recreate the project by incrementing the version and reuploading.

**Comment by ewdurbin** [comment]
The queue has cleared. If you're still experiencing issues with pip seeing your project please reopen this issue.

**Comment by gideonmanurung** [comment]
Thank you @ewdurbin , the bug has solved.
