### ISSUE TITLE
Typo "Top Storage users" in Stats page

### ISSUE THREAD

**Issue by rffontenelle** [pypa/warehouse#6691]
The [Stats page, line 30](https://github.com/pypa/warehouse/blob/97c4a5124e86119eabe57c7b896a34d2732dc1d0/warehouse/templates/pages/stats.html#L30) (e.g. [PyPI's Stats page](https://pypi.org/stats/)) has the heading text **Top storage users** but it seems to be related to **uses**, rather than **users**. Maybe it is a typo?

**Comment by nlhkabu** [comment]
Thanks for flagging this @rffontenelle.
Maybe "Top projects by package size" would be a more accurate heading here?

**Comment by brainwane** [comment]
**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

I think the wording should be:

> Top storage users:
> Ordered by the sum of all packages of each project

You'll need to change wording in `warehouse/templates/pages/stats.html` and find a way to add and style a subheading.

**Comment by lilivelazquezz** [comment]
Hello! I would love to work on this.

**Comment by raulgspan** [comment]
Hey, I started to look into this last night at the NY meetup as a first-time contributor, finally got my local env set up this morning... A few things:

- The second comment suggesting "projects" in the headline instead of "users" is right. The table is a list of "projects" so the heading should match. I would suggest "Top projects by total package size".

- "Ordered by the sum of all packages of each project" is a lot of text and seems unnecessary, it's pretty clear when you look at the table what it's ordered by. If anything, I'd suggest a small down arrow on the "Sum of release files (bytes)" column to indicate the sort order.

**Comment by brainwane** [comment]
@nlhkabu can you advise @lilivelazquezz and/or @raulgspan on a good approach?

**Comment by raulgspan** [comment]
Submitted PR 6767 for this: https://github.com/pypa/warehouse/pull/6767
