### ISSUE TITLE
Request trove classifier

### ISSUE THREAD

**Issue by marcelcure** [pypa/warehouse#6708]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

web3fsnpy

## Why do you want to add this classifier?
 I deleted web3fsnpy by accident from testPyPI as this is my first time using it, but there are users waiting to download this with the name web3fsnpy

**Comment by jamadden** [comment]
Hello,

I'm sorry, I do not understand your request.

A [classifier](https://pypi.org/classifiers/) is used to make browsing particular categories of software easier. For example, I can browse for software related to the popular [Django web framework](https://pypi.org/search/?c=Framework+%3A%3A+Django). 

Using classifiers is *optional*; using any particular classifier is not required in order to upload packages to pypi.org or test.pypi.org.

**Comment by marcelcure** [comment]
I'm sorry - I have used the wrong request. I wanted to upload to my project name web3fsnpy  on testPyPI but I had already deleted it by mistake and now it won't let me upload it again.

**Comment by jamadden** [comment]
PyPI does not allow reusing filenames. You'll need to use a new version number.

**Comment by marcelcure** [comment]
OK thanks.
