### ISSUE TITLE
Bug when try to delete a version

### ISSUE THREAD

**Issue by thiagopelizoni** [pypa/warehouse#6816]
[As this video shows](https://trello-attachments.s3.amazonaws.com/5c8241afaa58167f9f393552/5da067704a01557ecb650dcd/a76ce8f354716fc0e91a00c680951850/pipy_error.mp4), when I try to delete an existing version of a package, it shows a 404 page, instead of delete it.

**Comment by ewdurbin** [comment]
This report is from a user with the `pt_BR` locale. The issue appears to be due to translated strings being sent to our macros for the [`confirm_modal`](https://github.com/pypa/warehouse/blob/9923793cdd6e54e9d10e7be8b09b6ef0d953ce5f/warehouse/templates/manage/manage_base.html#L75-L130) and [`confirm_button`](https://github.com/pypa/warehouse/blob/master/warehouse/templates/manage/manage_base.html#L182-L194).

In reproducing, I confirmed that this was sending the translation of `version` (`versão`) to the backend.

<img width="397" alt="Screen Shot 2019-10-11 at 4 15 40 PM" src="https://user-images.githubusercontent.com/1200832/66684693-a0bc3480-ec48-11e9-9cf3-f1655a585b48.png">

[This line in particular](https://github.com/pypa/warehouse/blob/9923793cdd6e54e9d10e7be8b09b6ef0d953ce5f/warehouse/templates/manage/releases.html#L95) seems suspect, sending `gettext('Version')` as the `confirm_name` parameter.

**Comment by ewdurbin** [comment]
A possible solution, though not necessarily ideal is to update the backend routes to look for the translated string. [Here](https://github.com/pypa/warehouse/blob/9923793cdd6e54e9d10e7be8b09b6ef0d953ce5f/warehouse/manage/views.py#L921) is the hardcoded comparison for this specific case.

**Comment by ewdurbin** [comment]
Errrr, that won't work. This ends up as a 404 because of the routing, looking for hardcoded `confirm_release`: https://github.com/pypa/warehouse/blob/9923793cdd6e54e9d10e7be8b09b6ef0d953ce5f/warehouse/manage/views.py#L903
