### ISSUE TITLE
Rate limit login attacks

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#707]
We need to enable rate limiting on the log in attempts so people cannot easily brute force them.

**Comment by miohtama** [comment]
I'm not a Warehouse contributor (yet), but below related things.

* Here is Pyramid code I use in another project: https://gist.github.com/miohtama/86c86b4caa61a5615e44

* Background story:  http://opensourcehacker.com/2014/07/09/rolling-time-window-counters-with-redis-and-mitigating-botnet-driven-login-attacks/

*  More about the topic: http://operationssecurity.org/en/latest/user/index.html#brute-force-login-prevention

**Comment by demianbrecht** [comment]
I'm going to be taking a stab at authentication/registration and obviously falls in that ballpark. I'm thinking that rate limiting isn't something that we want to do (unless there's a technique that I'm missing).

If the account in question is used as the key by which we're rate limiting, it's easily possible to effectively DoS a legitimate user. Even if an account lockout can be reset by a password reset via email, it's still a painful process for the user.

If we use the source address as the key, then we're potentially DoSing all users behind a proxy.

Rather than rate limit, I'm wondering if the form should use either a captcha or a secret question to which an answer is given during registration (although that would pose a problem for account migration) when attempts >= N (3 seems pretty common).

In addition to the captcha/secret question, a delay could be added to the login flow, which would drastically increase the time required for automated attacks.

Thoughts?

**Comment by miohtama** [comment]
There are three ways of rate limiting for login, sign up and password reset

* Limit by IP address. This is pretty much useless as in future IPv6 gives attackers basically endless addresses and you need fancy way to upscale address matching to network block http://serverfault.com/questions/631160/banning-ipv6-addresses 

* Limit by username: this prevents spearhead attacks against individual users. Show CAPTCHA after N attempts, force cooldown after M attempts. This is the scenario where delay can help. However in the contemporary world of cyber threads this is rarely the most common attack method.

* Global attempt threshold: require CAPTCHA for all attempts (even for first login/password) if the system attempt threshold excess normal values (which one obtains from active system monitoring). In this case the system is most likely under a botnet attack and attackers are going through email (username)/password combo lists bought from blackmarkets and having thousands of IPs in their possession.  The attackers just cycle to the next email (username) / password / IP combo for every attempt so cooling down cannot help here. This is what bad guys tend to do against high value targets which I would see PyPi to be. It's likely millions of different username combos from thousands of IPs.

To count attempts  one can use rolling time window counters. Here is one example I made for Redis:

* https://opensourcehacker.com/2014/07/09/rolling-time-window-counters-with-redis-and-mitigating-botnet-driven-login-attacks/

**Comment by demianbrecht** [comment]
> Global attempt threshold

I hadn't actually considered that attack vector, thanks for pointing it out. In light of that, I'm +1 to forging down the Recaptcha path on every login attempt. This seems option with the least friction, while minimizing the potential for effectively creating DoS attacks for legitimate users. Minimal development effort while (seemingly) providing the highest level of security against brute force attacks. Sounds like an easy win to me.

Any thoughts from others?
