### ISSUE TITLE
"Invalid credentials" when revoking a token

### ISSUE THREAD

**Issue by ewjoachim** [pypa/warehouse#7143]
**Describe the bug**
I cannot revoke a token I have created, because it asks for my password and refuses to accept it. I'm using a password manager so low risk of typo, and I've tried displaying the password and they're the same. I've tried logging out and in with the same password and it works

**Expected behavior**
The crenetial check on token revocation should work with my password

**To Reproduce**
- Create a token
- From the creation screen, click on the remove button
- Type your password and validate

- Additionally, try removing it from your profile page.

**My Platform**

Firefox 71, Ubuntu

**Comment by ewdurbin** [comment]
I have been unable to reproduce this locally at this point.

It points to something going wrong when [validating the submitted form](https://github.com/pypa/warehouse/blob/64d223a255e0150232a33ebdb1b737d9a2fd5c5d/warehouse/manage/views.py#L725) that isn't necessarily associated with the credential supplied.

**Comment by ewdurbin** [comment]
@ewjoachim and @JokerQyou, is there any chance that a browser extension is modifying the contents of the form? In particular the `macaroon_id` input which is hidden. If the `csrf_token` input was being manipulated you'd get a different error.

**Comment by JokerQyou** [comment]
I've tried with `test.pypi.org` and it worked fine. This issue is only reproducible with `pypi.org`.

As for the `csrf_token` value, I've checked with the developer tool, the final value in the POST request matches the initial value received from the server. See the screenshots:

![Initial CSRF token value received from server](https://user-images.githubusercontent.com/1465267/71678158-77322580-2dbf-11ea-98a2-319b748e87b7.png)

![CSRF token sent in the POST request](https://user-images.githubusercontent.com/1465267/71678216-98931180-2dbf-11ea-892b-8fac5db0f243.png)

**Comment by JokerQyou** [comment]
Oh, sorry I misread your comment. I checked the `macaroon_id` field and it was indeed modified by the password manager! It was incorrectly filled with my username. If I manually copy and paste the password, the deletion works fine.

**Comment by ewjoachim** [comment]
Hm, that's interesting. I reproduce if I let my password manager, bitwarden, fill the password field for me. If I copy/paste manually, it works. I'm going to try and explore how the payload is different in both cases.

**Comment by ewdurbin** [comment]
This should be resolved. Can either of you confirm?

**Comment by JokerQyou** [comment]
Just tested on `pypi.org` and it's fine now.
