### ISSUE TITLE
Catch additional pymacaroons.Macaroon.deserialize exceptions

### ISSUE THREAD

**Issue by di** [pypa/warehouse#7434]
It appears that someone has [enumerated the various exceptions `pymacaroons.Macaroon.deserialize` might raise](https://github.com/ecordell/pymacaroons/issues/50). It'd be great if that were resolved, but we might want to further harden the work from #7424 to handle these other cases?

_Originally posted by @ewdurbin in https://github.com/pypa/warehouse/issues/7298#issuecomment-589957864_

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
I've added the ["good first issue"](https://github.com/pypa/warehouse/labels/good%20first%20issue) label to this issue.

**Comment by di** [comment]
In #7876 we discovered that `pymacaroons.Macaroon.deserialize` can also raise an `IndexError`, which is causing https://sentry.io/share/issue/8737571d268f41ae9eef2d12279882d2/

**Comment by deveshks** [comment]
I want to work on this PR, but it would be great if I get some additional context before I start. 

With that in mind, I will outline below what I could gain until now. Please feel free to expand/add on if I have missed something here for an initial stab at this.

We are currently using `pymacaroons.Macaroon.deserialize` [here](https://github.com/pypa/warehouse/blob/master/warehouse/macaroons/services.py#L80) and [here](https://github.com/pypa/warehouse/blob/master/warehouse/macaroons/services.py#L105) , and we are not catching the other exceptions mentioned in https://github.com/ecordell/pymacaroons/issues/50.

So in order to work towards fixing this, we will had to add one `except` clause around both call sites per PR, and then 

1. return None 

https://github.com/pypa/warehouse/blob/2d6364a12372cbf3ff18aeb861f26432486bb88e/warehouse/macaroons/services.py#L79-L82

2. raise an exception again

https://github.com/pypa/warehouse/blob/2d6364a12372cbf3ff18aeb861f26432486bb88e/warehouse/macaroons/services.py#L104-L107

3. log an exception via LOGGER.error (The message in cases 2 and 3 will have to be discussed)

And finally based on how we handle it, add unit tests for it. We can also add a helpful FAQ to suggest the user on how he can further debug the issue, on a case-by-case basis.

**Comment by di** [comment]
Hi @deveshks, thanks for the comment! Unfortunately @daneah and I had picked this issue to work on this today, sorry about that.

**Comment by deveshks** [comment]
> Hi @deveshks, thanks for the comment! Unfortunately @daneah and I had picked this issue to work on this today, sorry about that.

No worries @di and thanks for letting me know about it as well 😊 . 

May I also know what is the acceptable practices to let the maintainers know on an issue, that you would like to work on it, and  if you have any doubts you want to clarify before proceeding towards a PR, with the warehouse repo.

**Comment by di** [comment]
@deveshks I think what you did here was 100% what we're looking for, you just had the unfortunate luck of picking something we had already planned to work on, and I didn't see your comment in time. :)

**Comment by deveshks** [comment]
Thanks for the response. I will follow the same process going forward then.
