### ISSUE TITLE
Display issue with "View hashes" button

### ISSUE THREAD

**Issue by NathanBnm** [pypa/warehouse#7457]
The "View hashes" button text seems to be truncated when displayed in different languages. Don't know if it's due to translations or if it's a native bug, but here it is.

The corresponding string is located in the [templates/packaging/detail.html](https://github.com/pypa/warehouse/blob/master/warehouse/templates/packaging/detail.html#L312) file at line 321.

Here is a screenshot of the English version:
![image](https://user-images.githubusercontent.com/45366162/75452111-f41ded80-5971-11ea-9604-dbbd2b1e4d0a.png)

And here in the French version:
![image](https://user-images.githubusercontent.com/45366162/75452154-0bf57180-5972-11ea-9c18-66e424ce8a95.png)

The "hashes" word is not displayed. Maybe it's because of the `<span>` element surrounding it.

**Comment by di** [comment]
Looks like this was added in https://github.com/pypa/warehouse/pull/6561, perhaps by mistake. I don't see why the `span` tag need to be there, @nlhkabu care to chime in?

**Comment by nlhkabu** [comment]
Thanks for opening this ticket @NathanBnm.

@di - I think there is a reason for the span - my gut feeling is that it has something to do with mobile, but I will take a look :)

**Comment by nlhkabu** [comment]
On further investigation:

The markup has a `<span>` in it because "hashes" is hidden when the table header is visible, so the button only says "view":

![Screenshot from 2020-02-28 21-48-46](https://user-images.githubusercontent.com/3323703/75589966-1dbf3d80-5a74-11ea-9af1-2cd8bb347368.png)

On mobile, the button switches to "view hashes" because the column title is hidden:

![Screenshot from 2020-02-28 21-49-31](https://user-images.githubusercontent.com/3323703/75590014-421b1a00-5a74-11ea-8ab5-e78c6e736d89.png)

This obviously does not work for translation, so I will update the code to:

- Make the button always say "View"
- Ensure the "Hashes" title is visible, even on the smallest mobile screen
