### ISSUE TITLE
Make trove classifiers accordion only open one tab at once

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#755]
Currently you can view more than one section of trove classifiers at one time, for example, both ``By Environment`` and ``By Framework`` could be open.

Given the potential length of the page, I think we should consider enforcing the closing of other sections when a new one is opened.

* Copied from nlhkabu/warehouse-ui#2*

**Comment by di** [comment]
I created a branch which fixes this here: https://github.com/pypa/warehouse/compare/dabbdfe...di:fix-755

However, in doing so I noticed that this would introduce an issue with the UI that we probably don't want: Because some of the classifier lists are longer than the viewport, if one of them, such as "By Programming Language", is open:

![screen shot 2016-08-17 at 5 59 10 pm](https://cloud.githubusercontent.com/assets/294415/17754877/b931040c-64a4-11e6-8aa6-4a71e9f2b7af.png)
And we scroll to the bottom:

![screen shot 2016-08-17 at 6 10 13 pm](https://cloud.githubusercontent.com/assets/294415/17755080/eaa7dabe-64a5-11e6-9f5c-4434ea11f879.png)
When we click "By Development Status", it disappears, because it's much shorter, and the entire list has jumped out of the viewport:

![screen shot 2016-08-17 at 6 10 18 pm](https://cloud.githubusercontent.com/assets/294415/17755109/108cd54a-64a6-11e6-9533-3946a6647860.png)
I suppose we could address that by additionally forcing a jump to an anchor tag on the category, but I feel like that would be worse UX than what we've got as-is.

@nlhkabu, thoughts?

**Comment by nlhkabu** [comment]
This is a really difficult problem and I'm not sure that I have a solution.

My gut feeling is to pan the viewport back up to the activated accordion heading ala http://www.stampede-design.com/blog/demo/shaiful/large-accordion/large-accordion-fix.html

In this case, a pan/scroll should be less abrupt than jumping to the position, which might help... although, like you, I'm not sure this will actually be better.

Perhaps the solution then is to be content with allowing multiple accordion sections to be open at once and dropping this issue altogether?

**Comment by di** [comment]
> Perhaps the solution then is to be content with allowing multiple accordion sections to be open at once and dropping this issue altogether?

:thumbsup: from me.

**Comment by nlhkabu** [comment]
Ok, given your agreement @di, I am going to close this issue now. :)
