### ISSUE TITLE
HTTPError: 400 Client Error: This filename has already been used, use a different version, after deleting the repository

### ISSUE THREAD

**Issue by evandrocoan** [pypa/warehouse#7713]
**Describe the bug**
1. Upload a wheel for a new repository on pypi
1. Delete the whole repository
1. Upload a wheel the same repository on pypi
1. `HTTPError: 400 Client Error: This filename has already been used, use a different version.`

**Expected behavior**
1. Upload a wheel for a new repository on pypi
1. Delete the whole repository
1. Upload a wheel for the same repository on pypi
1. No errors of `This filename has already been used` because the repository was deleted. The new repository version names have nothing to do with the old repository which was deleted.

**Additional context**

When a whole repository is deleted, whoever creates a new repository under the old (free) name should not have to be forced to have their project releases names rejected by pypi. It does not make sense for a deleted project rule/force the version names for the new repository, which has nothing to do with the old repository.

**Comment by ewdurbin** [comment]
As mentioned in the help entry associated with this error message at https://pypi.org/help/#file-name-reuse, PyPI never allows reuse of a specific filename, even after a project is fully deleted.

This is a safeguard against malicious replacement of files and is expected behavior that will not change.
