### ISSUE TITLE
tar.gz file of the same release was rejected because wheel file occupied the file name space?

### ISSUE THREAD

**Issue by chfw** [pypa/warehouse#7833]
**Describe the bug**

I used to update a wheel package and then a tar.gz file. Now, the second tar.gz file was rejected this time around.

```
Uploading distributions to https://upload.pypi.org/legacy/
616
Uploading pyexcel-0.6.0-py2.py3-none-any.whl
617

618
  0%|          | 0.00/115k [00:00<?, ?B/s]
619
100%|██████████| 115k/115k [00:02<00:00, 53.3kB/s]
620
Uploading pyexcel-0.6.0.tar.gz
621

622
  0%|          | 0.00/802k [00:00<?, ?B/s]
623
HTTPError: 400 Client Error: This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
624
100%|██████████| 802k/802k [00:01<00:00, 726kB/s]
625
NOTE: Try --verbose to see response content.

```

upload log: https://github.com/pyexcel/pyexcel/runs/610131951?check_suite_focus=true

**Expected behavior**

tar.gz file can uploaded as well.

**To Reproduce**

**My Platform**

linux os.

**Additional context**

This package is python 3.6+ only. I am not sure if this blocks tar.gz file or not.

**Comment by jamadden** [comment]
I can confirm that uploading wheels and sdists (.tar.gz) for the same version of a release works; I did so for gevent just today. 

The logs show that `pyexcel-0.6.0.tar.gz` was already uploaded on Aug 20, 2017, 7:34:11 AM, and then it was removed within seconds. As the error message ("This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse") indicates, PyPI does not allow reusing filenames because of the potential for security issues and confusion. Thus, the upload attempt today, the 22, for the same file name was rejected. 

You could try using twine's ``—skip-existing` option.

If you feel that there is a way to improve PyPI's error messages in this case, please let us know by opening a new, specific issue.

**Comment by chfw** [comment]
I see. Thanks for your time. I forgotten I have tried a release 3 years ago.

and I can report that v0.6.1 had both files uploaded.
