### ISSUE TITLE
Warehouse project author name

### ISSUE THREAD

**Issue by reaperhulk** [pypa/warehouse#797]
On the warehouse search page each package currently has a `by <author>` where the author is the last username that released the package (https://warehouse.python.org/search/?q=cryptography). For larger projects this is a bit weird, as the username that uploaded the package is not necessarily the author (it may be an automated account or one of many authors that rotate as the release manager role shifts). It would be nice if there was some way to set that value for a project.

**Comment by dstufft** [comment]
We do have the "author" and "author_email" field here that we could use, but that would mean we can't always link to a user page since that's a freeform field and people can type literally anything into it. It also means that people can use it to imitate someone else (such as they can on Github with Git commits) just by putting someone else's name there.

I see a few possible options:

1. We just use the ``author`` and ``author_email`` field and if the email matches a user account, then display a link to that user's page (much like what Github does).
2. We change the verbiage from "Project by Author" to "Project uploaded by Uploader" or something.
3. We make it some kind of list of people that shows all of the people registered with that project (so something like "Project by Bob, Mary, and Jane".
4. We just remove the verbiage totally.

A question for @reaperhulk is whether he is against the "Released 1 week ago by reaperhulk" section at the top of the project detail page  https://warehouse.python.org/project/cryptography/).

I think part of the answer here is going to be design based since any of the answers above are equally doable.

**Comment by reaperhulk** [comment]
I'm okay with "project uploaded by", as it describes an action a particular account took. A list of people also sounds good, although some projects have a long list of maintainers and an unbounded list sounds like the sort of thing that's hard to account for in a layout.

**Comment by dstufft** [comment]
I think this has been solved now by #875
