### ISSUE TITLE
Badge is Squished when viewed in PyPi

### ISSUE THREAD

**Issue by SimiCode** [pypa/warehouse#8131]
**Describe the bug**
Viewing the black package page on PyPi shows the Pypi badge squeezed; One would be unable to view contents of the badge.
![image](https://user-images.githubusercontent.com/20975616/85016711-2f7f3a80-b162-11ea-9729-e0a9fdbd68cc.png)

**Expected behavior**
While on Github, it shows well:
![image](https://user-images.githubusercontent.com/20975616/85017019-b0d6cd00-b162-11ea-99e8-eac4532376ba.png)

**To Reproduce**
Visit: 
[Black PyPi](https://pypi.org/project/black/)
[Black Github](https://github.com/psf/black)

**Comment by di** [comment]
It looks like the issue is that the version it's attempting to render the url https://black.readthedocs.io/en/stable/_static/pypi.svg, which currently has the version `19.10b1.dev0+g6bedb5c.d20191029`, which just doesn't fit in the badge no matter where it's rendered:

![](https://black.readthedocs.io/en/stable/_static/pypi.svg)

I'm not sure why it's doing this but I don't think it's an issue with PyPI.
