### ISSUE TITLE
Format numbers (with localisation)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#817]
![number-formatting](https://cloud.githubusercontent.com/assets/3323703/11322682/d7dd1b32-90ee-11e5-9e6c-9c52eb3eb804.png)

Here in the UK, I would like to view this number as `69,806`.  In other places in the world, it should be formatted as `69 806`.

This is also relevant for floats, see: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

**Comment by dstufft** [comment]
With #832 this gets a bit more complicated. We're using ``L20n.js`` to handle translation which technically should handle this already. However it disables grouping separators (and doesn't currently handle date fields). We should be able to handle this using something like:

```javascript
var f = Intl.NumberFormat(navigator.languages, { useGrouping: true });
document.l10n.setAttributes(document.querySelector('[data-l10n-id="numProjects"]'), 'numberOfProjects', { num: f.format(96283) });
```

However, we'll need to write a bit of JS to handle this sanely. This is probably no longer an "easy" issue since it'll require a bit of JS trickery to make it work automatically.

**Comment by berkerpeksag** [comment]
L20n.js support has been removed in #1335 and I have added a `format_number` filter in https://github.com/pypa/warehouse/commit/e4965034f2c0e25e75f357f743527a9bc8c85a0a. Can this be closed now?
