### ISSUE TITLE
Project total_size is not updated when a release/file is removed

### ISSUE THREAD

**Issue by di** [pypa/warehouse#8213]
In https://github.com/pypa/pypi-support/issues/478 users are saying they have removed files/releases but this is not changing the `Project.total_size` for their project.

**Comment by ewdurbin** [comment]
must be a bug in https://github.com/pypa/warehouse/blob/1f834f848ef03660b4c099d75d752a80380d1536/warehouse/migrations/versions/d83f20495c10_handle_null_on_projects_total_size.py#L28

I will be able to take a look later today.

**Comment by ewdurbin** [comment]
Ah, it appears that because the trigger that updates the column is configured on the `release_files` table... but deleting a release operates on the `releases` table, that the trigger is not fired.

This is basically because we are relying on cascaded deletes from the `releases` table to remove the `release_files` row(s).
