### ISSUE TITLE
Attempting to view account settings for an account with 2FA enabled asks to reauthenticate even immediately after login

### ISSUE THREAD

**Issue by Julian** [pypa/warehouse#8441]
**Describe the bug**
After logging in, and immediately visiting the account settings page only a few seconds later, a "Confirm password to continue" page is shown.

My account has U2F 2FA enabled, in case that ends up being relevant.

**Expected behavior**

Immediately after login (and having provided both a password and the U2F), access should likely be enabled across any part of the site, including sensitive areas, until some timeout has elapsed.

**To Reproduce**

In a private window (or other place where you have not logged in), visit the home page, click log in, fill out your credentials, authenticate via U2F if applicable, then click "Account Settings" in the menu bar after logging in.

Quick video attached:

![login](https://user-images.githubusercontent.com/329822/90337291-84e39680-dfaf-11ea-93fb-602163e41af8.gif)

**My Platform**
FF80, macOS, U2F via Yubikey

**Additional context**

#8191 seems likely related (though don't know that the behavior is new after it).

**Comment by di** [comment]
Thanks for the report, I've noticed this as well. It looks like the initial login is not setting the "time to reauthenticate" in the session.

**Comment by imsahil007** [comment]
![output](https://user-images.githubusercontent.com/35963992/91219677-a4f62100-e738-11ea-9aae-b247a700c415.gif)
I couldn't create this issue again

**Comment by Julian** [comment]
Perhaps indeed 2FA/U2F is required to observe the behavior then?

**Comment by di** [comment]
Yes, it definitely is. The `record_auth_timestamp` function is only called when the user doesn't have 2FA set: https://github.com/pypa/warehouse/blob/ab78391c8e69173aa878c08f88259756de1db7b4/warehouse/accounts/views.py#L200

This needs to happen here as well:

https://github.com/pypa/warehouse/blob/ab78391c8e69173aa878c08f88259756de1db7b4/warehouse/accounts/views.py#L249-L261

Really, since `_login_user` is used in both, it should happen here instead:

https://github.com/pypa/warehouse/blob/ab78391c8e69173aa878c08f88259756de1db7b4/warehouse/accounts/views.py#L777-L788
