### ISSUE TITLE
/pypi/{package}/{version}/json: yanking an older release updates latest release's yanked_reason field

### ISSUE THREAD

**Issue by abn** [pypa/warehouse#8549]
**Describe the bug**
Yanking an older version of a package leads to unexpected side-effect for latest version's package info provided via the JSON endpoint. In particular, the `yanked_reason` field gets updated.

**Expected behavior**
When yanking a version of a package, no other verision's `yanked_reason` field should be updated.

**To Reproduce**
1. Create new package on test.pypi.org
2. Release version `0.2.0`.
3. Release version `0.3.0`.
4. Yank version `0.2.0`.
5. Check json endpoint of package version `0.3.0`.

```console
$ curl -sL https://test.pypi.org/pypi/abn-test-rss-yank/0.3.0/json | jq '.info.yanked'
false
$ curl -sL https://test.pypi.org/pypi/abn-test-rss-yank/0.3.0/json | jq '.info.yanked_reason'
"Testing Yank"
```

**My Platform**
N/A

**Additional context**
* Test package: https://test.pypi.org/project/abn-test-rss-yank/

**Comment by ewdurbin** [comment]
This appears to be due to this line:

https://github.com/pypa/warehouse/blob/bd2b3a22f4f84072eb03abb771a88ddab1489e7a/warehouse/legacy/api/json.py#L193

The reference to `r` here is a remnant from this iterator:

https://github.com/pypa/warehouse/blob/bd2b3a22f4f84072eb03abb771a88ddab1489e7a/warehouse/legacy/api/json.py#L129

The fix should be as direct as changing the earlier line to `release.yanked_reason`.

**Comment by abn** [comment]
Cheers for the quick fix @ewdurbin @di
