### ISSUE TITLE
Can I financially support Warehouse and other PyPA projects?

### ISSUE THREAD

**Issue by nchammas** [pypa/warehouse#856]
Y'all are doing the Lord's work here, I tell ya.

Is there a central pool I can give to to support PyPA projects? Or perhaps a way I can donate to the Warehouse project specifically?

I'm not sure if [donations to the PSF](https://www.python.org/psf/donations/) can be designated for specific projects.

**Comment by dstufft** [comment]
Hey,

Sorry for the delay in responding to you. I just moved on Friday so things are a bit hectic here.

We (the PyPA) do not currently have a way of accepting donations. Accepting donations comes with some overhead that nobody has really stepped up to handle, particularly since I don't believe that there's a whole lot we have to spend money on (all of our services like hosting etc, are donated) and the cost for people's time tends to be a lot more than we're likely to get donated. We totally appreciate the sentiment though!

**Comment by nchammas** [comment]
No worries, I understand.

Perhaps this is better discussed elsewhere, but has the PyPA considered using a platform like [BountySource's Salt](https://salt.bountysource.com/) ([FAQ](https://github.com/bountysource/core/wiki/Salt-Frequently-Asked-Questions))?

The Neovim team, for example, seems to have been very successful in funding its own development using Salt. And they've mostly been paying for people's time, not infrastructure.

There is also a related set of discussions on [Paying the piper](https://github.com/pybee/paying-the-piper).

Anyway, with all the good things coming out of the PyPA -- Warehouse, the Packaging Guide, improvements to pip, etc. -- which benefit so many people, it seems a shame there isn't a way to financially back the team.

If that kind of backing could make a difference, I'd be interested in hearing what the team needs to make it a reality--even if it was just as a short-term experiment. For example, you mentioned overhead. What kind of overhead specifically would need to be handled?

**Comment by ncoghlan** [comment]
From a PSF perspective, while we can accept earmarked donations, we don't really have a way to funnel donations to PyPA as such, so we can currently only accept in-kind donations that go towards providing the PyPI web service (e.g. Fastly for CDN, Rackspace for hosting, etc).

I'm optimistic that may change in 2016, though - we're just finishing up the process of hiring a paid infrastructure manager for the PSF, which will hopefully give us the capacity to more effectively administer freelance and contract activities targeting PSF provided services, including PyPI.

Another way the situation could change is if some of the PyPA organisers (e.g. @dstufft, @qwcode) were to approach the PSF about setting up a formal fiscal sponsorship arrangement (similar to the [arrangement with PyLadies]( https://psfmember.org/civicrm/contribute/transact?reset=1&id=6)), but it probably makes sense to first wait and see how things change with the infrastructure manager in place.

**Comment by nlhkabu** [comment]
Thanks for starting this thread @nchammas.

For what it is worth, I would certainly find it easier to make more time for the redesign were there a financial incentive.  I do my best to make progress on the project, but paid work always has to come first.  An income that corresponds to a number of development hours would allow me to make more *regular*, scheduled contributions, instead of having to 'snatch' a few hours here and there.  I am sure my experience here is not unique and there would be many PyPUG contributors who would benefit in the same way (not to mention the benefit to the projects).

**Comment by dstufft** [comment]
So I guess the question is, how can we accept money and then distribute it to folks like @nlhkabu where we can actually purchase some of their time to dedicate towards it? Should we just direct people who want to contribute to donate directly to those people? Should we try and work something out with the PSF? There's also options like what Twisted has done with the Software conservancy thing. I have no problem putting in time to make this sort of thing happen but it's far outside of my wheel house to be able to evaluate the options and push for one.

**Comment by nchammas** [comment]
In addition to the options that @dstufft mentioned, I'd once again call out [Salt](https://salt.bountysource.com/) as an option to look at. I haven't used it extensively, but my impression is that it has a relatively low overhead and directly lets us solve the problem of funding bits of development on PyPA projects.

Maybe @tarruda from the [Neovim](https://github.com/neovim/neovim) project can briefly chime in here? I think the Neovim team's experience with Salt may be a model we can follow.

**Comment by ncoghlan** [comment]
The main thing is having someone willing to take responsibility for directing funds that folks will accept as a legitimate PyPA authority, so if @dstufft is willing to do that (perhaps with @qwcode as a backup), it should be possible to work something out. (It's best if the folks administering the funds aren't themselves likely to be recipients of the funds in the near term, since it significantly reduces the potential for financial conflicts of interest)

In terms of what would be involved in setting up a fiscal sponsorship arrangement with the PSF and the potential benefits of doing so, the PyLadies organisers are probably the best folks to ask about that. Perhaps @econchick, @audreyr or @willingc could provide some insight?

**Comment by ncoghlan** [comment]
I'll also note that PSF fiscal sponsorship wouldn't be mutually exclusive with the idea of a PyPA team account on a platform like salt.bountysource.com or the revamped gratipay.com - the fiscal sponsorship merely lets the PSF collect and disburse funds on behalf of the sponsored project, as described in https://wiki.python.org/moin/FiscalSponsorship

The advantage from a sponsor perspective is that the PSF is a formally constituted non-profit organisation in the US, so many sponsors will be eligible for tax deductions when contributing through the PSF that they wouldn't receive when contributing through a payment platform like salt.bountysource.com.

**Comment by nchammas** [comment]
PSF fiscal sponsorship sounds good to me, and I agree it would definitely add additional incentive for people and companies to donate when the donation is tax-deductible.

**Comment by econchick** [comment]
I want to echo @ncoghlan 's suggestion to ask for fiscal sponsorship for PyPA - definitely a positive for PyLadies when collecting donations and allowing them to be tax-deductible.

\*puts on my PyLadies hat\* I will be upfront in that it can be a bit manual. For instance, I have to file for reimbursements against the PyLadies account; there's no easy way to directly draw against the account itself.  As well, it's one pool - there aren't sub-accounts for specific PyLadies locations (say, if PyLadies in AwesomeCity Town accepts $100 donation for help in running an event). I, as the designated "project manager" for the fiscal sponsorship relationship have to keep track that AwesomeCity Town PyLadies has $100, and have to "okay" their request for reimbursement. 

But being able to accept tax-deductible donations without the hassle of incorporating as a 501c3 (note: only US-based tax-deductible) heavily outweighs the manual cost of everything in our PoV.

\*puts on my PSF board member hat\* A simple email to the PSF to start the conversation would be all that's necessary at this point.  There wasn't much work at all from the perspective of PyLadies & PyPA (as well as the PSF).

**Comment by njsmith** [comment]
Another thing to consider is that it's entirely possible that if @dstufft and @nlhkabu (say) were to put together a proposal describing the cool stuff that they could do given $xx USD, then that the PSF might be willing to fund this out of existing funds. This is orthogonal to the original question about how to accept funds, but something to think about in any discussion of whether more funds would actually be useful...

**Comment by dstufft** [comment]
So, this is starting to get a better answer-- You can visit https://donate.pypi.io/ :)

**Comment by nchammas** [comment]
Related discussions for others coming through: #1315, #1321
