### ISSUE TITLE
Add Pygments support

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#876]
It would be great if code rendered in long descriptions could be syntax highlighted with a library like [pygments](http://pygments.org/docs).

I can handle the actual selection and application of colors in the CSS, if someone else is happy to integrate the library that applies the classes.  Related #800.

**Comment by dstufft** [comment]
Hmm, we should already be doing this too.

**Comment by dstufft** [comment]
Yes, if you take a look at https://warehouse-staging.python.org/project/dstufft.cryptography/ it already has the classes there. It just needs styled.

**Comment by nlhkabu** [comment]
OK.  So then, any code that is coming through without Pygments support (e.g. https://warehouse-staging.python.org/project/python-ldap-test/) is because the source file doesn't support it?

Would it be worthwhile documenting how users should write their READMEs so that they get code highlighting on PyPI?  ping @ddbeck

**Comment by dstufft** [comment]
Yea, they probably aren't instructing the rst renderer as to what language it is. Generally you want to do something like (taken from pyca/cryptography):

```
.. code-block:: pycon

    >>> from cryptography.fernet import Fernet
    >>> # Put this somewhere safe!
    >>> key = Fernet.generate_key()
    >>> f = Fernet(key)
    >>> token = f.encrypt(b"A really secret message. Not for prying eyes.")
    >>> token
    '...'
    >>> f.decrypt(token)
    'A really secret message. Not for prying eyes.'
```

The name (like ``pycon``) can be anything that shows up as a shortname from http://pygments.org/docs/lexers/.

**Comment by ryanhiebert** [comment]
For my stuff on PyPI I've found that _unrecognized_ languages also stop it from parsing. For example, with https://pypi.python.org/pypi/tox-travis, I have an example YAML file, and while GitHub recognized the rST, PyPI did not, and so assumed it was plain text. I had to remove the language specifier so PyPI would format it at all.

**Comment by ddbeck** [comment]
@nlhkabu Sorry not getting to this quicker! I already had it in mind to briefly encourage readmes in [the new tutorial about making packages](https://github.com/pypa/python-packaging-user-guide/issues/203), so I suppose the next step would be to provide guidelines on including a PyPI-friendly readme as well. I've opened [a new issue for the idea](https://github.com/pypa/python-packaging-user-guide/issues/210).

On another note, @ryanhiebert's report on unrecognized languages suggests that it would be nice if unrecognized lexers fell back to plain text rather than unformatted text. I'm not sure if that's something that would need to change in pygments or warehouse (or somewhere else) though.

**Comment by dstufft** [comment]
That'd be in https://github.com/pypa/readme probably.
