### ISSUE TITLE
Why nofollow on the homepage link?

### ISSUE THREAD

**Issue by MarcinJawor** [pypa/warehouse#8974]
I would like to consider removing rel="nofollow" attribute on the packages website links (just this one link).

Rationale:

1. All of the links in the extension description is already marked with nofollow
2. Extensions are already monitored for spam entries
3. This would serve as a gratification to the approved extension developer 

I would suggest to keep the rel="nofollow" attribute for the first month since the extension is posted, and after one month without any spam reports -> automatically remove nofollow.

I think Python extension developers deserve at least this one.

**Comment by di** [comment]
Thanks for raising the issue.

> Extensions are already monitored for spam entries

This is not really true. Since PyPI is volunteer-run, we don't currently have enough bandwidth to collect and act on spam reports. Occasionally we get user reports about spam, but usually that only happens when a) the user wants the package name or b) the user happens to see the package show up on the pypi.org homepage.

Having nofollow links on user-generated content helps discourage spam, but even with this we still get more spam than we can handle (e.g. I just looked for less than 30 seconds and found all these projects: https://pypi.org/search/?q=openload&o=-created)

In addition, the benefit of removing nofollow links (even for this one link) and slightly improving the SEO for legitimate users is far outweighed by the amount of work it would take to moderate even our existing spam, let alone the additional spam that we would get with this change.

Given that I'm going to close this, but thanks again for raising!
