### ISSUE TITLE
Implement PEP 629: versioning of the Simple repository API

### ISSUE THREAD

**Issue by brettcannon** [pypa/warehouse#9027]
**What's the problem this feature will solve?**
Implements [PEP 629](https://www.python.org/dev/peps/pep-0629/) which specifies the API version of the Simple repository API that's used.

**Describe the solution you'd like**
`<meta name="pypi:repository-version" content="1.0">` to appear on Simple repository API pages.

**Additional context**

I believe this will take updating:

- https://github.com/pypa/warehouse/tree/main/warehouse/templates/legacy/api/simple

And I would like to do the PR if that's okay.

**Comment by di** [comment]
I guess the question is whether the current `/simple` pages that PyPI provides are actually "version 1.0".

The PEP mentions that the python-requires metadata needed phased in, and the support for [PEP 592](https://www.python.org/dev/peps/pep-0592/) has also been added since then. IMO each of these would have been a new version if we consider [PEP 503](https://www.python.org/dev/peps/pep-0503/) to be the true "version 1.0".

**Comment by dstufft** [comment]
The PEP explicitly says the current version is 1.0.

**Comment by brettcannon** [comment]
I opened #9030 assuming that the templates are the only things that need updating.
