### ISSUE TITLE
pypi upload error

### ISSUE THREAD

**Issue by philippeller** [pypa/warehouse#9199]
Hi, I could not find anywhere else to get into contact, so I opened this issue.

I'm getting the error `The user 'peller' isn't allowed to upload to project 'dragoman'. See https://pypi.org/help/#project-name for more information. `, even though there is no such project on pipy. Could you please help me?

Everything worked fine on pypitest.

**Comment by di** [comment]
Hi @philippeller, sorry you're having trouble. The issue is that the project name has been previously registered, but all the releases have been removed. This likely falls into the "abandoned project" category of [PEP 541](https://www.python.org/dev/peps/pep-0541/), you should file an issue at https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME to acquire the project name.

**Comment by philippeller** [comment]
Thanks for the help & answer!
