### ISSUE TITLE
More compact "files" table

### ISSUE THREAD

**Issue by nedbat** [pypa/warehouse#929]
One advantage of the "classic" PyPI files list is that it was very compact: you could see at a glance the variety of files being offered.  The sorted file names gave almost a visual categorized catalog of the Python versions and kit types:

![old coverage.py files](http://imgur.com/zau5ubf.png)

On current Warehouse, the table is much sparser, and the columns wrap:
![new coverage.py files](http://imgur.com/1enm8sx.png)

As a humble suggestion, we don't need to see all of the checksum, or maybe we don't need to see any of it? GitHub has gotten people used to seeing a shortened version, with a longer one available for copying.

I understand the value of buffering the information with whitespace.  Maybe these tables offer more value by being dense?

**Comment by sigmavirus24** [comment]
This is also fairly easy to see with the cryptography page: https://warehouse.python.org/project/cryptography/

**Comment by dstufft** [comment]
I'm not sure if showing a shortened checksum is useful here, in Github that's not really a checksum it's a commit hash and anywhere you can use a commit hash in git you can use the shortest unique prefix without any issue. However that's not true for a checksum, you need the entire thing. That being said, I'm not sure it makes sense to show the checksum instead of just give a way of copying it easily since the vast majority of people will never bother to verify it, and if they did they're more likely to want to copy it rather than read it.

As far as wrapping goes, at some level it's going to be impossible to avoid wrapping in all cases because you can make some very long filenames which are completely valid. A lot of these won't wrap on legacy PyPI if you have a large enough monitor and you full screen your browser because legacy PyPI does not restrict the length of the view port at all. An example of a project with some very long filenames would be Numpy ([Legacy](https://pypi.python.org/pypi/numpy/), [Warehouse](https://warehouse.python.org/project/numpy/)). I think that Numpy for example would be pretty close to wrapping (or might even start to wrap) even if you gave it 100% of the width of the content area.

Anyways, this is a design decision for @nlhkabu!

**Comment by nlhkabu** [comment]
Yes, I agree. Now seeing this layout filled with checksums, I think you do lose legibility.  Going back to a link might be preferable.  I'll put together an alternative.

**Comment by alex** [comment]
What about something like the github "clone URL" dialog:

<img width="231" alt="screen shot 2016-01-27 at 11 06 39 am" src="https://cloud.githubusercontent.com/assets/772/12619452/145c59c6-c4e6-11e5-9bd4-0872f1e88ff3.png">

Specifically, an `<input />` that shows it truncated + a button for copy.

**Comment by nlhkabu** [comment]
Thanks for the suggest @alex ... the problem is that this is still going to take up at least as much horizontal space as the checksum does (though, granted, it would reduce the vertical spacing).

I think it's inevitable that we're going to get some of the file names wrapping, but it looks to me like I need to provide as much space as possible to try to avoid that on *most* packages.

**Comment by techtonik** [comment]
1. There are two cases for checksum - `validate` manually and `copy/paste` or `download` to check. For `validate` it is enough if status bar shows actual checksum instead of `clicking here copies`

2. The column with `Version` should be at least second or made downloadable, because moving eyes from left to right is not the best experience.

Actually I like the old way of swapped size and checksum places.

**Comment by nedbat** [comment]
Looks great, thanks! :)

**Comment by techtonik** [comment]
![image](https://cloud.githubusercontent.com/assets/515889/12867110/ea6c66c0-ccf5-11e5-88a4-d51e5ab7dc00.png)

Yes, much better. =)
