### ISSUE TITLE
Top projects and New Releases lists should be python-version dependant

### ISSUE THREAD

**Issue by mangecoeur** [pypa/warehouse#930]
The projets shown on the main page may not be available or relevant for the user's version of Python.

For example, the top projects list shows `simplejson` as the first result which makes no sense for Python3 users since it's built into the language..

For new users this could be confusing - someone may for instance try to explore the language by reviewing some of the most popular packages. For existing users it's useless information that pushes out more relevant results.

There probably needs to be a fairly visible python version switch (similar to the main Python docs), which also sets a preference cookie for the subsequent visits. Package results on the main page and search pages would be adjusted accordingly.

Perhaps also a "getting started" page with the possibility to set this option too.

**Comment by nchammas** [comment]
Probably a dup of #775.

Also, I'm not a fan of the idea of a version switch. That seems like something that better belongs strictly as a search filter.

**Comment by mangecoeur** [comment]
Firstly I don't think it's a dup because this is related to showing packages relevant to the python version - #775 is an different problem since it would be true even if the Python version issue didn't exist.

Secondly it would of course also make sense in a search filter, but since the front page also shows package results (effectively the result of a search with criteria for "top" and for "new") it makes sense to be able to filter those results also. This could take the form of a Python doc-style version selector or some other UI - whatever works best really...

**Comment by sigmavirus24** [comment]
Would this also auto-filter out packages in a search because the project mistakenly forgot to add Python 3 classifiers to their `setup.py`/`setup.cfg`?

**Comment by mangecoeur** [comment]
Several heuristics imho including  (if you set it for Python3):

1. Include only packages explicitly tagged python3. (probably too restrictive)
2. Assume packages tagged python2 but NOT python3 are python2 only (or dead)
3. Simply exclude only packages explicitly marked as Python2 only (I'm pretty sure there is a tag for that)

There are probably other combinations. Although, ironically, on further investigation simplejson would still appear in all of these since it is python3 compatible even though there's no point installing it. However that I think IS  part of #775 since it's more about finding a better definition of "top" than "most downloaded in all time"...

**Comment by nchammas** [comment]
> Firstly I don't think it's a dup

Sorry, I misspoke. I've edited my comment accordingly.

**Comment by sigmavirus24** [comment]
I don't think any of those heuristics are actually helpful outside of a search query. There are several projects that are still Python 2 only because they're undergoing a long, arduous process of adding Python 3 compatibility because of limited developer time and because only more recent versions of Python 3 have been sufficiently not broken for them. Those packages are not dead and in most cases are incredibly valuable (e.g., Twisted). They're adding Python 3 support but they can not do it over night. If a user says "I only want to see Python 3 packages" and then searches for Twisted, they won't see it by your heuristics. That's *actively harmful* to the community and to the users.

Finally, what about projects that set *no* classifiers (Python 2 or 3)? I take it those would be excluded as well because there's no point in installing them either.

**Comment by mangecoeur** [comment]
Well if you are running Python3 there doesn't seem to be much value in seeing packages you can't install. If you want to see the top and new packages it makes sense for those to be interesting packages *for you*, i.e. that run on the system you are on. Of course if you actually do a search you can filter or not for whatever you like - it's just a bit pointless to present you on the landing page with content that is irrelevant for you.

> what about projects that set no classifiers (Python 2 or 3)

Under heuristic 2, packages with no tags would be shown (since they are not tagged python2 OR python3, when the filter removes python2 AND NOT python3)
Under heuristic 3, packages with no tags would be shown since they are not explicitly tagged as Python2 only.

Finally:

> If a user says "I only want to see Python 3 packages" and then searches for Twisted, they won't see it by your heuristics.

So I wasn't talking about the search filter but rather the package suggestions on the home page. But while we are at it, that is precisely the behaviour I would expect of a search filter. A filter for Python3 that doesn't filter out packages that don't work on Python3 is entirely pointless.

**Comment by dstufft** [comment]
I can appreciate wanting to try and provide a list of "top packages" that more accurately reflects what version of Python the end user is running. However, I think at this point it doesn't make sense to try and filter this list. The list of top packages isn't really meant to be a primary interface for discovering packages that the user is going to be using but rather just a nice little snapshot into what other people are using.

On top of that, there are a couple of technical problems with trying to filter this list on the main page:

* This is going to be one of the most viewed pages on Warehouse since it is the primary landing page so we want to serve it from the cache wherever possible, however if we add some mechanism to change this then we'll likely need to add a ``Vary`` header on cookie which will destroy our ability to cache this page.
* We have a severe issue with the quality of information that we'd use to determine *if* something is Python 3 or not. At best we have some basic heuristics at worst we have dead wrong information.

Overall though, I think it will just work itself out overtime. As more people start moving towards Python 3 the list will naturally be influenced by projects that work on Python 3. As it is, all of the projects that are there *are* projects that run on Python 3 (including simplejson) which all of the methods of sorting will still include simplejson anyways (and simplejson I believe is still faster than the json in the standard library, so there is still a reason to use it).

Thanks for the issue though!
