### ISSUE TITLE
Add "/" to Simple Index Metatag to allow for XML parsing

### ISSUE THREAD

**Issue by whatatripp** [pypa/warehouse#9309]
**What's the problem this feature will solve?**
As noted in #9046, the changes to the Simple Index to implement repository versioning (see #9030) will break code that parses the index XML instead of HTML. A lot of this integrate code is in in the tools that Python developers rely on for their job, and when their tools break - their job is a bit harder.

While the [PEP 503](https://www.python.org/dev/peps/pep-0503/) specifications did clearly state that the Simple API is HTML and not XML... it *was* valid XML up until #9030. 

**Describe the solution you'd like**
Just adding a single forward slash to `detail.html` and `index.html` would do the trick. For example:

`<meta name="pypi:repository-version" content="1.0" />`

I'm totally happy to submit this as a pull request, as it's just two a two-character change... but I wanted to start with an Issue first to make sure this is okay.

**Additional context**

I realize this is something tool authors can definitely fix -- and it's something they can take the blame for mis-implementing int the first place. But at the end of the day, even if the tool is fixed.... the change to the API means that Python development teams are struggling to do their job and are a bit frustrated... then they are debugging the problem, discovering a tool upgraded is needed.... which means testing, upgrading, and then deploying a new version of that tool (and the other changes that come with the new version.

So one little slash (okay, two slashes in two files) could save a lot of headaches :)

**Comment by pradyunsg** [comment]
I don't directly maintain warehouse/PyPI, but I'll quickly jot down a couple of thoughts here none the less:

If the page was XML compatible, that was likely completely by accident. Tools depending on this were depending on a co-incidence, rather than a guarantee.

For the users who've been broken by this now, PyPI changing things to make their workflow work, hints that it's fine to do whatever they were doing. It's a call for PyPI maintainers to make though, but there has to be a line drawn somewhere about what's OK and what's not. :)

Given that this been out-and-about for more than a month now, we've likely already paid most of the churn cost of this; and I don't think it's worthwhile to pay this churn cost again.

Drawing the line at "this is what the standard is, and your tooling is making the wrong assumptions" is clear and fairly easy to communicate. I'm pretty sure most of such users/tooling aren't going to be proactive about changing their parsers if these slashes are added back anyway, so all we'd be doing is putting off the problem for sometime in the future, and setting precedence that "PyPI will change if we ask them".

**Comment by di** [comment]
Unfortunately the fact that this page was valid XML was just a coincidence and was never explicitly supported. The fact that people expect this to be valid XML as well severely limits what we are able to do with this API going forward.

Like @pradyunsg mentioned, we've already "eaten" the cost of this breaking change, and this is the first report we've gotten, so I'm not too keen to reverse it.

I'd advise using a HTML parser to parse this page instead of an XML parser. This will guarantee that your tool will continue to be able to parse this page in the future as it continues to change within the bounds of a valid HTML page.

Given that, I'm going to close this issue, but thanks very much for raising it first instead of just making a PR. If you need help determining how to use an HTML parser instead, @pradyunsg is a `pip` maintainer, and may be able to offer some advice as `pip` has been parsing this page as HTML since its inception.

**Comment by whatatripp** [comment]
Thanks @di, @pradyunsg ... I figured it didn't hurt to ask , just a single `/` after all ;)

Obviously I know how to parse HTML instead of XML, but it was more trying to save the hours of upgrade ​hassle 
of testing, etc. for our users...

FWIW; we chose XML parsing because the index files can be quite large (megabytes), and that lets us use forward-only readers that dispose of read nodes to drastically reduce processing and memory footprint. There are simply no HTML libraries that can do this, at least in .NET... and there still aren't 🙄

Do you plan on making other changes to the API going forward (i.e. upcoming months/years)? For now, will can simply just patch the index stream so we can use an XML reader... but depending on upcoming changes, we need to ultimately write a rudimentary forward-only parser.
