### ISSUE TITLE
Migrate all Sponsor data to the database.

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#9503]
**What's the problem this feature will solve?**

Currently due to copyright and trademarks that are incompatible with the license of this repository, PyPI uses a private repository [`pypi-theme`](https://github.com/python/pypi-theme) to store Sponsor logos.

These logos are rendered on the [sponsors page](https://pypi.org/sponsors) [using this template](https://github.com/pypa/warehouse/blob/main/warehouse/templates/pages/sponsors.html) and this [include](https://github.com/pypa/warehouse/blob/main/warehouse/templates/includes/sponsors.html).

We also render them in the [footer](https://github.com/pypa/warehouse/blob/main/warehouse/templates/base.html#L352) using this [include](https://github.com/pypa/warehouse/blob/main/warehouse/templates/includes/sponsors-footer.html) which references the dataset in [the aforementioned include](https://github.com/pypa/warehouse/blob/main/warehouse/templates/includes/sponsors.html).

And finally we render a subset of sponsor logos in [the sidebar](https://github.com/pypa/warehouse/blob/main/warehouse/templates/includes/sidebar-sponsor-logo.html) again using the same [aforementioned include](https://github.com/pypa/warehouse/blob/main/warehouse/templates/includes/sponsors.html).

At this point, the only reason we have the [`pypi-theme`](https://github.com/python/pypi-theme) repo is to house the Sponsor logos.

This makes @di and myself a bottleneck in updating sponsors and their logos on pypi.org.

**Describe the solution you'd like**

We should create a `Sponsor` model in the warehouse database that stores all of the various information encoded into the [sponsors include](https://github.com/pypa/warehouse/blob/main/warehouse/templates/includes/sponsors.html), as well as the ability to store an image in our object store that can later be referenced when rendering the page.

Then, we should update the rendering of sponsor logos throughout the site to use this model.

Additionally a new `is_sponsor_admin` column should be added to the [`User`](https://github.com/pypa/warehouse/blob/main/warehouse/accounts/models.py#L58) model which we will use to grant a new permission `sponsor_admin` in the [admin views](https://github.com/pypa/warehouse/tree/main/warehouse/admin) to a newly created admin panel to manage Sponsors. Users with `sponsor_admin` permissions should *only* be able to make changes to the Sponsor objects. You can see a similar behavior for the `moderator`/`is_moderator` permission/column in the admin app.

**Comment by ewdurbin** [comment]
This work will be done on behalf of the Python Software Foundation by @berinhard.

**Comment by ewdurbin** [comment]
For storing the Images, I think that will be blocked by me adding a new static bucket. In the meantime, please get started moving ahead simply storing a URL for the color and white logo options.

Also admin permissions may be a bit complex or difficult to handle, in the meantime, assume that all views can be guarded similar to the existing admin views so that only 'super user's can access the Sponsor panels. This may need input/review from @dstufft.

Other feature notes:
  - We probably want an `is_active` flag for each Sponsor so that they can be added prior to a "go live" date.
  - We probably want to leverage our cache purging feature to make updates render on next page load.

**Comment by dstufft** [comment]
Super user only is a pretty safe default. We'd only need to worry about anything more fine grained than that if we have a desire to grant someone the ability to manage sponsors without giving them full admin privileges.

**Comment by berinhard** [comment]
Hey @di, how are you? The next thing to improve the [new Pypi sponsors admin](https://github.com/pypa/warehouse/pull/9512) is to have this specific `sponsors_admin` permission to manage only sponsors data. @ewdurbin told me you would be the best person to guide me through this and that's why I'm pinging you =) 

From my initial research, I've wrote down a few changes I think I'll have to do to add this. Can you review them and point me to anything else I'm missing or things I should be aware of?

1. Add a new `is_sponsor_admin` boolean column to the [User model](https://github.com/pypa/warehouse/blob/main/warehouse/accounts/models.py#L75);
2. Add a new `(Allow, "groups:sponsor_admins", "sponsor_admin")` security policy to [`warehouse.config.RootFactory.__acl__`](https://github.com/pypa/warehouse/blob/main/warehouse/config.py#L59);
3. Update the [`_authenticate`](tweetdeck.twitter.com/) method to check against sponsors admin. An admin is both a moderator and sponsor admin;
4. Update [admin's sidebar view](https://github.com/pypa/warehouse/blob/main/warehouse/admin/views/core.py#L29) `view_config` decorator to allow `sponsor_admin` users to access it;
5. Only displays "Sponsors" section in the sidebar HTML for a sponsor admin;
6. Update `view_config` decorators for every sponsor admin view by changing permissions;
7. Update admin's `UserForm`, `detail.html` and `list.html` the with the new `is_sponsor_admin` boolean;
8. Unit test everything, of course =)

Thanks for your time!

**Comment by ewdurbin** [comment]
I think @dstufft might be more helpful with the authorization bits. Sorry if I misspoke.

**Comment by di** [comment]
I'm not @dstufft but that sounds like a good plan to me 🙂 

I agree with @ewdurbin that we should generalize this to `psf_staff`.

**Comment by berinhard** [comment]
Thanks for your comments! Certainly I was the one making confusion about the @ =}

**Comment by di** [comment]
@ewdurbin Is this done now that #9794 is merged?

**Comment by ewdurbin** [comment]
Indeed!
