### ISSUE TITLE
Can't upload a tarball after removing from test.pypi.org

### ISSUE THREAD

**Issue by matrixise** [pypa/warehouse#9582]
tested on test.pypi.org

I was testing my workflow with twine and a project. 
workflow: create the project on test.pypi.org, remote the project and the file.
I try to re-upload the same project/version and I get a 400, the filename has already been used, use a different version.
But in the web interface, my project does not exist anymore, I have dropped it.

I think you keep a reference in the database, but once dropped from the database, I could upload my project to pypi.

Any idea?

Thank you

**Comment by di** [comment]
Hi @matrixise, thanks for the report. I'm not sure I'm following exactly, are you saying that you're having issues uploading to pypi.org after uploading to test.pypi.org first?

**Comment by matrixise** [comment]
Hi @di 

nope, in fact, I was testing test.pypi.org with my workflow, and in fact, I have used `twine upload` upload ok, after, removed the version from `test.pypi.org` and tried a new upload with the same metadata (name,version) to `test.pypi.org`. Maybe I am wrong.

Is there a limitation in the workflow, to reupload the same version ?

PS: the project has been removed but I can't upload the project with the same version...

**Comment by di** [comment]
Sorry, I was confused by the "I could upload my project to pypi." part.

This behavior is intentional, the error message should have linked you to our help page which says ["PyPI does not allow for a filename to be reused, even once a project has been deleted and recreated."](https://pypi.org/help/#:~:text=PyPI%20does%20not%20allow%20for,and%20recreated.).

More details about why are here: https://stackoverflow.com/questions/52016336/how-to-upload-new-versions-of-project-to-pypi-with-twine/52130985#52130985

**Comment by matrixise** [comment]
@di I do understand for `pypi.org` but why for `test.pypi.org`?

tell me, is it the right solution with `--skip-existing`

```
twine upload -r test_pypi --skip-existing dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading dsmtpd-0.3-py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 11.2k/11.2k [00:00<00:00, 14.7kB/s]
  Skipping dsmtpd-0.3-py3-none-any.whl because it appears to already exist
Uploading dsmtpd-0.3.tar.gz
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 10.4k/10.4k [00:01<00:00, 9.39kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
This filename has already been used, use a different version. See https://test.pypi.org/help/#file-name-reuse for more information.
```

**Comment by di** [comment]
There are no actual differences in behavior between PyPI and TestPyPI. If you really need to use the same version number, you can make a `.post` release.

If you have existing distributions in the `dist` directory that have already been uploaded, then you should use `--skip-existing`, otherwise the upload will fail.

**Comment by matrixise** [comment]
okay, thank you for the explanation, I am going to close this issue. take care.
