### ISSUE TITLE
Change JS date formatting

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#959]
I like the human readable date formatting, but I think it is only useful for recent events.

"a few hours ago, today, this week" are fine, but anything beyond this starts to lose meaning.  For example, this timeline isn't really that useful:

![screenshot from 2016-02-06 10-15-11](https://cloud.githubusercontent.com/assets/3323703/12866136/9862cb52-ccba-11e5-8ce8-c9929f09b294.png)

ping @dstufft - I assume this is just a matter of adjusting our settings?

**Comment by dstufft** [comment]
Umm, I have no idea, but I assume it's doable.

**Comment by di** [comment]
@nlhkabu It would be very easy to change these all to just dates, e.g.:

<img width="185" alt="screen shot 2016-02-08 at 3 29 16 pm" src="https://cloud.githubusercontent.com/assets/294415/12898260/ca8fd398-ce79-11e5-96fb-ca27d1dcbf4e.png">

It would take a bit more work to choose one or the other depending on whether it's been more or less than a week. Which would you prefer?

**Comment by nlhkabu** [comment]
My strong preference is to choose one date format and use it everywhere across the site.  Even if we were to change this particular page to not use humanization, the same issue is going to exist elsewhere, for example:

- The authors page
- The main upload date for a package

So yes - anything up to a week - lets use humanized dates.  Anything over, let's go with the date format above.

p.s. is 'humanized' even a verb? :P

**Comment by dstufft** [comment]
Presumably this could be done just by adding more logic to [this line](https://github.com/pypa/warehouse/blob/c815aa92e6fbe0b6572f42f57eb3fcb59a82cd00/warehouse/static/js/main.js#L75). The only downside to doing it there is that it won't automatically go from relative to absolute if a page is left open, since that will only occur on page load, but I think that's a fairly reasonable caveat.
