### ISSUE TITLE
Switch sdist/wheel preference for older pip versions

### ISSUE THREAD

**Issue by mattip** [pypa/warehouse#9640]
**What's the problem this feature will solve?**

Over at NumPy we have run into a conundrum. We would like to stop supporting older manylinux2_12 (manylinux2010) wheels since they are built with CentOS6 which is 6 months past EOL. But this would be bad for people using [pip before 19.3 released Oct 2019](https://github.com/pypa/pip/blob/main/NEWS.rst#193-2019-10-14) since older pips do not recognize manylinux2_17 wheels (manylinux2014). For instance, see [this issue](https://github.com/numpy/numpy/issues/19192) caused by an older glibc.

**Describe the solution you'd like**

`pip install numpy` would query the PyPI index. If the pip version does not support `manylinux2_17`, and the user has not explicitly asked for a sdist, PyPI would return the latest binary wheel that pip supports. TBD: should an error/warning be returned?

This would allow NumPy and the scientific python stack to drop support for `manylinux2_12` and `manylinux2_5` (`manylinux1`)

**Additional context**

Carrot and stick: people wanting the latest and greatest NumPy, Scipy, scikit-learn, astropy would have to update their pip, which would help everyone: better resolver, better ux

**Comment by xavfernandez** [comment]
It is unclear for me what should change in this project (warehouse) to solve your issue as it seems more related to pip.
pip already provides the `--prefer-binary` option that should do what you suggest (but it isn't the default behavior).

**Comment by mattip** [comment]
I would like PyPI, which as I understand it is based on warehouse, to detect the pip version of the request originator, and adjust the results as explained above. This could be further qualified to python3.8 and earlier. Even if the pip default becomes `--prefer-binary` (see pypa/pip#9140), this will not help users with very old pip versions, like many CI systems or cloud clusters. I agree with the premise of the issue I linked to that building-from-source is rarely what end-users want, especially if they are using old versions of python and pip.

**Comment by rgommers** [comment]
I think the issue is that there there's the following for different kinds of dependencies:
```
# For build-time dependencies (in pyproject.toml)
[build-system]
requires = [...]

# For runtime dependencies (in pyproject.toml)
[project]
dependencies = [...]

# For Python version (in pyproject.toml) - and there's also trove classifiers for this
requires-python = ">=3.7"
```
But there's no `installer_requires`, `pip_requires`, `min_manylinux_version`, or some such thing. As a result, the default behavior cannot be made sensible, and we're forced to either keep supported an EOL platform like CentOS 6 (manylinux2010), or accept to get a stream of user complaints who get unexpected from-source builds that fail with potentially cryptic errors.

It's not 100% clear that this belongs in Warehouse indeed, but it belongs somewhere in the installer - index server interaction.

**Comment by di** [comment]
To restate the problem/request a bit (please correct me if I'm wrong): 
* older `pip` versions don't know about manylinux2014
* if `numpy` stops publishing manylinux2010 wheels, old `pip` versions will prefer newer source distributions over older manylinux2010 wheels
* installing from source will fail and/or be painful
* we can't change the behavior of older `pip` versions
* but we can change what they perceive to be available on PyPI
* we should "hide" source distributions when requests come from certain pip versions for certain releases

A few questions:

* How would PyPI know what releases to do this for? Presumably for this narrow use case, it would be possible to infer this per-release based on which manylinux wheels have been published for it, but what about other projects that want to declare some dependency on the installing `pip` version unrelated to manylinux?
* What about users that have an old `pip` version and _do_ want to compile from source, because there is no wheel for their platform/architecture? Wouldn't this effectively make `numpy` uninstallable for them?

It seems like the root of the problem is:
* users are using an old version of pip
* users are trying to install an unpinned version of numpy

Therefore, if `numpy`'s `setup.py` was able to detect the installing `pip` version and, for these versions of `pip` emit an error failing installation and telling the user to ether:
* upgrade their pip
* pin to some specific last-known version of `numpy` compatible with the `pip` version in use
* (ideally, do both)

Whichever action the user takes would resolve the issue for them. This would effectively mean that anyone installing an unpinned `numpy` with an old version of `pip` would get a deployment/installation failure, but I think that's an accepted risk when not pinning versions.

**Comment by dstufft** [comment]
This is pretty much a non starter. It would require adding a ``Vary: User-Agent`` to our responses, which would drastically reduce our ability to cache the `/simple/` API.

**Comment by mattip** [comment]
> Therefore, if numpy's setup.py was able to detect the installing pip version and ...

This is an interesting line of thought, I hadn't considered that. I wonder how many users would complain, but maybe that is the price they pay for not updating their pip.

> It would require adding a Vary: User-Agent to our responses ...

Thanks that makes sense. I will close this and take the `setup.py` idea back to the NumPy team.

**Comment by rgommers** [comment]
Thanks for the quick feedback everyone!

> Therefore, if numpy's setup.py was able to detect the installing pip version

For the record, I had considered this and tried to find some solution, but came up empty.

I'll add more details on the linked numpy issue (https://github.com/numpy/numpy/issues/19192).
