### ISSUE TITLE
<title> contains a leading bullet on home and search pages

### ISSUE THREAD

**Issue by pauleveritt** [pypa/warehouse#966]
Very minor issue, the <title> node on the home and search pages has: <title> · Warehouse (PyPI)</title>

**Comment by di** [comment]
This is because some templates (including `index.html` and `search/results.html`) are missing the `title` block.

@dstufft, @nlhkabu, which would be preferred: hiding the bullet if the block is empty, or ensuring that all templates have a `title` block? If the latter, is there a string which would be good to use as a default?

**Comment by di** [comment]
Technically a duplicate of #784.

**Comment by dstufft** [comment]
Sort of a duplicate, though sort of not, the question of how do we handle a page that legitly doesn't have a title is a reasonable question I think. Options being:

* Let the leading dot happen
* Make the dot only show up if there is a title
* Make sure all pages have a title and don't allow any to have an empty title

**Comment by nlhkabu** [comment]
:+1: +1 for option 2.  Lets only show the dot if there is a title :D
