### ISSUE TITLE
Support ie8

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#979]
At the moment ie8 is totally broken.  I don't want to spend a heap of time making it *perfect*, but I would like it to be *functional*.

As far as I can tell, these are the primary issues:

- [ ] HTML5 tags not rendering (look at fix with modernizr)
- [ ] SVGs do not display (provide [png fallback](http://ohdoylerules.com/snippets/modernizr-svg-fallback-to-png))
- [ ] JS not working (I don't know what the solution is for this - will need to debug)

**Comment by agronholm** [comment]
I mean no disrespect, but IE < 11 has been EOL'd beginning Jan 12th 2016. So why go through this effort when its vendor will not even supply security patches anymore?

**Comment by nlhkabu** [comment]
Because we still have almost 5000 users per month on ie8 (primarily in China).  I expect this will decline, but it still a large enough number to justify spending a couple of hours debugging.

**Comment by di** [comment]
JS is not working because jQuery 2.x only supports IE 9+: http://jquery.com/browser-support/

**Comment by dstufft** [comment]
Given that jQuery doesn't work on IE8 nor does l20n.js does it make sense to try and support this still? We're using jQuery to do a "client side include" of content like the login/logout/current-user indicator on each page so that the main content can be cached once for all users, but that additional content can be added post-cache. So unless we come up with a IE8 compliant solution to that, they're not going to be able to access any logged in areas of Warehouse.

**Comment by nlhkabu** [comment]
Ok, given this complexity, let's drop this for now and respond should we have any significant negative community feedback.
