### ISSUE TITLE
Automatically focus the 2FA input field

### ISSUE THREAD

**Issue by rbarrois** [pypa/warehouse#9805]
**What's the problem this feature will solve?**
When logging into PyPI with a 2FA-enabled account, the "authentication code" field should be auto-selected to simplify input by users.

**Describe the solution you'd like**
Modify the form design to put the focus on the primary field automatically.

**Additional context**
Tested under Linux with both Firefox (`78.4.1esr`) and Chromium (`86.0.4240.193`)

NB: If this feature interests the Warehouse project, I'll happily submit a pull-request to implement it.

**Comment by di** [comment]
Thanks for the feature request. Since we have users that use security devices WebAuthN instead of authentication apps that use a TOTP code, I don't think it would make sense to universally autofocus this field for all users.

In addition, we have users with both enabled, which makes it ambiguous whether the user will want to use WebAuthN or TOTP.

**Comment by ewjoachim** [comment]
Would the autofocus be a problem for WebAuthN users ?

**Comment by ewjoachim** [comment]
Ooooh it's a different field, I get it.

My suggestion:
- If only one 2FA method is enabled, put the focus in it's corresponding input
- If 2 (or more... Maybe someday) methods are enabled, don't change the focus from the default browser behaviour.
