### ISSUE TITLE
Upload failed (400)

### ISSUE THREAD

**Issue by 13021656835** [pypa/warehouse#9900]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by 13021656835** [comment]
Upload failed (400): Invalid value for blake2_256_digest. Error: Use a valid, hex-encoded, BLAKE2 message digest.

**Comment by ewjoachim** [comment]
Hello,

It's apparent that you have a problem.
What's not apparent, though, is what problem you have.

Please remember that this is not an automated answering machine here, we are real humans, most of us using our personal free time to run this open-source project. When we receive a report such as yours, we take time to investigate, understand and, when possible provide guidance and a resolution (if the problem is linked to the software that is being developed in this repository). Your report gives us mostly none of the information we'd need to start helping you.

I invite you to re-read the sections of the issue template that you ignored above (the first post of the page), and edit it to add the information requested there.
