### ISSUE TITLE
Send confirmation when email address changed

### ISSUE THREAD

**Issue by edmorley** [pypa/warehouse#998]
Currently on PyPI, if a user changes their contact email address, there is no notification to the old email address, meaning account compromise can go unnoticed.

This means that an attacker can silently prevent other important security notifications (eg #997) from being sent to the real owner.

**Comment by brainwane** [comment]
Thanks for another great suggestion, @edmorley, and sorry for the slow response!

This would be a very useful security feature, and now that #2898 is written and merged, it's far easier to add this feature.

Today in [our development meeting](https://wiki.python.org/psf/PackagingWG/2018-02-20-Warehouse) we discussed where this should go on [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap).

Since this feature isn't something that legacy PyPI has, I've moved the issue to a future milestone. But that doesn't have to stop a volunteer from working on it now; if someone wants to write up a pull request for it, go ahead!

Thanks and sorry again for the wait.

**Comment by waseem18** [comment]
I think we should send an email whenever an

- email is added
- email is deleted
- email has been changed to primary email

**Comment by waseem18** [comment]
@brainwane I'm looking into this and will soon put up a PR.

**Comment by di** [comment]
@waseem18 We already send an email when a new address is added (the "verification" email). I don't think deleting an email should require a notification, most likely the address will be unused/invalid anyways, and a "primary change" action is the one with real security implications, so I think this issue is good. Thanks for your work!

**Comment by waseem18** [comment]
Your welcome @di :)
